Week4 [STEP 2] 쿼카
yagom-academy/swift-starter-Round4 pull request #11
Opened 2022-01-04 08:31 UTC by Quokkaaa

안녕하세요 글렌! @Journey36 
요구사항 잘못 파악했다가 정말많이 해맸네요 ㅠㅠ
`startFitnessProgram`메서드를 구현하다보니 코드 량이 많이 길어진 부분이 마음에 걸리네요..^^ 
~*리펙토링 하는 시간을 거쳐야할것같습니다 하하..*~
에러구문과 class와 struct사용하는 법이 많이어려웠던것같습니다.
모두 구현하지 못했지만 시간이 길어지기만 할것같아 PR을 보냅니다!!
잘 부탁드릴게요

# 고민한점
- `errors`타입을 `LocalizedError`프로토콜을 채택하는것이 에러의 설명문구를 출력하는데 적합하다고 판단하였으나 기본제공하는 연산프로퍼티의 옵셔널로 코드의 길이가 길어질것같아 `Error`프로토콜로 다시 변경하였습니다.
- 예외처리를 구현할때 최종적으로 throws를 하는 메서드(=실행하는 메서드?)에 do catch문을 사용하여 한번에 처리하는게 적절하다고 판단하여 main파일내에 작성하였는데 적절하게 구현을 하였는지 ?궁금합니다.
- `main` 파일내 코드가 한곳에 모여있다보니 코드읽는데 번거로울 수 있을것같아 파일을 분리해보았습니다.

# 해결하지못한점
- 마지막에 출력되는 컨디션 값들이 계산되어 출력되지않습니다. 값이 복사되어 데이터 연동이 안된것으로 파악하여 `BodyCondition`타입을 `Class`로 변경해보았으나 운동목표치를 입력할때 예기치 못한 `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)` 라는 오류를 발견하였는데 해결방법을 찾지 못했습니다.

2022-01-04 14:54 UTC, Journey36 requested changes
@Quokkaaa
안녕하세요, 쿼카님. Step2 진행하느라 수고 많으셨습니다.
우선적으로 확인된 부분에 코멘트 남겼습니다. 확인 부탁드립니다.
그리고 아직 완성이 안되어 그런지 결과값이 제대로 나오지 않네요!

2022-01-04 14:54 UTC, iluxsm commented on CodeStarterCamp_Week4/main.swift
> +
리터럴 값을 그대로 하드코딩하지 않고, 열거형으로 관리하려는 좋은 시도가 보이네요! 👍

2022-01-04 14:54 UTC, iluxsm commented on CodeStarterCamp_Week4/main.swift
> +struct BodyCondition {
왜 클래스로 변경했나요?

2022-01-04 14:54 UTC, iluxsm commented on CodeStarterCamp_Week4/main.swift
> +        print("\(Guidance.WhatRoutineWouldYouLikeToWorkOn.message)?")
별거 아니긴한데 물음표나 콜론도 message안에 넣어줄 수 있지 않을까요? 😂

2022-01-04 14:54 UTC, iluxsm commented on CodeStarterCamp_Week4/main.swift
> +        guard let routineChoise = readLine(), let intRoutineChoise = Int(routineChoise),
int-를 붙인 네이밍보다, -number를 활용한 네이밍은 어떤가요? 타입보다는 역할에 집중하는 네이밍이 조금 더 가독성이 좋을 것 같아요.

2022-01-04 14:54 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +        guard let inputMemberName = readLine()?.replacingOccurrences(of: " ", with: ""),
여기의 `replacingOccurrences(of:with:)`은 어떻게 동작할까요? 🙂

2022-01-04 14:54 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +        guard let muscularEndurance = readLine(), let _ = Int(muscularEndurance) else {
타입 변환을 입력받을 때 함께 할 수 있지 않을까요?

2022-01-04 14:54 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +            }
guard 구문으로 작성하신 이유가 있나요?

2022-01-04 14:54 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +        print("\(Guidance.helloWhatYourName.description)?")
description으로 네이밍을 변경한 이유는 뭔가요?

2022-01-04 14:54 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +class Routine {
클래스로 변경한 이유는요?

2022-01-04 14:54 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +            routines.forEach { $0.exercises[1].action() }
[1]은 무엇을 뜻하나요?

2022-01-05 03:33 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +        print("\(Guidance.WhatRoutineWouldYouLikeToWorkOn.message)?")
처음에는 콜론이 가이던스메세지랑 연관이없다고 생각했었는데요
다시생각해보니 포함해도 별 상관없을것같네요 ㅎㅎ

2022-01-05 03:37 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +        guard let routineChoise = readLine(), let intRoutineChoise = Int(routineChoise),
number라는 네이밍이 더 직관적이라고 생각합니다 ㅎㅎ

2022-01-05 03:54 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +        guard let muscularEndurance = readLine(), let _ = Int(muscularEndurance) else {
음,,, 저는 Int(readLine())이와같이 감쌋을때 오류가 났는데 혹시 어떤방법으로 해볼 수 있을까요 ?

2022-01-05 03:59 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +            }
guard 구문을 사용하면 if코드를 훨씬 갈견하고 읽기 좋게 구성할 수 있어 guard 문을 선택했습니다.
else블록을 처리하지않고 예외사항만을 처리할 수 있다고 판단했어요

2022-01-05 04:00 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +        print("\(Guidance.helloWhatYourName.description)?")
message도 직관적이라고 생각했지만 apple공식문서에서 에러설명하는 부분을 description변수명으로 사용하는것같아 변경하였습니다.

2022-01-05 04:01 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +            routines.forEach { $0.exercises[1].action() }
두번째 프로퍼티인 let action 을 가르키는것으로 이해했어요!

2022-01-05 05:41 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +        guard let inputMemberName = readLine()?.replacingOccurrences(of: " ", with: ""),
readLine()에서 입력받은 값에서 of: 매개변수로 받은 값을 제거하고 새로운 문자열 값으로 guard let inputMemberName에 할당될것같아요!

2022-01-05 05:47 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +struct BodyCondition {
클래스로 지정했던 이유는 주소를 참조하기때문입니다.
struct타입의 인스턴스에 class인 BodyCondition타입의 값을 할당하면 값이 복사되는게 아니라 참조되기때문에 근력들이나 피로도의 값들의 주소를 통해 데이터를 다룰 수 있겠다는 판단이 들어서 class로 변경을 했었습니다.
그런데 Circular Reference라는 조금은 복잡한 에러를 만났는데 해결하는데 시간이 많이걸려 struct로 다시 변경하였습니다.

2022-01-05 05:47 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +
감사합니다

2022-01-05 05:49 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +class Routine {
순환 참조문제를 해결하기위해 잠시 class로 변경했었던것같습니다. 현재는 struct로 지정했어요!! 그 이유는 참조를 아직잘 이해한것같지않다는 판단이들어서입니다 ㅠㅠ

2022-01-06 03:45 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +        guard let inputMemberName = readLine()?.replacingOccurrences(of: " ", with: ""),
사용자의 돌발적인 입력을 방지하는 좋은 코드라고 생각이 드네요. 🙂
그럼 해당 코드에서 `trimmingCharacters(in:)`를 사용하게 되면, `replacingOccurrences(of:with:)`와는 어떤 차이가 있을까요? 🤔

2022-01-06 03:46 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +        guard let inputMemberName = readLine()?.replacingOccurrences(of: " ", with: ""),
사용자의 입력 실수를 방지할 수 있는 좋은 코드라는 생각이 드네요. 🙂
그럼 해당 코드에서 `trimmingCharacters(in:)`를 사용하게 되면, `replacingOccurrences(of:with:)`와는 어떤 차이가 있을까요? 🤔

2022-01-06 03:48 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +        guard let muscularEndurance = readLine(), let _ = Int(muscularEndurance) else {
`??`에 대해서 알고 계시다면 가능할 것 같습니다 ㅎㅎ

2022-01-06 03:49 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +        guard let muscularEndurance = readLine(), let _ = Int(muscularEndurance) else {
우선 말씀해주신 `Int(readLine())`에서 왜 오류가 나는지 알고 계셔야할 것 같구요.
알고 계신다면 `??`에 대해서 공부해보시면 가능할 것 같습니다 ㅎㅎ

2022-01-06 04:55 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +            }
그런데 현재 코드에서는 사실 if 문과 별 차이가 없어보이네요.
참고로 guard 구문은 특정 상황에는 한 번 비틀어 생각해야 하는 부분이 존재하죠.
위와 같은 상황이나 또는 다른 예를 들면:
```swift
let a = Int.random(1...10)

if a != 10 { print("Wrong") }

guard a == 10 else { print("Wrong") }
```
자신만의 기준을 잘 세워서 사용하시면 좋을 것 같습니다. 🙂🙂

2022-01-27 10:17 UTC, closed without merging