Week4 [STEP 2] mint3382
yagom-academy/swift-starter-Round4 pull request #112
Opened 2023-03-14 17:33 UTC by mint3382

@wonbi92 
안녕하세요 원비! 
나름 열심히 고쳐본 step2입니다~
원비와 밈의 조언으로 조금이나마 더 깔끔한 코드가 된 것 같은 느낌적인 느낌?! 
잘 부탁드려요!!

## 고민한 점
### 기능 분리
너무 많은 기능이 한 함수에 담겨 있는 것 같아 고민하다가 밈의 조언에 따라 매니저를 만들어 주었습니다. 트레이너가 운동을 시켜주는 느낌으로요! 트레이너가 운동 기구에다가 회원이 해야하는 루틴의 개수를 설정하면 Routine 타입에서 숫자가 제대로 입력되었는지 확인 후 잘못 입력되었으면 다시 입력받을 수 있게 합니다. 회원이 지쳐서 못하는 것과 관련한 피로도를 관리해주는 것은 트레이너의 역할이니 그 부분은 매니저 타입에 넣었습니다. 

### 피로도는 0 이하로 내려가지 않게
동적휴식에서 피로도를 줄여주는데 이때 피로도가 음수인 것을 말이 안되니 피로도가 0이하로 내려가지 않게 for문을 만들어 보았어요.

## 해결하지 못한 점

## 조언을 얻고 싶은 점
### do {}
이 do에 대해서 찾아봤는데요. 사실 {}만 벗기면 do가 없어도 사용할 수 있잖아요. 그런데 제가 찾아본 바로는 이것은 레이블이 지정된 do 문으로 코드라인을 설명하는, 이름이 있지만 함수는 아닌 코드 블록으로 만드는 방법이라고 해요. 좀 더 한눈에 보고 이해하기 좋게요. 제가 이해한 것이 맞을까요? 공식문서에서는 찾지 못했어요...

2023-03-15 06:47 UTC, wonbi92 requested changes
@mint3382 
안녕하세요 민트님!
스탭2도 잘 작성해주셨어요. 👍
요번에는 약간의 수정이 필요해보이니 코맨트 참고하셔서 수정해주세요!

> 이 do에 대해서 찾아봤는데요. 사실 {}만 벗기면 do가 없어도 사용할 수 있잖아요. 그런데 제가 찾아본 바로는 이것은 레이블이 지정된 do 문으로 코드라인을 설명하는, 이름이 있지만 함수는 아닌 코드 블록으로 만드는 방법이라고 해요. 좀 더 한눈에 보고 이해하기 좋게요. 제가 이해한 것이 맞을까요? 공식문서에서는 찾지 못했어요...

- 잘 파악하신거 같아요! 사실, 대부분 사용하지 않는 문법이라.. 찾기 좀 힘드셨을거 같긴 합니다 😅
- 이런것도 있구나~ 정도로 알고 넘어가시면 될거 같아요!

> 너무 많은 기능이 한 함수에 담겨 있는 것 같아 고민하다가 밈의 조언에 따라 매니저를 만들어 주었습니다. 트레이너가 운동을 시켜주는 느낌으로요! 트레이너가 운동 기구에다가 회원이 해야하는 루틴의 개수를 설정하면 Routine 타입에서 숫자가 제대로 입력되었는지 확인 후 잘못 입력되었으면 다시 입력받을 수 있게 합니다. 회원이 지쳐서 못하는 것과 관련한 피로도를 관리해주는 것은 트레이너의 역할이니 그 부분은 매니저 타입에 넣었습니다.

- 각 객체가 어떤일을 해야하는지 잘 설명해주셨어요!
- 다만, 코맨트를 통해 조금 더 고민해보실 점들을 적어두었으니 참고해보시면 좋을거 같아요!

코맨트를 참고하셔서 고민해보시고 수정해보세요~!
아직 시간이 많으니 충분히 고민해보시고 공부해보시기 바랍니다~!

2023-03-15 06:47 UTC, wonbi92 commented on CodeStarterCamp_Week4/Activities.swift
> +        }
음.. 지금 로직상으로는 동적휴식이 제대로 동작하지 않는거 같아요! 
한번 미션잘 읽어보고 수정해볼까요! 😁

2023-03-15 06:47 UTC, wonbi92 commented on CodeStarterCamp_Week4/Activities.swift
> +        case .sitUp: do {
말씀주신대로 do 문구는 클로저로 코드블럭을 나타내 구분지을 때 사용하기도 합니다! 😁
사람에 따라 다르겠지만.. 저는 잘 사용하지 않긴 해요! 역시 말씀해주신대로 없어도 잘 동작하긴 하니까요! ㅎㅎ 

그럼에도 애플이 만들어둔 이유는 분명 있겠죠?
각각의 동작을 클로저 타입의 상수로 만들어서 그 상수를 호출하는 방식으로 쓰면 쓸 수는 있을거 같아요! 
요 방법도 일반적으로 do 구문 없이 사용하겠지만.. 😅

2023-03-15 06:47 UTC, wonbi92 commented on CodeStarterCamp_Week4/ErrorCatch.swift
> +
요 개행은 어떤 의미일까요? 👀

2023-03-15 06:47 UTC, wonbi92 commented on CodeStarterCamp_Week4/Maneger.swift
> +
요 캐치문은 아무것도 하지 않네요? 👀
왜 이 캐치문을 작성해주셨는지 이해는 됩니다만, 미리 지정한 에러타입이 아닌 다른 에러들은 어떻게 처리할지 간단하게라도 출력해주는게 좋을거 같아요!

2023-03-15 06:47 UTC, wonbi92 commented on CodeStarterCamp_Week4/Maneger.swift
> +    }
요건 제 개인적인 생각입니다만, 이 메서드는 각 루틴을 매개변수 만큼 반복하는 메서드죠?
저였다면, 루틴을 실행하는 메서드와 루틴을 매개변수 만큼 반복실행 시키는 메서드를 나눌 거 같긴 해요.

이렇게 하면 for문이 두번 중첩되는 것도 막을 수 있을거 같구요! 
한번 고민해보세요~

2023-03-15 06:47 UTC, wonbi92 commented on CodeStarterCamp_Week4/main.swift
> +var trainer = Manager(member: mom, routine: special)
모든 타입이 변수로 선언되어 있네요? 이유가 있을까요? 👀

2023-03-15 06:47 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +    }
루틴이라는 객체가 매니저에게 입력을 요청하고 운동을 시키라 요청하는게 맞을까요? 🤔

물론, 미션에서 루틴을 통해서 입력받으라 제시하긴 했습니다만, 이 요구사항은 매니저라는 객체가 없을 때를 의미한다 생각해요.
지금 매니저라는 객체를 만들었으니, 루틴을 몇번 반복할지 입력받고, 피로도를 관리해주는 객체는 매니저가 되어야 겠죠?
메인 소스파일에서 민트님이 매니저를 통해 루틴을 받는 것 처럼요!

요러한 문제 때문에 처음 입력을 받는 `setCount()` 호출 이후로 잘못된 입력을 받았을 때, `manager.setRoutine()`를 호출하고 있네요. 
뭔가.. 이상하죠? 
루틴 객체가 매니저라는 객체를 소유하고 있는것도.. 좀 어색해 보이기도 하네요!

이런 경우 각 객체간 결합도가 너무 높아 로직을 수정하기가 매우 힘들어집니다. 또한 요구사항이 변경되면 어디서부터 수정해야 할지 갈피를 못잡게 되기도 하죠 🫠

각각의 객체가 어떤일을 해야하고, 그 객체들 사이에서 어떤 메시지(메서드를 호출하는 것을 의미합니다.)를 주고받아야 할지 한번 더 정리해보세요! 
이러한 고민이 바로 객체지향 프로그래밍의 시작입니다! 😁

2023-03-15 14:21 UTC, mint3382 commented
@wonbi92 
안녕하세요 원비! 
남겨주신 코멘트들을 토대로 코드를 수정해보았습니다. 

### do{}
일단 이 do {}는 전부 삭제했습니다. 없어도 되고 그렇게 할 때 더 코드가 짧아져서요.

### 이중 for 문 분리
바깥 쪽 루프와 안 쪽 루프를 각자 다른 메서드로 만들었습니다. 피로도 에러처리 때문에 두개의 메서드 모두 do-catch문을 써주어야 했는데 밑에 가서 마지막에 이미 끝난 루틴인데도 "루틴을 중단합니다. " 라는 문구가 나오지 않게 하는 데게 유용하게 쓰인 것 같습니다. 

### 피로도가 0 아래로 내려갈 때
피로도가 0 아래로 내려가는 경우 피로도 수치 표현은 계속해서 0에 머물러야 한다고 생각했습니다. 마이너스 피로도..는 뭔가 좀 말이 안되는 것 같았어요. 고민하다가 새로운 에러 케이스로 만들어 주었습니다. 

### 각각의 객체들 역할
객체 : 트레이너 , 회원 , 운동루틴, 활동(운동)

트레이너에게 회원이 등록된다.
-> 트레이너는 회원의 BodyCondition을 체크할 수 있다.
-> 트레이너는 회원에게 운동 루틴을 몇 번 시킬지 정할 수 있다.
-> 트레이너는 회원의 피로도를 확인하고 운동을 중단시킬 수 있다.

운동 루틴에는 운동이 담겨있다.
-> 반복하고 싶은 운동들을 순서대로 담는다.

회원이 운동루틴을 따라 운동을 한다.
-> 회원은 운동을 하며 BodyCondition의 수치 변화가 일어난다.
-> 휴식을 취할 때 피로도는 0 아래로 내려갈 수 없다.

2023-03-15 14:28 UTC, mint3382 commented on CodeStarterCamp_Week4/main.swift
> +var trainer = Manager(member: mom, routine: special)
Routine 타입인 special을 제외하고는 mom이라는 것과 trainer라는 것은 변하지 않는 존재기에 let으로 수정했습니다!

2023-03-16 06:50 UTC, wonbi92 approved these changes
@mint3382 
안녕하세요 민트님!
잘 수정해주셨어요! 고생하셨습니다!

2023-03-16 06:50 UTC, wonbi92 commented on CodeStarterCamp_Week4/Maneger.swift
> +    private func roundLoop(number: Int, name routine: Routine) {
몇번 반복할지 정하는 매개변수이니까 `number`도 좋지만, 저는 `times` 정도의 네이밍은 어떨까~ 합니다 ㅎㅎ

2023-03-16 06:51 UTC, merged