Week4 [STEP 2] 꼼:G
yagom-academy/swift-starter-Round4 pull request #118
Opened 2023-03-16 08:08 UTC by karenyang835

@wonbi92 

안녕하세요. 원비~!
4주차의 2번째 미션 PR보내드립니다.
1번째 미션을 완료하고 나서 피드백 기다리는 동안 바로 미션 2를 해서 머지 되자 마자 보내드립니다.
1번째 미션에서 말씀해주셨던 '트레일링 클로저(후행 클로저 라고도 합니다.)' 이부분은 아직 적용해보지 않았습니다.

기존 진행해놨던 코드 먼저 보내드리고 피드백 주시는 동안 공부해서 적용시켜보도록 하겠습니다.(그래야 맞게 이해한건지 확인할 수 있을것 같아서요 ㅎㅎ)

## 고민했던 점
### 피로도가 100에 근접했을 때도 멈추게 하는 방법
아직 해결을 못했지만 조금더 생각해보고 고민해보고 있습니다.

### 누적 수치 적용
누적 수치를 적용함에 있어서 어려움이 있었습니다. 아무래도 코드 흐름을 이해를 잘 못해서 시간이 오래 소요 됬던것 같습니다. 자꾸 입력되어진 수치로 입력이 되어져서 한참을 헤멨던것 같습니다.

### 코드가 너무 길어져서 간결하게 하는 법
여전히 고민 중이긴 한데요. 되도록이면 간결하게 딱 한줄로 할 수 있는 방법이 없을까 계속 고민해보고 있습니다.

--- 

## 해결이 되지 않은 점
### 피로도가 100에 근접했을 때도 멈추게 하는 코드 작성
미션에서는 나오지 않았지만 100에 근접 했을 때 랜덤하게 올라가는 수치에 맞춰서도 멈추게 하는 코드를 작성하고 싶은데 아직 구현하는데 어려움이 있어서 구현은 못했습니다.
예를 들어서 현재 쌓인 피로도가 90일 경우 랜덤으로 10~20, 20~30의 피로도가 올라가는 운동들을 다 못하게 하는 방법도 구현하고 싶은데..생각처럼 쉽지가 않네요.

---

## 조언을 얻고 싶은 부분
### 기억력이 썩 좋지 않은 것 같습니다.
아무래도 코드가 길어지다 보니 기억력이 가물가물 한 것 같습니다.

분명 코드를 짤 때에는 먼가를 생각하고 짠 것 같아서 나중에 기억이 안날 것 같아 적어 두었는데.. 다시 읽어보니 무슨 생각으로 코드를 짠 건지...제가 짠 코드를 또 해석해야 되더라구요. 저만 그런건가요?...

혹시 이런 문제점이 발생되어지는 것이 아직 익숙하지가 않아서 일까요? 그리고 이해를 완벽하게 못해서 그런것 같기도 합니다. 아직 다른 사람에게 제가 이해한 부분에 대해서 한 줄로 설명하는게 어려운 걸 보니 모른다는게 맞는것 같습니다.

아직 연습이 더 필요한거겠죠?

2023-03-17 03:45 UTC, wonbi92 requested changes
@karenyang835 
안녕하세요 꼼지님!
스탭2 고생하셨습니다.
전반적으로 잘 작성해주셨는데요!
이제 소스파일을 스탭별로 나누지 마시고 각각의 객체별로 나눠주세요!
예를들어, `Activity` 구조체는 Activity.swift에 작성하는 식입니다.
그리고, 함수의 호출이나 전역변수의 선언 등은 메인에서 해주시면 됩니다.

> 미션에서는 나오지 않았지만 100에 근접 했을 때 랜덤하게 올라가는 수치에 맞춰서도 멈추게 하는 코드를 작성하고 싶은데 아직 구현하는데 어려움이 있어서 구현은 못했습니다.
예를 들어서 현재 쌓인 피로도가 90일 경우 랜덤으로 10~20, 20~30의 피로도가 올라가는 운동들을 다 못하게 하는 방법도 구현하고 싶은데..생각처럼 쉽지가 않네요.

- 좋은 생각인거 같네요! 이렇게하려면 피로도를 체크하는 시점을 더 신경쓰고 각 오류처리를 위한 프로퍼티나 오류 케이스등을 추가해야 할거 같군요.
- 이 부분은 로직을 구성하는 설계의 고민이기 때문에 삽질이 정답이긴 합니다. ㅎㅎ;
- 이렇게 구현되면 재밌을거 같아요!

> 기억력이 썩 좋지 않은 것 같습니다.

- 저도 이전에 제가 쓴 코드를 보면 완전 처음보는 느낌도 들고 합니다 ㅎㅎ 
- 코드에 익숙해지고 그 부분을 다른사람에게 잘 설명할 수 있을 때까지 여러번 반복해보는게 가장 빠른 방법일거 같아요.
- 이제 막 시작하시고 언어를 배우는 단계시니까 당연한 거라 생각합니다!
- 조바심 내실 필요 없어요! 잘 하고 계세요! 👍👍

잘 작성해주셨지만, 약간의 수정이 필요한 부분도 있습니다.
코맨트 확인해보시고 수정해주세요~

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/main.swift
> +let routine = Routine(routineName: "야곰 피트니스 지옥의 헬스 트레이닝 루틴", activities: activities)
지옥의 루틴 😱

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/step01.swift
> +
요 개행을 추가하신 이유가 있을까요? 👀

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/step01.swift
> +        }
프로퍼티 옵저버! 👍👍

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/step01.swift
> +        return "\(changeValueText)"
고냥 변수를 리턴해주셔도 됩니다 ㅎㅎ
```suggestion
        return changeValueText
```

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/step01.swift
> +            changeValueText = "변화 없습니다."
변화가 없는 것에 대해서도 신경을 써주셨군요! 👍

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/step01.swift
> +            changeValueText = "\(changeValue) 하락합니다."
값이 음수이면 하락하는군요! 좋은 분기처리입니다!
다만 현재 로직대로라면 피로도가 하락할 때 "피로도가 -8 하락합니다." 와 같이 나올거 같네요..?🤔

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/step01.swift
>  }
요 함수는 반드시 필요한 함수일까요?
요 함수를 정의하신 이유가 무엇일까요? 🤔

별개로 띄어쓰기 오타가 있네요 😅
```suggestion
func startTraining(_ activity: Activity, _ bodyCondition: BodyCondition) {
    activity.action(bodyCondition)
}
```

2023-03-17 03:45 UTC, wonbi92 commented on CodeStarterCamp_Week4/step02.swift
> +    let inputRound: String! = readLine()
옵셔널 암시적 추출을 통해 사용자의 입력을 받고 있군요!
다만, 현재 저희는 느낌표 없이 코드를 구현해야 합니다. 느낌표 말고 다른 방법을 통해 안전하게 옵셔널을 바인딩 해볼까요? 😁

2023-03-17 04:03 UTC, karenyang835 commented on CodeStarterCamp_Week4/step01.swift
> +
엇...이 부분을 놓쳤군요. 저는 PR보내고나서 원비의 피드백을 기다리는 동안 수정사항이 혹시 없는지 추가할 수 있는 부분이 없는지 등을 로컬디스크에서 따로 버전관리하면서 수정을 하기 때문에 요 부분을 체크를 못했었네요. (초반에 깃허브할 때 꼬였던 전적이 있어서 깃허브와 연동되는 폴더는 건드리지 않으려고 로컬상에서 따로 버전관리 하면서 작업하다가 이 부분을 놓친것 같습니당) 

이 부분은 다시 수정해두었습니다. 항상 이런 부분도 잊지 않고 꼼꼼하게 피드백 해주셔서 감사합니다.

2023-03-17 04:06 UTC, karenyang835 commented on CodeStarterCamp_Week4/step01.swift
> +        return "\(changeValueText)"
요 부분 말고도 어제 PR보내고 나서 코드 점검 하는데 밝혀진 오류도 있고 또 너무 쓸데없이 print문이랑  try도 남발한 부분이 있어서 함께 수정했습니다.

무슨 생각으로 그렇게 했는지.. 지금 보니.. 코드가 난리가 아니네요..ㅠ_ㅠ

2023-03-17 04:09 UTC, karenyang835 commented on CodeStarterCamp_Week4/step01.swift
> +            changeValueText = "\(changeValue) 하락합니다."
엇...그렇게 나오면 안 되는거군요..하락이 수치를 낮춘다는 의미이니 -8이 나오면 안 되겠군요..당연히 하락하는건 -로 표시 되야 된다고 인식했습니다. ㅎㅎ 수정하겠습니다.

2023-03-17 04:13 UTC, karenyang835 commented on CodeStarterCamp_Week4/step01.swift
>  }
그렇지 않아도 이 부분 관련해서 수정을 하고 있습니다. startRoutine 한 곳에서 너무 많은 것을 처리하려고 하다보니 굳이 만들지 않아도 될 함수까지 만들어버린것 같아서 다시 보고 있습니다. 수정해보겠습니다!!

2023-03-17 04:31 UTC, karenyang835 commented on CodeStarterCamp_Week4/step02.swift
> +    let inputRound: String! = readLine()
역시.. 이 부분도 문제가 되는군요..ㅠ_ㅠ
원비가 말씀해주셨던 방법으로 진행해보겠습니다!

2023-03-20 06:15 UTC, wonbi92 approved these changes
@karenyang835 
안녕하세요 꼼지님!
잘 수정해주셨습니다. 고생하셨어요!

100근접하면 루틴 시작을 제한하는 부분 생각보다 구현이 힘드셨나보군요 ㅎㅎ
그래도 열심히 고민하신 흔적이 보여서 좋았습니다! 
잘 마무리해주셨고, 약간의 코맨트가 있으니 확인해보시고 다음 미션 진행해주세요~ ㅎㅎ

2023-03-20 06:15 UTC, wonbi92 commented on CodeStarterCamp_Week4/bodyCondition.swift
> +    }
좋은 기능 분리라 생각합니다! 😁

2023-03-20 06:15 UTC, wonbi92 commented on CodeStarterCamp_Week4/bodyCondition.swift
> +            changeValueText = "\(changeInt) 하락합니다."
음수일 경우 -1을 곱해서 양수로 바꿔주는 로직이네요! 👍
하나 팁을 드리자면, 절대값을 활용하는것도 방법일거 같아요 😁

2023-03-20 06:15 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +        }
요것도 가드로 처리해줘도 괜찮을거 같아요! 😄

2023-03-20 06:15 UTC, merged

2023-03-20 06:22 UTC, karenyang835 commented on CodeStarterCamp_Week4/bodyCondition.swift
> +            changeValueText = "\(changeInt) 하락합니다."
오옷~ 절대값이요?? 그런게 있군요?? 다음번에는 한번 적용해봐야겠습니다!

2023-03-20 06:23 UTC, karenyang835 commented on CodeStarterCamp_Week4/routine.swift
> +        }
아하? 가드를 여러번 사용해도 괜찮은거군요? 오호 다음번에는 적용해보도록 하겠습니다. 감사합니다~