Week4 [STEP 2] Mary
yagom-academy/swift-starter-Round4 pull request #120
Opened 2023-03-16 19:03 UTC by MaryJo-github

@wonbi92 
안녕하세요 원비!
Week4 Step 2 PR 드립니다.
매도 먼저 맞는게 낫다고... 사실 이번에는 commit 단위를 나누는 것에 실패했습니다.
commit 하는 습관이 아직 안잡혀있어서 과제하다가 정신차려보니 이미 많은 action을 취했더라고요😭😭😭
다음부터는 더 신경쓰겠습니다🥲

### 고민했던 점
1. RoutineError는 다음 3가지 케이스로 나누었습니다.
   1. 피로도가 100이 넘었을 때
   2. 루틴 반복 횟수가 정수가 아닐 때 (=정수로 변환할 수 없을 때)
   3. 루틴 반복 횟수가 0 이하 10 초과일 때
  (요구사항에 맞도록 출력하기 위해 numberInKorean 배열을 만들었는데, 10까지만 만들어 놓았기에 입력이 10보다 크면 오류를 뱉도록 하였습니다) 
3. 오늘 피드백세션에서 은닉화 맛보기 강의를 들어서 메소드에 private 를 사용해보았습니다. 아직 제대로 공부하지는 않았지만 메소드에 private 를 쓰면 정의된 타입 내에서만 사용 가능한 것이라 이해했습니다.  
4. readLine()으로 입력값을 받으면 String? 으로 저장이되기때문에 강제추출을 이용하여 String 타입으로 만들어주었습니다. 
이후 String 타입을  Int로 감싸면 다시 Int? 가 되는데, 이는 guard let 구문을 이용하여 nil이면 오류를 던지도록 처리하였습니다.
6. 피로도가 음수값이 되는 것에 대한 예외처리는 error로 던져서 코드 흐름을 바꾸는 것 보다 0 으로 유지하게 하는 것이 더 맞는 것 같아서 휴식 인스턴스쪽을 수정하였습니다. (피로도가 0이더라도 더 쉴 수 있으니까요...😂)

### 조언을 얻고 싶은 점
1. Routine 타입 내 메소드를 구현할 때 기능 분리에 대해 신경을 많이 썼는데, 더 할 수 있을까요...? 또는 어색한 부분이 있으면 피드백 부탁드립니다!
2. 검색해보니 readLine() 에는 강제추출을 많이 쓰는 것 같더라고요. 이건 값이 무조건 들어올 것이라는 확신을 할 수 있어서인가요??? nil 값을 강제로 넣어줄 수 있는 방법은 없는 건가요...??😅
3. invalidInput 이나 outOfRangeInput 이 발생했을 때 다시 처음부터 반복하되, 최대 횟수를 지정하고 싶었습니다.
현재 do-catch 문 밖에 while 문으로 감싸서 구현하였는데 더 좋은 방식이 있을까요...??? 궁금합니다!

피드백 부탁드립니다! 감사합니다

2023-03-17 04:56 UTC, wonbi92 requested changes
@MaryJo-github 
안녕하세요 메리님!
스탭2 잘 작성해주셨어요!

입력횟수를 제한하는 로직을 추가하신 부분 너무 좋습니다. 👍👍

> Routine 타입 내 메소드를 구현할 때 기능 분리에 대해 신경을 많이 썼는데, 더 할 수 있을까요...? 또는 어색한 부분이 있으면 피드백 부탁드립니다!

- 음.. 기능 분리는 잘 이루어졌다고 생각해요! 각자의 메서드가 한가지 기능만 하고 있군요! 👍
- 한가지 더 힌트를 드리면, 각각의 객체가 어떤 행동을 해야 하는지 고민해보시면 좀 더 좋은 코드를 작성하실 수 있을거 같아요!
- 액티비티 라는 객체가 해야할 일과 가지고 있어야할 정보는 무엇인가? 와 같은 질문에 대한 고민을 한번 해보시기 바랍니다! 

> 검색해보니 readLine() 에는 강제추출을 많이 쓰는 것 같더라고요. 이건 값이 무조건 들어올 것이라는 확신을 할 수 있어서인가요??? nil 값을 강제로 넣어줄 수 있는 방법은 없는 건가요...??😅

- 코드 코맨트를 통해 말씀 드렸습니다 😁
- 강제추출을 예제에서 활용하는 이유는 말 그대로 예제이기 때문이에요.
- 예제는 예제일 뿐입니다. 로직이나 글이 말하고자 하는 바를 이해하는 용도로만 활용하시는것이 좋아요!

> invalidInput 이나 outOfRangeInput 이 발생했을 때 다시 처음부터 반복하되, 최대 횟수를 지정하고 싶었습니다.
현재 do-catch 문 밖에 while 문으로 감싸서 구현하였는데 더 좋은 방식이 있을까요...??? 궁금합니다!

- 음.. 저였다면 사용자의 입력을 관리하고 제대로 된 입력이 들어왔을 때만 루틴을 실행시켜주는 객체를 만들거 같긴 하네요!
- 그 안에 로직은 메리님이 작성한 것과 거의 유사하긴 하겠지만요! 😁

잘 작성해주셨지만, 약간의 수정이 필요해 보입니다.
코맨트 잘 읽어보시고 수정해주세요~

2023-03-17 04:56 UTC, wonbi92 commented on CodeStarterCamp_Week4/bodycondition.swift
> +            let result = upperBody > oldValue ? "\(upperBody-oldValue) 상승" : "\(oldValue-upperBody) 하락"
`result`는 제가 예제로 드린 네이밍이라.. 😅😅
이 문자열을 잘 설명해주는 네이밍을 고민해봅시다!

2023-03-17 04:56 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +    let numberInKorean: [String] = ["첫", "두", "세", "네", "다섯", "여섯", "일곱", "여덟", "아홉", "열"]
숫자를 한글로 출력하기 위해 한글 배열을 만드셨군요! 👍👍👍

2023-03-17 04:56 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +    func start(conditions: BodyCondition) throws {
무엇을 시작하는 함수일까요? 👀

2023-03-17 04:56 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +        let sets = try getNumberOfSets()
sets라는 네이밍이 조금 어색하네요. 일반적으로 스위프트에서는 타입의 이름을 변수명에 사용하는 걸 지양합니다. 몇몇 특수한 경우를 제외하구요!
어떤 의미로 set을 쓰셨는지는 이해가 됩니다.. 만 😅 다른 네이밍을 한번 고민해볼까요?
이 Routine타입에서 사용하셨던 모든 set에 다 해당되는 코맨트입니다!

2023-03-17 04:56 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +        guard let sets = Int(readLine()!) else {
readLine을 사용할 때 많은 예제에서 강제추출을 사용하죠 ㅎㅎ
하지만, **절대로** 좋은 방법은 아닙니다. 사용자의 입력이 nil이 아닐 수 있다고 장담할 수 있을까요?
만약 그렇다면, 그럼 왜 애플에서는 readLine() 메서드의 반환값을 옵셔널로 설정했을까요? 어차피 입력값은 무조건 존재하는데.. 🤔

추가적으로, 이번 캠프 과정에서 강제추출과 암시적 추출은 사용 금지입니다! 🙅‍♂️
안전하게 옵셔널을 바인딩해볼까요?

2023-03-17 04:56 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +        sets > 0 && sets <= 10 ? true : false
삼항 연산자를 활용하셨군요! 👍👍
한가지 팁을 더 드리자면, 조건의 결과 자체가 Bool타입이라서 요렇게도 쓸 수 있습니다.
가독성은 좀 떨어지지만, 코드는 더 간단해져서 상황에 따라선 활용할 수도 있어요. 😁
```suggestion
        sets > 0 && sets <= 10
```

2023-03-17 04:56 UTC, wonbi92 commented on CodeStarterCamp_Week4/routine.swift
> +        sets > 0 && sets <= 10 ? true : false
조금 더 보기좋게 조건문을 작성하시고 싶으시다면, 범위 연산자와 그 지정된 범위의 메서드를 활용하는 방법도 있습니다.
방법을 한번 찾아보시고 만약 해결이 안되신다면 디엠 주세요 ㅎㅎ

2023-03-20 04:02 UTC, MaryJo-github commented
@wonbi92 
안녕하세요 원비!
이번 피드백도 감사합니다🙇‍♀️

원비께서 각 객체가 해야할 일과 가지고 있어야할 정보에 대해 다시 생각해보라고 하셔서 고민을 해보았고,
결국 운동을 하는 Person 타입 객체를 따로 생성하였습니다.
기존에는 Routine 타입의 운동 시작 메소드를 통해 운동을 진행했었는데,
운동을 하는 주체는 사람이기 때문에 Person 객체에서 해주는 것이 맞다고 생각하였습니다.

피드백 부탁드립니다! 감사합니다😀

2023-03-20 06:23 UTC, wonbi92 approved these changes
@MaryJo-github 
안녕하세요 메리님!
잘 수정해주셨어요! 👍
특히 객체의 관계를 고민하시면서 Person 타입을 만드신 부분! 너무 좋았습니다. 👏👏👏
객체지향에 한발짝 다가가신 모습이 보이는군요! 굿굿! 👍👍👍

약간의 코맨트를 드렸으니 확인해보시고, 다음 미션 진행해주세요~
고생하셨습니다.

2023-03-20 06:23 UTC, wonbi92 commented on CodeStarterCamp_Week4/bodycondition.swift
> +    }
상승과 하락을 체크하는 메서드군요! 👍
프로퍼티 옵저버 안에서 읽기 조금 힘들 수 있으니 이 메서드 안에 얼만큼 상승하는지 나타내는 로직까지 한번에 넣는것도 방법일거 같아요!

2023-03-20 06:23 UTC, wonbi92 commented on CodeStarterCamp_Week4/person.swift
> +        1...10 ~= times
범위 연산자 활용! 👍

2023-03-20 06:23 UTC, wonbi92 commented on CodeStarterCamp_Week4/person.swift
> +            guard isExausted() == false else { throw Errors.exhaust }
요렇게도 표현할 수 있습니다.
사람에 따라서는 읽기 힘들다는 가독성의 이유로 메리님처럼 작성하기도 합니다! ㅎㅎ
한마디로 사바사!
```suggestion
            guard !isExausted() else { throw Errors.exhaust }
```

2023-03-20 06:23 UTC, wonbi92 commented on CodeStarterCamp_Week4/person.swift
> +        100... ~= bodyCondition.fatigue
요것도 괜찮아 보이는군요! ㅎㅎ
```suggestion
        bodyCondition.fatigue >= 100
```

2023-03-20 06:25 UTC, wonbi92 approved these changes

2023-03-20 06:25 UTC, wonbi92 commented on CodeStarterCamp_Week4/person.swift
> +    }
아참, 이렇게 매개변수가 없이 Bool타입을 선언하는 경우, 저는 연산 프로퍼티를 활용하는게 더 깔끔해 보이더라구요 ㅎㅎ
```suggestion
    private var isExausted: Bool {
        bodyCondition.fatigue >= 100
    }
```

2023-03-20 06:25 UTC, merged