Week4 [STEP2] gaemee
yagom-academy/swift-starter-Round4 pull request #122
Opened 2023-03-17 10:32 UTC by increw

@jsa0224 
솜, Step2 입니다. 지금까지 해왔던 것중 가장 오래 걸린 것 같습니다.
저번처럼 접힌 부분이 있어서, 확인해주시면 감사하겠습니다.

### 고민했던 점
- 애플 가이드라인에서 권장하는 구조체 조건에 준하여, Routine과 TrainingList를 구조체로 사용했습니다.
- 메소드 중 getRoutineCount에서 노란색 오류? 같은 것이 발생하여 검색 엔진을 활용하여 @discardableResult를 붙여줬습니다.
-  setRoutine 메소드에서 시간이 가장 오래 걸렸습니다. 어떠한 방식으로 코드를 짜야할지, 어떻게 짜야 오류없이 실행할지... 라고 생각하며 계속해서 도전했습니다.

### 해결하지 못한 점
- 시간이 오래 걸리는 만큼 여러 시도를 해볼 수 있었기에, 정상적으로 작동이 됩니다. 하지만 문제가 있을 수 있기에 코밋 달아주시면 감사하겠습니다.

### 조언을 받고 싶은 점
- 위에서 말씀드렸다 싶이 getRoutineCount 메소드에서 Result of call to (Some Function or Method) is unused 오류가 발생합니다. 알아보니 메소드나 함수를 호출하고 리턴값을 사용하지 않았기에 발생한다고 나와있더라구요. 이 부분에서 이해가 잘 가지 않아서 조언좀 얻고 합니다.

2023-03-17 12:10 UTC, jsa0224 requested changes
안녕하세요, 개미(@increw)님~🐜
4주차 프로젝트 Step 2도 구현 잘해주셨네요!

네이밍도 너무 많이 좋아지셔서 제가 다 뿌듯하네요😊
자세한 피드백 내용은 아래 코멘트로 남겨두었습니다!

2023-03-17 12:10 UTC, jsa0224 commented on CodeStarterCamp_Week4/main.swift
> +    var bodyCoindition = BodyCondition()
bodyCondition 오타가 존재하네요!

2023-03-17 12:10 UTC, jsa0224 commented on CodeStarterCamp_Week4/main.swift
> +    func startRountine() {
메서드명에 Routine 오타 존재합니다!

2023-03-17 12:10 UTC, jsa0224 commented on CodeStarterCamp_Week4/main.swift
> +    }
- 여기도 매개변수 네이밍인 루틴에 오타가 존재해요!
- 해당 부분이 운동을 진행하는 부분 같은데, 루틴이 운동을 하는 주체는 아닌 거 같아요!
요구사항에는 없지만, Person 타입을 만들어서 운동 주체인 사람의 기능으로 넣어주면 좋을 거 같네요~

2023-03-17 12:10 UTC, jsa0224 commented on CodeStarterCamp_Week4/main.swift
> +        print("<<윗몸일으키기을(를) 시작합니다>>")
해당 `print문`이 아래에서도 반복되는데, `setRoutine()` 메서드에 넣어서 반복을 줄일 수 있을 거 같아요!

2023-03-18 17:23 UTC, increw commented
@jsa0224 
솜, 오타 부분들을 확인하여 수정하였고, 말씀하신대로 Person 구조체를 생성하였습니다.

2023-03-19 05:07 UTC, jsa0224 commented on CodeStarterCamp_Week4/main.swift
> +    }
- Person 타입 구현 정말 잘해주셨습니다!
- 하지만 객체지향적으로 생각해본다면, 사람 스스로가 루틴을 세팅하고 그에 따른 컨디션을 체크하는 게 어색해보입니다!
FitnessCenter와 같은 해당 내용들을 관리해줄 객체가 필요해보여요! 

- `getRoutineCount()` 메서드의 리턴값이 필요할까요?
- 프로그래밍을 실행해보면서 빈 괄호가 계속 나오고 있어요!
![스크린샷 2023-03-19 오후 2 06 44](https://user-images.githubusercontent.com/94514250/226154896-b28fa170-9b22-45cf-a5c9-f8447c203419.png)

2023-03-19 16:40 UTC, increw commented on CodeStarterCamp_Week4/main.swift
> +    }
@jsa0224 
솜, 중첩구조체 FitnessCenter를 생성하였고, 기존 Person 타입명에서 Customer로 바꾸어주었습니다. Customer가 갖고 있던 내용들은  솜이 말씀하신 것처럼 FitnessCenter에서 관리하도록 만들어 주었습니다.

2023-03-20 09:33 UTC, increw commented
@jsa0224 
솜, 중첩구조체 FitnessCenter를 생성하였고, 기존 Person 타입명에서 Customer로 바꿨습니다. Customer가 갖고 있던 내용들은 솜이 말씀하신 것처럼 FitnessCenter에서 관리하도록 만들어 주었습니다.

2023-03-21 00:24 UTC, jsa0224 commented
수고하셨습니다, 개미님(@increw)!! 
복잡한 프로젝트였던 만큼 얻어가는 것도 많으셨음 좋겠네요!
다음 프로젝트 진행하시면 됩니다!

2023-03-21 00:24 UTC, merged