Week4 [STEP1] Whales
yagom-academy/swift-starter-Round4 pull request #124
Opened 2023-03-17 14:00 UTC by WhalesJin

드디어!!!!!제가!!!!!!!끄핫!!!!!!!!!!!!!!!!!!!!!!!!  ˃̵͈̑ᴗ˂̵͈̑
진짜 온세상 다 들리게 소리지릅니다!!!!!!!!!!
저 진짜 정말정말 너무 힘들었어요ㅠㅠ 아시죠 Som(@jsa0224) ??
근데 다 해가지고 진짜 너무 신나요!!!
정말 필수적인 것만 하고 단순하게만 해서
그 누구의 코드보다 단순하고 부족할 수 있지만
구현했다는 점에서 그 누구보다 뿌듯하고 행복합니다 !!! ๑❛ᴗ❛๑ 

---
#### 계획과 과정
- 일단 `BodyCodition`은 활동을 진행했을 때 프로퍼티 값이 변해야니까 `class`로!
`Activity`는 todo 대로 `struct`

![image](https://user-images.githubusercontent.com/124643545/225921152-46533d68-c2f4-4043-9398-79fe7a9d19ed.png)

갖다 써야는 줄 알고 `action` 안에도 `whalesBodyCondition`으로 넣었는데
뭔가 이게 아닌거같아 색이 다르자나 쟤를 가져오는게 아니야
( 그 후 장장 이틀에 거쳐 온갖 시도를 하며 완연한 삽질 중 )
( 위로해주신 많은 분들에게 애정 가득한 하트를 드립니다. )

- 복습도 하고 놓쳤던 세션도 다시 보며 공부공부!!
- 그래도 코드 잘 쓴 것 같은데 안되서ㅠㅠ 흠....하다가 다른 분들꺼를 훑어보자!!해서 들어간 깃헙!!
- 그중에서도 꼼지님껄 봤는데
아....... 그렇구나......
나 호출을 잘 못하고있었구나....
![](https://i.imgur.com/JRZKdKQ.png)
하ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
대박이다 진짜ㅠㅠㅠㅠㅠㅠㅠㅠㅠ
여기저기 자랑하고
텐션올려서 다시 시작!!!
- 여기까진 되었으니 프린트를 하자!!
![](https://i.imgur.com/LwzmHQK.png)
- 위 프린트는 각 운동 인스턴스 안에서 만들고
- 현재 컨디션은 BodyCondition에서 옵저버로 만들까? didSet?
- 오 근데 늘어난 정도를 얘기할거면 
```
let sitUp: Activity = Activity(name: "윗몸일으키기", action: { bodyCondition in
    bodyCondition.upperBodyMuscleStrength += Int.random(in: 20...30)
    bodyCondition.degreeOfFatigue += Int.random(in: 10...20)
    print("""
        <<\(sitUp.name)을(를) 시작합니다>>
        상체근력이 

    """)
})
```
이대로는 안되겠다 변수로 넣고 바꿔줘야겠다
![](https://i.imgur.com/SPXtC1B.png)

오케이 성공!!
- 아아 이름에 왜 name을 쓰면 안나오나 했더니 괄호가 action 괄호네
![](https://i.imgur.com/HCOWV4b.png)
오케이 성공!! 인제 아래만 채우자!!!

- 전부 다 피로도는 가지고 있으니까 피로도에 넣자!!
![](https://i.imgur.com/CM7w1Bi.png)
오 
    - 첫번째 문제. 순서가 뒤집혔다 -> 프린트랑 바뀌는거 순서바꾸면 해결될듯
    - 두번째 문제. 피로도는 엑티비티로 뜨네 왜지
![](https://i.imgur.com/eHsdCqC.png)
- 역시 첫번째는 순서만 변경하면 되는 문제였고
피로도는ㅋㅋㅋㅋㅋㅋㅋ
내가 dynamicResting을 넣었구낰ㅋㅋㅋ
제대로 안보고 ㅋㅋㅋㅋㅋㅋ
![](https://i.imgur.com/UB7cDW8.png)

성공성공!!!하 진짜 신난다 ㅎㅎㅎㅎㅎ

---

#### som 저 성공했어요!!!!!!!!! ✧*.◟(ˊᗨˋ)◞.*✧

2023-03-18 01:43 UTC, jsa0224 requested changes
안녕하세요, 웨일님(@WhalesJin)~🐳
성공성공! 축하드립니다!

전체적으로 깔끔한 프로젝트였지만, 코멘트 드릴 사항이 있어서 아래에 남겨두었습니다!

2023-03-18 01:43 UTC, jsa0224 commented on CodeStarterCamp_Week4/Activity.swift
> +    let effect2 = Int.random(in: 10...20)
bodyCondition의 근력을 바로 올려줄 수 있지 않을까요? 
```suggestion
    bodyCondition.upperBodyMuscleStrength += Int.random(in: 10...20)
    bodyCondition.degreeOfFatigue += Int.random(in: 10...20)
```

2023-03-18 01:43 UTC, jsa0224 commented on CodeStarterCamp_Week4/Activity.swift
> +    """)
해당 `print문`이 아래에서도 반복되고 있네요!
이 부분은 Step 2에서 어떻게 반복되는 `print문`을 줄일 수 있을지 고민해봅시다!

2023-03-18 01:43 UTC, jsa0224 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    }
피로도의 값이 변할 때마다 모든 컨디션을 알려주는 로직으로 보이네요.
각 컨디션이 바뀔 때마다 각각의 컨디션을 알려주는 게 더 좋아보여요!

2023-03-18 04:26 UTC, WhalesJin commented on CodeStarterCamp_Week4/Activity.swift
> +    let effect2 = Int.random(in: 10...20)
처음에는 바로 올렸다가 프린트 할 때 얼만큼 올랐는지 차이를 보여줘야 하더라고요
그래서 분리시켰어요!!
그러면 바로 올리고 프린트를 할때 차이를 보여주는 걸로 수정할까요?
아 근데 그렇게 되면 `didSet`이랑 `print문`의 순서도 바뀔거라 그 부분 수정도 고려해봐야 할 것 같아요!!

2023-03-18 04:26 UTC, WhalesJin commented on CodeStarterCamp_Week4/Activity.swift
> +    """)
오!! 넵!!!! 고민해보겠습니다!!!

2023-03-18 09:59 UTC, WhalesJin commented on CodeStarterCamp_Week4/BodyCondition.swift
> +                print("피로도가 \(oldValue - degreeOfFatigue) 하락합니다.")
피로도가 `- 상승`으로 뜨는게 싫어서 조건문으로 넣어봤어요!!!

2023-03-19 02:09 UTC, jsa0224 commented
수고하셨습니다, 웨일님(@WhalesJin)!
다음 스탭 진행하시면 돼요~!

2023-03-19 02:09 UTC, merged