Week4 [STEP2] Whales
yagom-academy/swift-starter-Round4 pull request #130
Opened 2023-03-20 10:37 UTC by WhalesJin

항상 우선적으로 애써주시고 많이 챙겨주시는
나의 애정하는 멘토님 Som(@jsa0224 )
(자중해봅니다 저의 애정)

저 이번에는 좀 사람같이 했어요!!!
이성적으로!! 뭔가 작업도 좀 되고!!!!
너무 일희일비 같지만!!!
그래도 저 열심히 하고있어요!!!!!!!!
걱정마세요 ෆ

---

#### 계획
1. Routine 타입
   - 일단 어떤걸로 할까 struct/class 좀 고민해보자
   - var name: String
   - activities: [Activity]

2. readLine
   - '프로그램이 시작되면' 그러면 얘도 감시자로 넣을 수 있나?
   - readLine은 숫자도 문자열로 인식 -> 그러면 Int? 로 못 쓰고 String?으로 만들어야겠네
근데 입력은 양의 정수로 받으라며? 그럼 여기서 받은 문자를 숫자로 바꾸고 0 이하면 던져?
   - 해보자. Int로도 해보고 String으로도 해보고
   - 받은 만큼 배열 속 클로저 반복. 이건 for문이나 while문으로. 조건 넣기엔 while이 좀 더 좋을 것 같기도.

일단 여기까지 한번 해보자

---

#### 과정
![](https://i.imgur.com/A3cXxpu.png)
일단 여기까지는 했는데
흠... 오류를 던져야니까
오류문구 만들어야겠다
```
struct Routine {
    var name: String
    var activities: [Activity] = [sitUp, squat, marathon, dynamicResting]
    
    func startProgram() throws -> Int {
        print("루틴을 몇 번 반복할까요? :", terminator: " ")
        let count: Int? = Int(readLine() ?? "nil")
        let count2: Int = count ?? 0
        guard count2 > 0 else {
            throw ProgramError.notNumber
        }
        return count2
    }
    
    func doRoutine(count: Int) {
        var round: Int = 1
        while round <= count {
            print("\(round) 번째 \(self.name)을(를) 시작합니다.")
            activities[0].action(bodyCondition)
            activities[3].action(bodyCondition)
        }
    }
}

let newRoutine: Routine = Routine(name: "hellRoutine")
do {
    try newRoutine.doRoutine(count: newRoutine.startProgram())
} catch ProgramError.notNumber {
    print("잘못된 입력 형식입니다. 다시 입력해주세요.")
} catch ProgramError.overActivity {
    print("피로도가 100 이상입니다. 루틴을 중단합니다.")
}
```
이렇게 하고 실행은 됐는데
무한루프 돌아서 깜짝 -> `round += 1`로 무한루프 해결!!

근데 예시를 보면 이번엔 오르는 값이 일정하네 고정시켜야겠다.
`bodyCondition.upperBodyMuscleStrength += 13`

---

첫번째, 두번째로 출력 시키고 싶어서 수정.
배열로 넣고 대신 `-1`로
```
let ordinalNumber: [String] = ["첫", "두", "세", "네", "다섯"]
print("\(ordinalNumber[round-1]) 번째 \(self.name)을(를) 시작합니다.")
```

피로도 오류던지는 코드를 함수 안에 넣고

```
func doRoutine(count: Int, bodyCondition: BodyCondition) throws {
        var round: Int = 1
        while round <= count {
            print("\(ordinalNumber[round-1]) 번째 \(self.name)을(를) 시작합니다.")
            activities[0].action(bodyCondition)
            activities[3].action(bodyCondition)
            activities[1].action(bodyCondition)
            guard bodyCondition.degreeOfFatigue < 100 else {
                throw ProgramError.overActivity
                return
            }
            round += 1
        }
        bodyCondition.checkBodyCondition()
    }
```
`catch`도 합치고 `bodyCondition` 프린트까지
![](https://i.imgur.com/rd8GjCS.png)

---

이렇게 성공은 했으나 아쉬운 부분이 많아요ㅠㅠ
1. `nil`병합 연산자는 성능부분에서 좋지 않다고 들어서 `guard let`으로 바꾸고싶고요
2. `do-try-catch` 이걸 `Rountine` 안에 메소드로 넣고 싶어요

아직 이 두가지를 고민 중인데요 혹시 다른 부분 수정이 필요하거나 더 좋은 코드가 있으면 배우고싶어서 미리 올립니다!!!
코멘트 주시기 전까지 더 수정해보겠습니다!!

2023-03-20 22:04 UTC, WhalesJin commented
두 가지 다 성공해서!! 다시 커밋했습니당!!!
(@jsa0224 )

2023-03-21 08:13 UTC, jsa0224 requested changes
안녕하세요, 웨일님(@WhalesJin)~🐳
Step 2도 잘 구현해주셨네요!

웨일님 덕분에 nil 병합 연산자가 성능이 안 좋다는 것도 새로 알게 되었네요!
기능적인 부분은 정말 잘 구현해주셔서, 코멘트 남길 게 별로 없더라구요👍

주로 컨벤션이나 객체지향적 사고 위주로 코멘트 남겼습니다!

2023-03-21 08:13 UTC, jsa0224 commented on CodeStarterCamp_Week4/Activity.swift
> +    bodyCondition.degreeOfFatigue -= 7
요 부분 랜덤값 대신 직접 값을 넣어준 이유를 한참에서야 깨달았네요...
캠프 사이트 예제를 보고 하신 거군요!
하지만 캠프 사이트 예제 또한 랜덤값이 출력된 것이니, 원래대로 바꿔주시면 좋을 거 같아요!

2023-03-21 08:13 UTC, jsa0224 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var upperBodyMuscleStrength: Int{
```suggestion
    var upperBodyMuscleStrength: Int {
```
아래도 프로퍼티 감시자 컨벤션이 통일되지 않네요!

2023-03-21 08:13 UTC, jsa0224 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    func checkBodyCondition () {
```suggestion
    func checkBodyCondition() {
```
요기도 컨벤션!!

2023-03-21 08:13 UTC, jsa0224 commented on CodeStarterCamp_Week4/main.swift
> +}
에러 타입 구현해주셨네요👍
정확히 어떤 프로그램인지 명시되어 있으면 좋을 거 같아요!

2023-03-21 08:13 UTC, jsa0224 commented on CodeStarterCamp_Week4/main.swift
> +    }
이 부분이 Routine의 기능인지 잘 모르겠어요.
저는 운동하는 주체는 사람이라고 생각이 들어서, `Person` 객체를 구현해보시는 것도 좋을 거 같아요~

2023-03-21 08:16 UTC, WhalesJin commented on CodeStarterCamp_Week4/Activity.swift
> +    bodyCondition.degreeOfFatigue -= 7
랜덤으로 넣으면 반복할때마다 수치가 달라질 것 같아서 직접 넣었어요
그러면 랜덤으로 나와서 정해진 값으로 반복문이 돌아가도록 수정해봐야겠네요!!!!

감사함미당 ๑❛ᴗ❛๑

2023-03-21 08:17 UTC, WhalesJin commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var upperBodyMuscleStrength: Int{
아...제가 저번꺼 수정 안 한 걸로 작업을 했더니 또ㅠㅠㅠ 웬수가 또... ( •᷄⌓•᷅ )  ㅠㅠㅠㅠㅠㅠㅠ
이것도 아래꺼도 다 수정해놓겠습니다ㅠㅠㅠ

2023-03-21 08:18 UTC, WhalesJin commented on CodeStarterCamp_Week4/main.swift
> +}
넵!! 네이밍을 바꿔보겠습니다!!

2023-03-21 08:18 UTC, WhalesJin commented on CodeStarterCamp_Week4/main.swift
> +    }
그렇게 들으니 또 그렇네요!!!!
알려주신대로 한 번 해보겠습니다!!!!!! (ง •̀_•́)ง !!

2023-03-21 10:07 UTC, WhalesJin commented
다른 부분들은 수정했는데 랜덤받고 고정시키는 부분을 아직 못했어요ㅠㅠ
더 고민해보겠습니다!!!!!

2023-03-22 14:23 UTC, jsa0224 commented
수고하셨습니다, 웨일님(@WhalesJin)!
다음 프로젝트 진행하시면 됩니다~!

2023-03-22 14:24 UTC, merged