Week4 [STEP 1] knumber2
yagom-academy/swift-starter-Round4 pull request #150
Opened 2023-08-09 16:02 UTC by cognd98

@Rhode-park 

### 고민했던 점

- 각 프로퍼티의 상승 수치를 나타내기 위해 didset 구문을 사용하였습니다.
- 피로도 부분은 하락하는 경우도 고려해야하기 때문에 if를 사용하여 구현하였습니다.

2023-08-10 16:55 UTC, Rhode-park requested changes
PR 잘 받았습니다!
너무 잘 작성해주셔서 언급할 점이 많이 없었던 것 같습니다.
Foundation과 class struct에 대해서만 조금 더 생각해볼까요?

2023-08-10 16:55 UTC, Rhode-park commented on CodeStarterCamp_Week4/main.swift
>  import Foundation
이 친구는 필요한 친구인가요?
`import Foundation`은 어떤 존재인가요?

2023-08-10 16:55 UTC, Rhode-park commented on CodeStarterCamp_Week4/main.swift
> +class BodyCondition {
`BodyCondition`을 class로 만들어주셨군요! 멋집니다! class와 struct의 두드러지는 차이는 무엇일까요? 그리고 여기에서 class를 써주신 이유는 무엇일까요?

2023-08-10 16:55 UTC, Rhode-park commented on CodeStarterCamp_Week4/main.swift
> +        didSet {
didSet을 써주셨군요! LGTM!

2023-08-10 16:55 UTC, Rhode-park commented on CodeStarterCamp_Week4/main.swift
> +    let action: (BodyCondition) -> Void
클로저를 만들어주셨군요! 멋집니다!

2023-08-11 00:04 UTC, cognd98 commented on CodeStarterCamp_Week4/main.swift
>  import Foundation
Foundation에서 구현된 코드들을 사용할 수 있게 하는 역할입니다.

2023-08-11 00:06 UTC, cognd98 commented on CodeStarterCamp_Week4/main.swift
> +class BodyCondition {
class는 상속이 가능하다는 점입니다. 이후 상속 가능성을 고려하여 struct보다는 class를 사용하였습니다.

2023-08-12 01:49 UTC, merged