Week4 [STEP 2] QL
yagom-academy/swift-starter-Round4 pull request #152
Opened 2023-09-11 14:45 UTC by slowkuma

@Tediousday93
Round 4 의 Step 2 진행 결과 입니다.

## 고민했던 점
### People 과 Routine 의 관계
- People 에게 Routine 을 넘길 것인가? Routine 에게 People 을 넘길 것인가? 를 고민 하다가
  People 은 Model 성격 임으로 주 역할은 Routine 이 되어야 할꺼라고 생각하고 만들었습니다.
### 반복 할때 기수를 한글로 출력 하는 부분
- 출력하는 방법에 대해서 최대 10개까지 만 하여 간단하게 예외 처리 넣고 해볼까 라고 생각 하였지만,
  시간이 좀 있어서 한글 숫자의 서수 와 기수 문자열 생성로직을 만들었습니다.

---

## 해결이 되지 않은 점
- 없습니다.

---

## 조언을 얻고 싶은 부분
- 없습니다.

2023-09-12 11:03 UTC, Tediousday93 requested changes
안녕하세요 QL님 Stpe2 고생하셨습니다 ☺️
벌써 마지막 PR이군요!

이번에도 잘 수행해 주셨습니다 👏👏👏
기수 / 서수를 만드는 로직이 인상적이네요 👍 

### 수행 내용
* [x] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기
---
- [x] Routine 타입 생성하기
- [x] 원하는 방식으로 에러 처리하기
- [x] 실행예시와 일치하도록 결과 출력하기


### 피드백
* 네이밍
이전 스텝에서 놓쳤던 부분인데요, People은 복수형이므로 타입의 이름을 Person으로 하는 것이 좋을 것 같습니다. People이라고 파라미터에 들어가있는 것을 보니 `[Person]` 타입이 전달될 것 같은 느낌이 듭니다. 💭
* 오류 처리
빠지는 것 없이 잘 오류를 잡아주셨습니다 👍

이전부터 Result 타입을 사용하셨기 때문에 do-catch만 사용해달라고 말씀드리기가 어렵군요 ㅎㅎ

2023-09-12 11:03 UTC, Tediousday93 commented on CodeStarterCamp_Week4/BodyCondition.swift
>      }
삼항연산자의 활용 👍

2023-09-12 11:03 UTC, Tediousday93 commented on CodeStarterCamp_Week4/People.swift
> +        }
피로도가 100이 넘으면 오류를 던져주도록 해주셨군요 👍

2023-09-12 11:03 UTC, Tediousday93 commented on CodeStarterCamp_Week4/Routine.swift
> +    }
sessionRepeat 메서드에서 오류처리를 하지 않고 여기에서 Result타입으로 변환하시는 이유가 있을까요?
Result 타입의 `init(catching:)`이니셜라이저를 활용하면 조금 간단해집니다.
```suggestion
    private func workout(_ activity: Activity, with people: People) -> Result<String, Error> {
        return Result { try people.workout(activity) }
    }
```
이 정도는 따로 메서드로 분리하지 않아도 오류처리 구문으로 `sessionRepeat` 내부에서 작성해도 괜찮을 것 같습니다.

또한, 지금은 한 종류의 에러밖에 던져지지 않기 때문에 강제 다운캐스팅을 사용해도 무방하지만
다른 종류의 에러가 던져질 경우에는 위험하기 때문에 사용을 지양하는 편이 좋다고 생각합니다.

errorMessage를 출력하는 부분은 `LocalizedError` 프로토콜을 활용해주셔도 좋을 것 같습니다.

2023-09-12 11:03 UTC, Tediousday93 commented on CodeStarterCamp_Week4/Routine.swift
> +            fallthrough
fallthrough를 사용하신 이유가 있을까요??
fallthrough로 인해 `cannotRead` 에러를 받은 경우 `notInt` case의 return 문을 타게 됩니다.
cannotRead의 경우 별다른 처리 없이 넘어간다면 굳이 에러를 만들지 않아도 괜찮아보입니다.
다른 케이스들과 마찬가지로 특정 문자열을 반환해주는게 좋다고 생각되네요 🤔

던져줄 오류가 없게 되면 readRepeatCount에서 readLine 바인딩 guard else 문에서 어떻게 처리를 할 지 고민되실 수도 있겠네요.
이렇게 반복적으로 값이 nil이 아닐 때까지 입력을 받는 경우, while let을 활용하기도 합니다.
또는 반환값을 옵셔널타입으로 만들어줘도 괜찮겠네요.
참고만 해주세요!

2023-09-12 11:03 UTC, Tediousday93 commented on CodeStarterCamp_Week4/RoutineInputError.swift
> +}
`LocalizedError` 프로토콜을 채택하면 나중에 catch 할 때 타입캐스팅을 따로 하지 않더라도
`localizedDescription` 프로퍼티에 접근해 원하는 문자열을 출력할 수 있습니다.

2023-09-12 11:03 UTC, Tediousday93 commented on CodeStarterCamp_Week4/Routine.swift
> +        } while count < 1
`count`를 Routine 타입의 프로퍼티로 정의하고 반복횟수를 설정하는 메서드를 분리해도 좋을 것 같습니다. 💭

2023-09-12 11:03 UTC, Tediousday93 commented on CodeStarterCamp_Week4/main.swift
> +routineSleep.start(with: misterKim)
Sleep activity도 결국 People의 fatigue 기준으로 예외처리를 하기 때문에 첫 번째 루틴에서 피로도가 100이 넘어가면 실행되지 않네요.
이 부분은 요구사항에 없기 때문에 수정하지 않으셔도 괜찮습니다. 😊

2023-09-12 11:41 UTC, slowkuma commented on CodeStarterCamp_Week4/Routine.swift
> +    }
Error 에 LocalizedError 적용 하는부분은 지난 작업에서 사용 한 적이 있음으로 사용 법은 알고 있습니다.

과제의 print 는 `피로도가 100 이상입니다. 루틴을 중단합니다.`  문구 이며
정의된 PersonWorkoutError 는 Person.workout() 에서 발생 되는 에러 입니다.
또한 에러의 내용은 `피로도가 100 이상일때 진행 하려는 경우` 가 됩니다.

여기서 문제는 LocalizedError 를 적용하면 `피로도가 100 이상이어서 진행 할 수 없다.` 가 됩니다.
하지만 `루틴을 중단합니다.` 라는 메세지를 넣어야 함으로 message 를 Routine 에서 일부러 생성 하였습니다.

`피로도가 100 이상입니다.` 와 `루틴을 중단합니다.` 를 각각 합성을 해도 될꺼 같지만
그렇게 해도 별도로 처리가 필요한건 똑같습니다.
그래서 이렇게 구현 하였습니다.

LocalizedError 적용을 해서 변경 해야 한다면 한번더 말씀 부탁 드립니다.

2023-09-12 12:06 UTC, slowkuma commented on CodeStarterCamp_Week4/Routine.swift
> +            fallthrough
readLine() 이 nil 을 반환 하는 경우는 정말 거의 없을 것 입니다.
일반적인 키보드 환경에선 전혀 없다고 봐도 무방 하죠.
하지만 기술적으로는 발생이 할 수 있으며 그렇기 때문에 cannotRead 를 정의 하였습니다.

그리고 과제애서 `입력을 잘못한 경우` 에 해당 함으로
`잘못된 입력 형식입니다. 다시 입력해주세요.` 를 출력 하도록 하였습니다.

하지만 이는 notInt 와 같은 메세지 임으로 fallthrough 를 통해
notInt 와 같은 로직으로 동작 하도록 만든 것 입니다.

---

이번 과제의 목표는 `do-catch` 와 `Result` 의 활용 같아서 일부러 이렇게 좀 꼬아 놓았습니다.
그리고 말씀대로 while let 을 사용 할 경우 let 에서 받은 값은 while 밖에선 사용 할 수 없고
(물론 별도로 밖에서 선언하면 해결 되지만)
또한 오류 입력에 대한 예외 print() 처리가 힘들어 질것 같습니다.

이전에도 말씀 드린거 처럼 저는 출력이 필요한 부분은 가능한 한곳으로 모으고
최소한 적게 사용하려는 경향이 있어서 print() 코드가 적용 되는 부분은 Routine.start() 에서 한정 하고 있었던 것 입니다.
(쓸대 없는 고집 일 수도 있습니다)

Routine.readRepeatCount() 에서 Result 를 사용 하지 않고 Int? 를 반환하게 함으로서 
Routine.start() 내부에 while let 적용은 가능 합니다.
역시 이 경우 메세지 print() 을 Routine.readRepeatCount() 에서 직접 하면 해결 됩니다.

while let 적용을 해서 변경 해야 한다면 한번더 말씀 부탁 드립니다.

2023-09-12 12:12 UTC, Tediousday93 commented on CodeStarterCamp_Week4/Routine.swift
> +    }
LocalizedError를 반드시 활용해달라는 말씀은 아닙니다.
메세지를 만드는 부분은 errorMessage 부분이고 위 코멘트에서 중요하게 봐주시면 좋겠는 부분은
"에러처리 구문 위치"와 "강제 타입캐스팅" 입니다.

따로 workout 메서드를 routine에 정의하지 않더라도 try people.workout을 호출 가능하고
Result 타입이나 do-catch문을 활용하여 catch한 에러에 맞는 오류처리를 해주시면 좋겠다는 생각입니다.

Result타입의 경우 failure case가 any Error이기 때문에 타입캐스팅이 필요하지만 do-catch를 활용하면 에러를 특정하여 코드블록을 작성할 수 있습니다.

```swift
                do {
                    let workResult = try people.workout(activity)
                    result += workResult
                } catch PeopleWorkoutError.tiredness {
                    result += "피로도가 100 이상입니다. 루틴을 중단합니다."
                } catch {
                    print(error)
                }
```

2023-09-12 12:19 UTC, Tediousday93 commented on CodeStarterCamp_Week4/Routine.swift
> +            fallthrough
> 다른 케이스들과 마찬가지로 특정 문자열을 반환해주는게 좋다고 생각되네요 🤔

case를 만들어주셨다는건 notInt와 cannotRead가 다른 경우라고 생각하셨던 것이 아니신가요??
발생할 일이 잘 없긴 하지만 입력을 잘못한 경우가 아니라 입력을 받지 못한 경우라고 생각이됩니다.
"사용자의 입력을 받지 못했습니다." 정도의 return값을 주는 것은 어떠신가요?

while let은 굳이 사용하실 필요 없습니다. 👀

2023-09-12 12:19 UTC, slowkuma commented on CodeStarterCamp_Week4/RoutineInputError.swift
> +}
위에서 설명한 것 과 같이 과제의 출력 메세지에 맞추기 위하여 만들어 놓은 것 입니다.

LocalizedError 적용을 해서 변경 해야 한다면 한번더 말씀 부탁 드립니다.

2023-09-12 12:35 UTC, slowkuma commented on CodeStarterCamp_Week4/Routine.swift
> +        } while count < 1
위에서 설명한 것 과 같이 print() 에대한 개인적인 집착 때문 입니다.

변경 해야 한다면 한번더 말씀 부탁 드립니다.

2023-09-12 13:01 UTC, slowkuma commented
@Tediousday93
이번에는 저의 고집으로 인하여 코드가 좀 꼬여있어 보기가 힘드셨을것 같습니다.
그리고 다시금 과제를 읽어봤는데 요구사항이 `do-catch` 로 한정 되어 있었다는걸 보았습니다.
그래서 Result 사용부분을 전부 제거 하였습니다.
미적용 부분확인 해 보시고 작업이 필요한것을 말씀 해 주시면 적용 하겠습니다.

### 적용
* People class 를 Person 으로 이름 변경
* Result 사용 부분 제거
* Routine.workout() 제거

### 미적용
* LocalizedError 를 사용 하도록 변경
* Routine.readRepeatCount() 에서 반복 입력 처리까지 전부 해결 하도록 함
* RoutineInputError.cannotRead 의 경우 오류 메세지를 출력 하도록 함
* count 를 property 로 옮김
* while let 방식 적용

2023-09-12 13:16 UTC, slowkuma commented on CodeStarterCamp_Week4/Routine.swift
> +            fallthrough
키보드 입력상태에서 readLine() 이 nil 을 반환 하는 경우는
입력한 값이 무진장하게 길어서 메모리의 허용값을 넘겼고 이에 따라
String 으로 변환 하지 못하는 경우가 발생 합니다.

저는 잘못된 입력으로 인식 하고 있긴 했는데 ㅎㅎ
말씀 대로 적용 하겠습니다.

2023-09-12 13:20 UTC, slowkuma commented
@Tediousday93

* RoutineInputError.cannotRead 의 경우 오류 메세지를 출력 하도록 함

부분을 적용 하였습니다.

2023-09-12 13:34 UTC, slowkuma commented
@Tediousday93
Routine.errorMessage() 를 제거 하였습니다.

2023-09-12 13:35 UTC, slowkuma commented on CodeStarterCamp_Week4/Routine.swift
> +    }
Routine.errorMessage() 를 제거 하였습니다.

2023-09-13 13:29 UTC, Tediousday93 commented
QL님의 코드가 보기 어렵지는 않았습니다!
print 함수의 호출을 최소화한다는 점은 저도 좋다고 생각합니다 👍
다만 해당 부분을 지키려고 하시다보니 오류 처리 쪽에서 취향이 갈린 것 같네요.  ㅎㅎ

물론 지금도 충분히 잘 구현해주셨습니다 👀
요구사항 지켜주셔서 감사합니다 🙏

머지하도록 하겠습니다.
함께한 5주가 유익한 시간이 되셨다면 좋겠네요. ☺️
고생 많으셨습니다 👏

2023-09-13 13:31 UTC, merged

2023-09-13 23:48 UTC, slowkuma commented
5주동안 고생 많으셨습니다.
리뷰를 친절히 끝까지 잘 해주셔서 저의 코드를 되돌아 보는 경험이 많이 되었습니다.
감사합니다.