Week4 [STEP1] Kay Ahn
yagom-academy/swift-starter-Round4 pull request #19
Opened 2022-03-06 08:41 UTC by cpp2swift

@1Consumption 
올라프님 안녕하세요!
이번주 내내 클로저를 조금 더 공부한다고 많이 늦었습니다..

이번에 제가 코드를 작성하면서 가장 중요하게 여겼던 부분은 "클로저 함수를 제대로 사용하자" 이였고,
그 다음으로 중요하게 여겼던 부분들은 코드의 가독성과 바른 네이밍 그리고 커밋 메세지 작성을 최대한 자세하게 작성하는것 이었습니다.

모든 파일을 커밋하고 나서 다시 돌아보니 차라리 클래스 또는 구조체를 각각 하나씩 파일에 담아서 커밋했으면 어땠을까 하는 생각도 들었습니다.
항상 좋은 코멘트 주셔서 감사합니다!

2022-03-07 14:40 UTC, 1Consumption requested changes
@cpp2swift
케이안님~ 고생하셨습니다!
확실히 커밋이 하나의 역할만 하고있어요. 노력하신게 느껴집니다.
클로저라는 개념이 생소하고 어려웠을텐데 잘 사용하셨습니다!

클로저를 쓰면서 느꼈던 장점이 있었나요? 있었다면 코멘트로 남겨주세요.

몇가지 코멘트를 남겼는데 확인 부탁드릴게요!

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +class Bodycondition {
class로 선언한 이유가 있을까요?

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +    init(upperBS: Int = 0, lowerBS: Int = 0, muscular: Int = 0, fatigue: Int = 0) {
BS는 약어네요! 약어는 최대한 지양해주세요. 읽는 사람에 따라 다르게 해석할 수 있습니다.

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +    }
출력하는 메소드네요! check보다는 print가 들어가는게 어떨까요?

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +var myBody = Bodycondition(upperBS: 50, lowerBS: 50, muscular: 50, fatigue: 0)
클래스인데 var네요. 어떤 값이 바뀌는걸까요?

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +    myBody.fatigue += randomNum(10,20)
, 사이에 공백을 넣어주세요. 조금 답답해보이네요.

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +})
한글로 변수명을 작성해주셨네요! 가독성은 좋아졌는데, 사용할 때 한영전환을 해야해서 조금 불편할거같아요.
하지만 재미있는 시도네요ㅋㅋ

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +    let exercises: Array<Exercise>
외부에서 알아야하는 프로퍼티인가요?

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +    }
동사로 시작하는게 어떨까요?

2022-03-07 14:40 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +var hellRoutine = Routine(routineName: "missKim's Hell Routine", exercises: [윗몸일으키기, 윗몸일으키기, 동적휴식, 스쿼트, 스쿼트, 동적휴식, 오래달리기, 오래달리기])
var인 이유가 없어보입니다. struct의 값 자체가 바뀌는게 아닌거같아요.

2022-03-08 06:37 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +class Bodycondition {
class로 선언한 이유는 저번주 미션에서 구조체로만 코드를 작성해서 한번 클래스로 구현해 보고 싶었습니다!

2022-03-08 06:39 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +    init(upperBS: Int = 0, lowerBS: Int = 0, muscular: Int = 0, fatigue: Int = 0) {
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/9e4add68434a6c1cc519955ff0e4ecf761ba35d7

약어를 풀네임으로 수정했습니다. "몇개 없는 프로퍼티니까 다른 사람들도 당연히 ~~로 생각하겠지" 라는 생각을 버리겠습니다.

2022-03-08 06:43 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +    }
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/1df539fafc005cfa6ab5ffc0b25826fb4a57cec9

결국엔 출력하는 메서드이니, 현재 컨티션을 체크한다보다 현재 컨디션을 출력하는 메서드명이 더 어울리는것 같습니다!

2022-03-08 06:54 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +var myBody = Bodycondition(upperBS: 50, lowerBS: 50, muscular: 50, fatigue: 0)
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/339c1e78d76babd70b38dc76e14baf1ff76432ae

바뀌는 값은 없습니다! let으로 변경한 이유는 재할당 하는 일도 없고, 속성값은 멤버 접근으로 변경 할 수있고, 실수를 방지, 실행속도가 빨라진다는 이유로 변경했습니다.

2022-03-08 06:57 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +    myBody.fatigue += randomNum(10,20)
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/bb04c49472c4871c41737e5dc33626954f2df3b0

공백을 추가해 가독성을 높였습니다!

2022-03-08 07:00 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +})
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/94c8c88a424bd9e5361d98bc7f980459c1af0519

영어가 아닌 한글로 된 코드가 실행된다는게 신기해서 한번 써봤는데 차후에는 영어로 쓰겠습니다!

2022-03-08 07:05 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +    let exercises: Array<Exercise>
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/5477c306dd61e688abee056397d69c9d62e416df

다시 보니 외부에서 루틴의 이름이나 어떤 운동들이 있는지 꼭 알지 않아도 될 것 같습니다!

2022-03-08 07:08 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +    }
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/2e787826b5f4b6796d72b7a8296488a676622a8a

객체가 "routine start" 보다 "start routine" 이 더 잘어울리는것 같습니다!

2022-03-08 07:13 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +var hellRoutine = Routine(routineName: "missKim's Hell Routine", exercises: [윗몸일으키기, 윗몸일으키기, 동적휴식, 스쿼트, 스쿼트, 동적휴식, 오래달리기, 오래달리기])
https://github.com/yagom-academy/swift-starter-week4/pull/19/commits/c95c0b04626ae6c4a9d71e6fc92d74496682cff8

3주차 미션에서도 이런 실수를 하고 더 신경을 쓴다고 했는데.. 다시 보니 값을 바꿀일이 없는 객체인데 let이 더 잘 어울린다고 생각합니다!

2022-03-08 07:20 UTC, cpp2swift commented
@1Consumption 
올라프님 코멘트 감사합니다.
저번주부터 구조체와 클래스에 대해서 점점 더 많이 알게되었고, 자주 실수는 하지만 언제 var를 써야하는지 let을 써야하는지 조금씩 머릿속에 자리 잡고있는게 느껴집니다. 제가 지은 메서드명도 한번 생각해보면 다른사람들도 이해는 하겠지만 코멘트 써주신대로 짓게된다면 바로 이해가 가능한것 같습니다! 
이번에도 좋은 코멘트들로 다시 생각해 보게끔 성장시켜주셔서 감사합니다!

2022-03-08 14:33 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +class Bodycondition {
이건 class를 채택한 이유가 되지 못할거같아요. 
class와 struct의 차이는 뭔가요?

2022-03-08 14:34 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +var myBody = Bodycondition(upperBS: 50, lowerBS: 50, muscular: 50, fatigue: 0)
class와 struct의 차이를 알아보시고 이 코멘트를 다시 보면 어떨까요?

2022-03-08 14:51 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +class Bodycondition {
죄송합니다..제가 질문의 의도를 파악하지 못했었습니다.
Week3의 미션을 진행하면서 person과 coffeeshop을 구현할 때, class와 struct의 가장 큰 차이점, 값 전달과 참조 전달을 배웠습니다. 
만약 클래스로 생성된 객체의 속성을 바꾸려면 self.xx에서 해당 객체의 주소를 참조해 오리지날 객체의 속성을 변경할 수 있는 반면
구조체로 생성된 객체의 속성을 바꾸려면 mutating func으로 속성을 바꾸고, 속성이 바뀌어진 이름만 같은 다른 객체를 반환하는것으로 알고있습니다!

다시 코멘트 달아 주신것에 대한 답변은 구조체는 값 타입, 클래스는 참조 타입입니다!

2022-03-08 14:58 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +var myBody = Bodycondition(upperBS: 50, lowerBS: 50, muscular: 50, fatigue: 0)
이 부분도 제가 올라프님의 질문의 의도를 정확하게 파악하지 못해 잘못된 답을 드린것 같습니다.
myBody의 바뀌는 부분은 Bodycondition클래스내 프로퍼티들이 바뀐다고 생각을 해서 처음엔 var로 선언하였다가
다시 생각을 해보니 객체는 한번 선언하면 속성은 바뀌지만 해당 객체가 변경되는일은 없다고 생각해 let으로 바꾸었습니다!

처음에 달아주신 코멘트에 대한 제 생각은 "속성값이 바뀐다" 입니다!

2022-03-10 11:03 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +class Bodycondition {
그렇다면 결국 class로 선언한 이유는 없다라고 볼 수 있겠군요. 맞나요?

2022-03-10 11:04 UTC, 1Consumption commented on CodeStarterCamp_Week4/main.swift
> +var myBody = Bodycondition(upperBS: 50, lowerBS: 50, muscular: 50, fatigue: 0)
`속성값이 바뀐다` 라는게 정확히 어떤 뜻인지 잘 모르겠어요. 메모리 영역의 어느 부분이 바뀌는건가요?

2022-03-10 11:36 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +class Bodycondition {
현 코드에서는 쓰이지 않았지만 처음에 코드를 구상할 때 객체를 함수의 매개변수로 썼을때를 생각해 봤습니다. 
구조체로 생성한 객체를 매개변수로 전달 하게되면 함수 안에서 새로운 인스턴스를 생성하고 제가 원하는 방식대로 되지 않았던것.
반면 클래스로 생성된 객체를 썼을때는 본래의 의도된 해당 객체의 속성이 변하는 이유 때문에
코드를 짤때 나중에 객체가 매개변수로 전달되는 상황이 올것 같아 클래스를 썼던 이유도 있습니다.

2022-03-10 11:40 UTC, cpp2swift commented on CodeStarterCamp_Week4/main.swift
> +var myBody = Bodycondition(upperBS: 50, lowerBS: 50, muscular: 50, fatigue: 0)
> 클래스인데 var네요. 어떤 값이 바뀌는걸까요?
이부분은 객체의 속성(프로퍼티)이 바뀌는 부분을 말씀드렸습니다.
제가 제 자신을 봤을때 아직 객체를 var와 let중 어느것으로 선언해야하는지 공부를 더 해야할것 같습니다.

2022-03-10 11:50 UTC, 1Consumption commented
@cpp2swift 디코에서 얘기를 나눠보도록 해요.

2022-03-11 01:45 UTC, merged