Week4 [STEP 2] 마이노
yagom-academy/swift-starter-Round4 pull request #2
Opened 2021-12-30 08:38 UTC by Mino777

안녕하세요 네프! @Neph3779 
step2 PR 입니다~!

## 피드백
#### final 키워드 사용
### final keyword
> - 재정의 및 상속을 방지
> - 코드의 런타임 성능이 향상
#### final 키워드가 성능에 미치는 영향
- 오버라이딩한 메서드는 실행 시점에 어떤 메서드를 실행할지 결정(vtable)
- final 키워드가 적용된 메서드는 컴파일 시점에 어떤 메서드를 실행할지 결정할 수 있으므로(런타임 오버헤드가 제거되고 static dispatch로 구현 가능)성능 상 이점을 가짐.
>- vtable?
> - 가상 메서드 테이블
> - 메서드 오버라이딩에 따라 실행 시점에 어떤 메서드를 실행할지 결정하는 dynamic dispatch를 지원하기 위해 언어에서 사용하는 메커니즘

>- Method Dispatch?
>- Method를 호출할 때, 현재 메모리에서 어떻게 각 메소드를 실행시키고 어떤 메소드를 실행시킬지를 결정지을 때 사용
>- 대표적으로 Dynamic, Static으로 나뉨

>- Static Dispatch
>   - 가장 빠른 Dispatch 방식
>   - 컴파일 타임에 컴파일러가 어떤 메소드를 실행할지 주소값을 알고 있기 때문에 inline으로 빠르게 수행
> - Dynamic Dispatch
>    - 런타임 중에 어떤 메소드를 사용할 지 결정하기 때문에 오버헤드가 약간은 발생하고 속도가 느림.
>    - 하지만 OOP의 특징중 다형성 개념 때문에 많은 언어가 Dynamic Dispatch 방식을 사용함

#### ExerciseOption
- 파일 정리를 할때 아무래도 같은 유형의 타입끼리 묶어놓는게 편한 느낌이 들어서 따로 분리하는 편입니다!

#### Closure는 Reference? Value?
- Closure는 Reference Type이다.

#### Capturing Values
- 클로저가 매개변수나 지역변수가 아닌 주변 외부의 context를 참조하는 것(Capturing by reference)
```swift
func makeIncrementer(forIncrement amount: Int) -> () -> Int {
    var runningTotal = 0
    func incrementer() -> Int {
        runningTotal += amount
        return runningTotal
    }
    return incrementer
}
```
- runningTotal과 amount를 캡쳐해서 사용
- Closure는 값을 캡쳐할 때, Value/Reference 타입에 관계 없이 모두 Reference Capture 한다.

## 고민한 부분
- 현재 요구사항중에 목표치에 도달하지 못했을 경우 다시 루틴을 시작하는 기능을 구현하지 못했습니다.
  - 해당 기능 뿐만 아니고 에러가 났을 경우에 다시 프로세스가 시작되거나, 에러 메세지만 보여주고 계속 진행되어야 되는 부분들 ( ex) Input error )을 어떤식으로 구현해야할지 아이디어가 떠오르지 않습니다😭
- 뭔가 처음부터 구조자체를 잘못잡은 것 같은 느낌입니다😭

감사합니다!

2021-12-31 02:49 UTC, Neph3779 requested changes
안녕하세요 마이노님!
미션 안내에 있는 에러처리(Error Handling)이 
에러를 뿜고 프로그램이 죽는 것이 아닌 예외 케이스를 처리하라는 의도였던 것 같은데
조금 이 부분이 헷갈릴 여지가 있다보니 코드의 방향성이 많이 달라진 것 같아요 🥲
throw를 하는 부분도 너무 많다고 생각되는데 이 부분도 조금 개선해볼 수 있을 것 같아요! (지금 코드는 조금 흐름이 복잡한 감이 있네요 😅)

언제든 조언이 필요하시면 dm 부탁드려요!

2021-12-31 02:49 UTC, Neph3779 commented on CodeStarterCamp_Week4/Errors/InputError.swift
> +}
LocalizedError를 사용해보셨군요 ㅎㅎ 좋습니다!

2021-12-31 02:49 UTC, Neph3779 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    func start() throws {
메서드 네임이 조금 더 구체적이어도 좋을 것 같아요

2021-12-31 02:49 UTC, Neph3779 commented on CodeStarterCamp_Week4/Errors/InputError.swift
> +}
\+ 에러를 처리한다는 것이 꼭 에러를 뿜고 프로그램이 종료되는걸 의도한 것을 아니라고 하네요
프로그램이 바로 죽는 것보다는 예외 상황을 처리할 수 있도록 코드를 바꿔주시면 좋을 것 같아요!
예를 들면 잘못된 입력이 들어올 시 다시 입력을 받을 수 있도록 한다든지.. 등등이요

2021-12-31 02:49 UTC, Neph3779 commented on CodeStarterCamp_Week4/Views/InputView.swift
> +            }
enumerated를 사용하셨군요! for문을 쓰는 것과 비교해봤을때 어떤 장단점이 있을까요?

2021-12-31 02:49 UTC, Neph3779 commented on CodeStarterCamp_Week4/Views/InputView.swift
> +}
이 메서들에는 왜 Each라는 단어가 들어갔을까요?.. 
조금 이해하기 어려운 것 같아요 ㅠ

2021-12-31 02:49 UTC, Neph3779 commented on CodeStarterCamp_Week4/Views/InputView.swift
> +    }
위에서도 말씀드렸듯 에러처리 -> 예외케이스 처리로 바꿔주시면 좋을 것 같습니다

2022-01-03 04:53 UTC, Mino777 commented on CodeStarterCamp_Week4/Errors/InputError.swift
> +}
예외 상황을 처리할 수 있도록 수정하였습니다!

2022-01-03 04:53 UTC, Mino777 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    func start() throws {
좀 더 구체적으로 변경해보았습니다!

2022-01-03 04:54 UTC, Mino777 commented on CodeStarterCamp_Week4/Views/InputView.swift
> +}
굳이 Each가 안들어갔어도 되는 상황이었는데 입력문을 나누다보니 각각의라는 단어에 꽂혔던 것 같습니당ㅠㅠ 수정했습니다!

2022-01-03 04:54 UTC, Mino777 commented on CodeStarterCamp_Week4/Views/InputView.swift
> +    }
수정하였습니다!

2022-01-03 05:10 UTC, Mino777 commented on CodeStarterCamp_Week4/Views/InputView.swift
> +            }
### enumerated()
> - array값에 enumerated()함수를 사용하면, (index, value) 튜플 형식으로 구현된 리스트형이 리턴
>- array안에 값을 가져오며 해당 값의 index 값도 함께 가져오고 싶을 때 사용

장점으로는 index와 해당 배열의 값을 같이 가져와야할떄 더 간편하게 사용할 수 있다와
키, 값이 있으니 아무래도 시간복잡도에서 O(1)로 O(n)인 for문 보다 성능적으로 더 좋을 수 있다? 정도 인 것 같습니다.
단점으로는 관련 자료를 찾지 못했습니다ㅠㅠ 어떤것이 있을까요?!

2022-01-03 05:26 UTC, Mino777 commented
안녕하세요 네프! @Neph3779 
우선 말씀해주신 예외 케이스 발생시 프로그램이 죽는게 아닌 예외 상황들을 처리하는 방향으로 변경해보았습니다!
요구사항의 경우엔 모두 충족 시켰는데 코드 복잡성을 어떤식으로 리팩토링 해야할지 감이 오질 않습니다😭
구조도 조금 바꾸어서 진행을 해보았는데 복잡성은 여전한 것 같습니다..
어떤식으로 접근을 해보면 좋을까요ㅠㅠ

감사합니다!

2022-01-03 07:35 UTC, Neph3779 requested changes
안녕하세요 마이노님!
예외처리를 잘 해주셨어요!
조금만 리팩토링해보면 좋을 것 같은데
어떤 부분이 복잡하게 보이는지, 어떻게 고치고 싶은데 잘 안되는지 알려주시면 
도와드리기 더 수월할 것 같습니다! dm을 주셔도 좋고 회의실에서 봬도 좋을 것 같아요!
그럼 조금만 더 화이팅!!

2022-01-03 07:35 UTC, Neph3779 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            try? self.startRoutine()
catch문 내에서 해주는 작업들이 비슷하다면
이를 통합해줄 수 있지 않을까요?

2022-01-03 07:35 UTC, Neph3779 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            try? self.startRoutine()
where절을 활용해봐도 좋고 잘 안되는 부분은 질문답변방에 올려도 이부분은 활발한 토론이 이루어질 것 같아요!

2022-01-03 07:35 UTC, Neph3779 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            try? self.startRoutine()
fitnesError인지 확인해서 catch문을 통해 거르고
만약 fitnessError라서 catch문안에 들어왔다면? 타입 캐스팅을 통해 범용적으로 만들 수 있겠죠?

2022-01-03 07:35 UTC, Neph3779 commented on CodeStarterCamp_Week4/Models/Routine.swift
> +        guard bodyCondition.fatigue < 200 else {
이 부분은 어떤 작업인가요?

2022-01-03 08:18 UTC, Mino777 commented on CodeStarterCamp_Week4/Models/Routine.swift
> +        guard bodyCondition.fatigue < 200 else {
앗 해당 부분은 예외 케이스중에 목표치에 도달하지 않았을 경우를 처리할 때 피로도 한계치가 100밖에 안되다보니 해당 케이스를 보기가 어려워서 바꿨던 부분입니다! 다시 바꿔놓았습니다!

2022-01-04 06:17 UTC, Mino777 commented
@Neph3779 
확실히 네프가 알려주신 where와 타입캐스팅을 사용하는 방식으로 변경해보니 깔끔해진 느낌입니다!
감사합니다!

2022-01-04 08:03 UTC, Neph3779 commented
고생 많으셨습니다!
다음 미션에서 봬요~!

2022-01-04 08:03 UTC, merged