Mission4: Step1: 루틴을 지켜 운동을 해보자!
yagom-academy/swift-starter-Round4 pull request #26
Opened 2022-05-02 12:05 UTC by wolframhwang

- 타입별로 파일을 나눴습니다.
- Exercise 인스턴스에서 초기화 과정 시, bodyCondition Property를 직접 접근하게 했습니다.
    - 아무래도, 각 항목 마다 내부 메소드를 통해 하는건 코드 낭비 같아서요... 리뷰 부탁드릴게요
- forEach를 통해 순회하는 방식을 차용했습니다.

2022-05-03 05:34 UTC, llghdud921 requested changes
안녕하세요~ 제리입니다~
이번에도 너무 잘하셔서 리뷰드릴것이 별로 없었습니다... 🤔
너무 날로 먹는 것 같으니 질문 완전 환영입니다ㅎㅎ

아그리고 소소하지만 요구사항과 다른 부분이 있어서 수정부탁드릴게용

![스크린샷 2022-05-03 오후 2 34 08](https://user-images.githubusercontent.com/40068674/166408477-120abd6c-eaa5-4482-80fe-06b59f730bfd.png)
![스크린샷 2022-05-03 오후 2 33 40](https://user-images.githubusercontent.com/40068674/166408450-24453567-ba88-4ad0-a2c2-f2aa238e4f4c.png)

2022-05-03 05:34 UTC, llghdud921 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    func statusPrint() {
메소드는 기본적으로 동사구 형태로 네이밍합니다 :)
printStatus 가 좋을 듯 합니다!

2022-05-03 05:34 UTC, llghdud921 commented on CodeStarterCamp_Week4/Routine.swift
> +    func runRoutine() {
루틴을 실행하는 것이므로 run()이라는 네이밍도 좋을 것 같아요!

2022-05-03 05:34 UTC, llghdud921 commented on CodeStarterCamp_Week4/Routine.swift
> +        exercises.forEach { exercise in
forEach를 사용하셨군요!!
for문과 foreach의 차이는 무엇일까요?

2022-05-03 05:34 UTC, llghdud921 commented on CodeStarterCamp_Week4/main.swift
> +    }
해당 로직이 잘못 작성된 것 같습니다 😥
예를 들어 피로도가 3인경우 감소될 피로도가 5이면 감소하지 않고 그대로 3으로 남아있을 것 같네요!

2022-05-03 05:34 UTC, llghdud921 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        print("피로도: \(fatigue)")
여러개의 print문을 사용하는 것을 하나의 print로 처리할 수도 있습니다!
[Multiline String Literals](https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html#ID286)를 참고해보세요 :)

2022-05-03 07:24 UTC, wolframhwang commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    func statusPrint() {
동의합니다
이상하게 짯네요 ㅋㅋ;

2022-05-03 07:24 UTC, wolframhwang commented on CodeStarterCamp_Week4/Routine.swift
> +    func runRoutine() {
이 부분도 지난번에 지적해주셨던 사항인데, 또 실수를 했군요 ㅎㅎ; 감사합니다.

2022-05-03 07:24 UTC, wolframhwang commented on CodeStarterCamp_Week4/main.swift
> +    }
잘못된 로직임을 확인했습니다.
추후 패치에 fix로 반영했습니다.

2022-05-03 07:25 UTC, wolframhwang commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        print("피로도: \(fatigue)")
실제로 안써봤던 부분인데, 이번 패치에는 반영을 했습니다.

2022-05-03 07:28 UTC, wolframhwang commented on CodeStarterCamp_Week4/Routine.swift
> +        exercises.forEach { exercise in
for - in 문은 워딩 그대로 말하면, 반복 문 그 자체지만 forEach는 closure로 알고있습니다.
저희 이번 미션자체에서 Exercises가 담긴 요소를 하나씩 실행한다 라는 의미가 forEach랑 좀 더 부합한다고 생각해서 사용했습니다.

2022-05-03 07:28 UTC, wolframhwang commented
@llghdud921 제리

코멘트 주신 사항에 대해서 반영한 패치를 다시 올렸고,
그에 대한 답변을 답글로 달아두었습니다.

리뷰를 부탁드릴게요.

감사합니다~

2022-05-05 11:17 UTC, llghdud921 commented
안녕하세요!!
너무 늦게 머지드려서 죄송해요ㅠ 답글이 달린줄 몰랐어요..
이번 스텝 머지하고 넘어가겠습니다!! 고생많으셨어요!!

2022-05-05 11:17 UTC, merged