Week4 [Step 1] dooly
yagom-academy/swift-starter-Round4 pull request #27
Opened 2022-05-02 13:53 UTC by yuvinrho

@leeari95 

# Step 1
## 타입 정의
### 1.  BodyCondition
- 상.하체 근력, 근지구력, 피로도 프라퍼티를 갖는 구조체 정의
- 기본값 0
### 2  Exercise
- 운동이름을 나타내는 프로퍼티와 운동액션 함수타입 프라퍼티를 갖습니다.
- 액션 파라미터로 inout BodyCondition 값이 들어갑니다.  액션에 따라 파라미터로 들어온 바디컨디션값을 변경합니다. 
- 파라미터 값은 기본적으로 상수이기 때문에 변경할 수 없음. 파라미터값이 바뀌는 것 방지.
- inout 키워드는 파라미터 값을 수정할 수 있게함.
### 3. Routine
- 루틴 이름과, 운동배열을 프로퍼티로 갖습니다.
- 운동배열에 운동을 실행하기 위한 doExercises 메소드를 갖습니다.
- for in 구문을 이용하여 운동배열에 있는 각 운동의 이름을 출력 및 액션을 합니다.
- 매개변수로 inout 타입 바디컨디션이 들어옵니다. Exercise에 action 메소드 넘겨주어 운동에 따른 바디컨디션값이 변경됩니다.

## 각 운동 인스턴스 생성
인스턴스의 맨 마지막 인스턴스가 클로저이면 후행 클로저로 나타낼 수 있습니다.

## 인스턴스 생성
1. `var myCondition = BodyCondition()`
나의 컨디션을 나타내는 인스턴스를 생성합니다.

2. `let myExercises: [Exercise] = [윗몸일으키기, 윗몸일으키기, 동적휴식, 스쿼드, 스쿼드, 동적휴식, 오래달리기, 오래달리기]`
운동루틴을 실행하기 위해 운동배열을 만듭니다.

3. `let myRoutine = Routine(name: "hellRoutine", exercises: myExercises)`
내 운동 루틴 인스턴스를 하나 생성합니다.

4. `myRoutine.doExercises(&myCondition)`
내 운동루틴을 실행합니다. 나의 컨디션을 매개변수로 넘겨줍니다. inout 파라미터를 사용하는 함수를 호출할 때는 &를 사용하여 넘겨줍니다.

2022-05-03 01:58 UTC, leeari95 requested changes
둘리~ 안녕하세요!
스텝1을 엄청 빠르게 구현해주셨네요!! 🫢
커밋 이력과 적어주신 상세한 설명 덕분에 코드를 보는게 너무 수월했어요! 😆

다만 한가지 의견드릴 것이 있어 코멘트 남겨봅니다!

## 저의 의견

* inout 키워드

인 아웃 키워드를 활용해서 BodyCondition의 프로퍼티들을 수정해주고 있는데요.
이런 방법보다는 BodyCondition 타입 내부에 프로퍼티의 상태를 바꿔주는 함수를 만들어주면 어떨까요?
Routine타입의 doExercises(_:) 메소드처럼 
타입과 관련된 기능은 타입 내부 메소드로 있는게 훨씬 보기 좋아질 것 같아요.
물론 둘리의 방법이 틀리다는 것은 아닙니다!

#

클로저도 잘 활용해보셔서 제가 리뷰드릴 것이 많이 없네요ㅎㅎ
너무 잘해주셔가지고... 😁
이번주도 잘부탁드려요 둘리!
고생하셨습니다~ 😊

2022-05-03 01:58 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +    func doExercises(_ bodyCondition: inout BodyCondition) {
inout 키워드를 사용하신 이유가 무엇인가요?
또 inout 키워드를 붙이게되면 안붙인 것과 차이점이 뭘까요?

2022-05-03 01:58 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +    $0.피로도 += Int.random(in: 10...20)
피로도를 요구사항에 맞게 만들어주신걸까요?

2022-05-03 01:58 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +""")
이게 조금 더 가독성이 좋을 것 같아요!
```suggestion
print("""
      현재의 컨디션은 다음과 같습니다.
      상체근력 : \(myCondition.상체근력)
      하체근력 : \(myCondition.하체근력)
      근지구력 : \(myCondition.근지구력)
      피로도 : \(myCondition.피로도)
      """)
```

2022-05-03 01:58 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +    var 피로도: Int = 0
이니셜라이저를 쓰지 않고 기본값으로 할당해주신 이유가 궁금해요! 🤔

그리고.. 네이밍이 한글로 되어있네요?
제가 겪어본 바로는.. Xcode에서 한글로 네이밍을 하게 되면 강제종료가 되는 버그가 있는 걸로 알고있어요.
한글말고 영어로 네이밍 해보면 어떨까요?

2022-05-03 14:38 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    func doExercises(_ bodyCondition: inout BodyCondition) {
doExercises 메소드 호출시 파라미터로 넘어간 바디컨디션값을 수정해주고 싶었습니다. 함수에서 파라미터는 기본적으로 상수값으로 실수로 파라미터 값을 변경할 수 없게 되어있습니다. 따라서 inout 키워드가 없는 경우 파라미터 값을 수정할 수가 없습니다~ 제가 답변한게 질문의도와 다르다면 힌트 부탁드립니다~

2022-05-03 14:38 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    $0.피로도 += Int.random(in: 10...20)
앗ㅎㅎ 수정하였습니다~~

2022-05-03 14:39 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +""")
들여쓰기를 해야되나 말아야되나 고민했었는데 하는게 괜찮은 거군요~~ 감사합니다! 들여쓰기 수정하였습니다~~

2022-05-03 14:43 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    var 피로도: Int = 0
음... 다른 이유는 없었고 바디컨디션 인스턴스를 만들때 BodyCondition() 이렇게 만드는게 간단하다고 느껴서 구조체에 기본값을 정해주었습니다~ 현업에서는 기본값보다 이니셜라이저를 대체적으로 쓰는지도 궁금합니다~

2022-05-03 14:57 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    var 피로도: Int = 0
한글이름에서 영어로 수정하였습니다~~ 단축키 최고!! 이런기능이 있는줄 몰랐습니다ㅎㅎ 꿀팁 감사합니다!

2022-05-04 00:52 UTC, leeari95 approved these changes
안녕하세요 둘리!
수정사항 잘 확인했습니다!

저는 보통 프로퍼티에 직접 값을 할당해주는 것 보단 이니셜라이저를 활용하는 편이에요.
이유는 나중에라도 혹시 기본값을 수정해주고 싶을 때, 직접 코드를 건드리지 않기 위해서에요.

물론 지금처럼 var인 프로퍼티에 기본값이 할당되어있어도 
구조체의 경우 멤버와이즈 이니셜라이저 때문에 큰 문제는 없겠지만... 
let일 경우, 클래스일 경우에는 제공되지 않아요.

그리고 이니셜라이저 뜻 자체가 초기화잖아요? 
이 타입의 초기값은 이렇다~~ 명확해지기도 하고... 
저는 그래서 이니셜라이저를 활용하는 편이에요!

어떻게 답변이 되셨을까.. 모르겠네요 ㅎㅎ ☺️

이번에도 제가 드린 피드백 반영해주셔서 정말 감사해요! 😁
더이상 문제없어서 머지해드리겠습니다!!
둘리 고생하셨어요. 다음 스텝에서 만나요~ 👋🏻

2022-05-04 00:52 UTC, merged