Week4 [Step1] Onestar
yagom-academy/swift-starter-Round4 pull request #28
Opened 2022-05-03 16:56 UTC by oneStar92

@oksunwoo 
***
# Step 1: 루틴을 지켜 운동을 해보자!
- [x] 운동 상태를 체크하기 위해 BodyCondition 타입과 그 인스턴스를 생성합니다.
  * BodyCondition 타입은 다음과 같은 프로퍼티를 갖습니다.
    * 상체근력
    * 하체근력
    * 근지구력
    * 피로도
  * 운동을 진행하면 BodyCondition 인스턴스의 프로퍼티에 할당된 값이 변화합니다.
- [x] 아래에 제시된 운동 타입을 활용해 다양한 운동 인스턴스를 생성합니다.
```swift
//운동 타입
struct Exercise {
  let name : String
  let action: () -> Void
}

//예시 운동
let 윗몸일으키기: Exercise = Exercise(name: "윗몸일으키기", {
//BodyCondition에 영향을 주는 클로저 내용
})
```
  * 필수적으로 구현해야하는 운동은 다음과 같습니다.
    - [x] 윗몸일으키기
      * 상체 근력이 10 ~ 20 사이에서 랜덤하게 상승합니다.
      * 피로도가 10 ~ 20 사이에서 랜덤하게 상승합니다. 
    - [x] 스쿼트
      * 하체 근력이 20 ~ 30 사이에서 랜덤하게 상승합니다.
      * 피로도가 10 ~ 20 사이에서 랜덤하게 상승합니다.
    - [x] 오래달리기
      * 근지구력이 20 ~ 30 사이에서 랜덤하게 상승합니다.
      * 상,하체 근력이 5 ~ 10 사이에서 랜덤하게 상승합니다.
      * 피로도가 20 ~ 30 사이에서 랜덤하게 상승합니다.
    - [x] 동적휴식(Active Rest)
      * 피로도가 5 ~ 10 사이에서 랜덤하게 하락합니다.
    - [x] 이외에도 추가적인 동작을 구현해보세요!
- [x] Routine 타입을 생성합니다.
  * Routine 타입은 다음과 같은 프로퍼티를 갖습니다.
    * 루틴의 이름(String)
    * 운동, 휴식과 관련한 클로저를 순서에 맞게 담아둔 exercises 배열
- [x] 나만의 루틴을 생성하고, 루틴을 진행했을 때 BodyCondition의 인스턴스가 실행 예시와 유사한 결과값을 가질 수 있도록 해봅시다.
```swift
--------------
hellRoutine을 시작합니다.
윗몸일으키기
윗몸일으키기
동적휴식
스쿼트
스쿼드
동적휴식
오래달리기
오래달리기
--------------
현재의 컨디션은 다음과 같습니다.
상체근력: 120
하체근력: 80
근지구력: 90
피로도: 80
```
***
# 질문
1. 클로저 사용이 올바른지 잘 모르겠습니다. 제 생각에는 BodyCondition의 값을 변화시키기 위해선 결국 BodyCondition을 클로저의 파라미터로 받은 후 해당 파라미터를 클로저 내부 변수에 복사하고 복사된 변수를 바탕으로 클로저 내부를 수행한 후 해당 변수를 반환해서 반환된 값을 다시 BodyCondition에 복사하는 형태 이외에는 방법이 없는것 같아서 이렇게 구현하였는데 코드가 너무 길어보여서 고민이 많았습니다. 토니의 생각은 어떤가요??
2. PR을 보낸 후 생각해보니 값 타입인 struct가 아닌 참조 타입인 class로 BodyCondition을 정의하는게 클로저의 내부에서는 더 나아보여서 질문드립니다. 그 이유는 현재와 같은 값을 복사하는 것 보단 참조하는 것이 더 나은 사용을 보이는 것 같습니다.
 하지만 상속을 하지도 받지도 않고 저장된 프로퍼티가 값타입이고 간단한 캡슐화가 목적인 BodyCondition의 경우 struct를 사용하는게 맞다고 생각하는데 단지 사용에 있어서 값을 복사하는 형태가 아닌 참조하는 형태가 더 나은 사용을 보인다고해서 class로 사용해야 하는지 궁금합니다.

2022-05-04 17:10 UTC, oksunwoo requested changes
전반적으로 읽기 괜찮은 코드였습니다.
이제 슬슬 코드의 양이 길어지기 시작하는 거 혹시 느끼셨나요?
그럼 이제 가독성을 위해서 무엇을 더 해줄수있을까요?ㅎㅎ
바로 파일분리입니다. 원스타는 아마 코딩 경험이 있으셔서 파일분리도 능숙하게 잘해내실것 같은데요!
이번에는 한번 타입별로 나누어볼까요? 실행부분은 당연히 main이겠죠?
앞으로도 파일을 나누는 연습도 해보자구요! MVC구조의 밑거름이 될 수 있을거에요!

---
### 질문사항에 대한 답변

1. 음.. 우선 클로저의 사용은 아주 적절했다고 생각합니다. 만약 요구사항대로가 아닌 원스타의 형태였다면 저 형식으로 저도 사용했을 것 같습니다. 잘해주셨어요.

2. class와 struct 이 부분이 참 어렵기도 하고 간단하기도 합니다. 우선은 apple공식문서에서는 기본적으로 struct의 사용을 지향하고 있습니다. 그리고 원스타가 말씀해주신 방향도 옳은 이유라서 struct의 사용이 좋다고 생각합니다. 만약, 상속할 필요도 없고, struct의 내부또한 reference type이 없고, value type만 있게 된다면, 메모리적인 측면에서 저는 아무래도 struct를 사용할 것 같습니다ㅎ 근데 이부분은 너무나도 먼 이야기라서... 현재 코드에서는... class던 struct던 둘다 좋을 것 같다는 의견 드리고 싶습니다.

2022-05-04 17:10 UTC, oksunwoo commented on CodeStarterCamp_Week4/main.swift
> +}
이렇게 init을 두개 작성하셨군요!
왜 그랬는지 설명해주세요~

규칙은 없지만, 일반적으로는 init을 한개만 작성하는데요. 그래서 같은 기능을 하는 다른 init들이 있다는 것만 알고 계시면 좋을 것 같습니다. 구글에 swift init 한번 검색해보시면 무엇이 그 역할을 하는지 바로 알 수 있을 겁니다.

2022-05-04 17:10 UTC, oksunwoo commented on CodeStarterCamp_Week4/main.swift
> +}
요구사항에서는 운동타입을 이미 만들어주고, 저 만들어진 Exercise를 이용하라는 의미같아요~

<img width="711" alt="스크린샷 2022-05-05 오전 1 00 03" src="https://user-images.githubusercontent.com/55880539/166722396-bd0f19ad-8bef-4b71-b0ba-f845581223df.png">

2022-05-04 17:10 UTC, oksunwoo commented on CodeStarterCamp_Week4/main.swift
> +}
클로저의 활용 여쭈어보셨는데, 아주 잘 작성해주셨습니다!
그러면 여기서 클로저란 무엇이고, 왜 쓰는지 한번 설명해주시겠어요?

2022-05-04 17:10 UTC, oksunwoo commented on CodeStarterCamp_Week4/main.swift
> +myBodyCondition = upperBodyRoutine.startRoutine(bodyCondition: myBodyCondition)
158,159 변수 myBodyCondition에 담고나서 아무런 역할도 하지않고 있는데요!
이렇게 담아서 추후에 활용할 계획이셨던건가요? 물론 제가 코드를 다운받아서 요구사항대로 refactor를 해보니 해당부분은 없어지긴 하네요~

2022-05-05 15:08 UTC, oneStar92 commented on CodeStarterCamp_Week4/main.swift
> +}
init(upperBodyStrength: Int, lowerBodyStrength: Int, muscleEndurance: Int)의 경우 기본적인 Designated init의 형태입니다. 하지만 제가 init()을 추가적으로 구현한 이유는 아무값도 넣지 않았을때 기본값으로 생성되는 init을 만들어 놓고 싶어서 이렇게 코드를 작성 하였습니다. 일반적으로 한개의 init만 사용하는지는 몰랐네요. ㅠㅠ struct의 경우 보조 이니셜라이저를 지정해주지 못해서 이렇게 작성했는데 현재는 수정하였습니다.

2022-05-05 15:09 UTC, oneStar92 commented on CodeStarterCamp_Week4/main.swift
> +}
요구사항에 맞게 refactor했습니다.

2022-05-05 15:19 UTC, oneStar92 commented on CodeStarterCamp_Week4/main.swift
> +}
클로저란 일급객체의 역할을 할 수 있는 코드블럭이라고 알고있습니다.
클로저를 사용하는 이유는 몇번 사용되지 않는 코드를 함수로 지정하여서 메모리를 낭비하지 않기 위해서 사용하는 것으로 알고있습니다.

2022-05-05 15:21 UTC, oneStar92 commented on CodeStarterCamp_Week4/main.swift
> +myBodyCondition = upperBodyRoutine.startRoutine(bodyCondition: myBodyCondition)
stuct인 BodyCondition의 프로퍼티 값을 수정하기위해서 사용하였습니다. 현재는 수정하였습니다.

2022-05-05 15:41 UTC, oneStar92 commented
***
# 질문사항
저의 질문이 제대로 전달되지 않은 것 같아요 ㅠㅠㅠㅠ 죄송합니다. 말을 잘 못해서 ㅠㅠ
* BodyCondition과 Exercise에 관한 질문.
 요구사항의 Exercise의 action프로퍼티는 아래와 같은 형태를 원하는 것 같습니다.
```swift
var action: (BodyCondition) -> Void
```
여기서 BodyCondition의 프로퍼티 값을 수정하기 위해선 제가 할 수 있는 방법은 세가지가 있었습니다.
  1. BodyCondition이 struct가 아닌 class를 사용하기.
 해당 방법은 BodyCondition은 struct가 맞는 사용인데 단지 action의 클로저 내부에서 값을 변경하는데 수월한 사용을 위해서 class로 바꾸는 건 올지 않다고 생각했습니다.
  2. inout을 사용하기.
 해당 방법은 일전에 Inout을 사용했을 때, 토니가 배운내용을 토대로 구현해보는 방법을 추천하여서 사용을 배제하였습니다.
  3. 전달 받은 값을 클로저 내부에서 새로운 변수에 복사 한 후 복사된 BodyCondition의 값을 변경한 후 복사된 BodyCondition을 반환하기.
 해당 방법은 요구사항을 따르지 안고 코드의 가독성 또한 떨어지며 코드가 지저분해저서 고민하였습니다.
그래서 토니에게 질문을 했는데 ㅠㅠ 다음부턴 조리있게 질문하겠습니다!!
현재 코드는 inout을 사용하여서 구현하였습니다.

2022-05-09 05:31 UTC, oksunwoo reviewed
질문사항이 혹시 저 중에 1가지 어떤것이 좋을지 물어보는 거인가요??
혹시 그렇다면 지금은 1번이 제일 괜찮아 보입니다! 3번역시 좋아보이긴 하나, 원스타가 말씀하신대로 작성하신다면 요구사항과는 살짝 다른 action을 가지기 때문이죠! 처음에 2번을 지양한다고 말씀하신 것도 올바른 고민이라고 느껴집니다!
그리고 저렇게 고민한 흔적 너무 보기좋습니다!
해당 부분만 고쳐주시면 될것같습니다!

2022-05-09 05:31 UTC, oksunwoo commented on CodeStarterCamp_Week4/Exercise.swift
>  }
혹시 캠퍼의 요구사항과 도우미의 요구사항이 조금 다른걸까요?
제가 보는 요구사항은 let action: () -> Void 거든요
<img width="298" alt="스크린샷 2022-05-09 오후 2 25 09" src="https://user-images.githubusercontent.com/55880539/167345760-86ad8f6b-134b-4a58-b04e-29c4fc332eee.png">

2022-05-09 05:31 UTC, oksunwoo commented on CodeStarterCamp_Week4/Exercise.swift
>  }
축약형을 사용해주셨네요! $0은 무엇인가요?

2022-05-09 05:31 UTC, oksunwoo commented on CodeStarterCamp_Week4/Routine.swift
> -            return exerciserBodyCondition
지난번에 말씀드린 것처럼 inout을 사용하여 참조형태로 강제로 바꾸는 것은 지양하는 것이 좋아보입니다!

2022-05-09 06:48 UTC, oneStar92 commented on CodeStarterCamp_Week4/Exercise.swift
>  }
$0의 경우 파라미터의 축약형으로 첫번째 파라미터를 뜻합니다.

2022-05-09 06:49 UTC, oneStar92 commented on CodeStarterCamp_Week4/Routine.swift
> -            return exerciserBodyCondition
BodyCondition을 class로 수정하여서 inout은 삭제 하였습니다.

2022-05-09 06:49 UTC, oneStar92 commented on CodeStarterCamp_Week4/Exercise.swift
>  }
요구사항에 맞게 수정했습니다!

2022-05-09 06:55 UTC, merged