Week4 [STEP 1] 쿼카
yagom-academy/swift-starter-Round4 pull request #3
Opened 2021-12-30 09:35 UTC by Quokkaaa

안녕하세요 글렌! @Journey36 
STEP1 PR잘부탁드립니다!

클로저를 실행하는 방법을 몰라 많이 헤맸던것같아요..^^
날이 많이 추워지고있는데 글렌!! 감기조심하세요ㅎㅎ 
그리고 곧 2021년이 끝나가네요 새해복 많이받으세요!! 😄 

# 고민했던점
- 되도록 운동, 루틴, 근력 등의 문자열 값들을 열거형으로 캡슐화하도록 구현했습니다.
- `BodyCondition`을 `class`로 변경한 이유는 `struct`로 구현하였을때 자신의 메서드 타입을 `Exercise`로 반환할때 `Partial application of 'mutating' method is not allowed` 라는 오류메세지가 확인되어 `class`로 변경하였습니다.
- 요구사항대로는 `Exercise` 구조체타입 내 `action`프로퍼티의 타입이 `() -> Void`로 구현이 되어있으나 그렇게 구현했을 경우 `Routine` 타입의 인스턴스의 `[() -> Exercise]`내에 `Exercise`의 인스턴스로 만든 `action`프로퍼티와 타입이 달라 들어 갈 수 없을거라고 판단하였습니다.
그래서 구조체타입 내 `exercises`프로퍼티인 `[()->Exercise]`타입과 같은 반환타입을 갖게되면 구현하기에 적합하다고 판단하여 이와 같이 작성했습니다. 혹시 제가 스스로 판단하여 바꾼것은아닌지 조금 조심스럽기도하여 확인한번 부탁드려요 ㅜㅜ..

# 궁금한점
- 프로젝트의 요구사항을 의도한대로 구현했는지 궁금합니다.

2021-12-31 08:27 UTC, Journey36 requested changes
@Quokkaaa
안녕하세요, 쿼카님!
클로저 많이 어렵죠? 저도 아직까지 어렵다고 생각하는 부분 중의 하나입니다. 😢
하지만 Swift 및 iOS 개발에서 정말 자주 사용하니, 지금 많이 부딫히는 게 도움이 많이 될거에요!
코드 확인 후 코멘트 남겼습니다. 확인부탁드립니다!

그리고 고민하고 계신 부분에 대해서 약간 힌트를 드리자면, 요구사항을 충족 후, 추가되는 부분에 대해서는 관계가 없지만, 요구사항을 구현하기 힘들어서 임의로 변경하는 것은 위험하다고 말씀드리고 싶네요. 어쨌든 **요구사항** 이니까요.🙂 그래도 충분히 납득이 갈만한 이유라면 괜찮다고는 생각합니다. 그래도 충족해서 코드를 작성하도록 노력해봅시다.

더 궁금한 부분이 있으시다면, DM으로 주시거나 코멘트 남겨주세요. ㅎㅎ

2021-12-31 08:27 UTC, iluxsm commented on CodeStarterCamp_Week4/main.swift
> +    var action: () -> Self
요구 사항에는 `() -> Void` 타입이었던 것 같은데, 다르게 타입을 주셨네요?
그럼 `Self`는 무엇이고, 왜 `Self`를 반환하도록 하셨나요?

2021-12-31 08:27 UTC, iluxsm commented on CodeStarterCamp_Week4/main.swift
> +
해당 열거형의 역할은 무엇인가요?

2021-12-31 08:27 UTC, iluxsm commented on CodeStarterCamp_Week4/main.swift
> +}
해당 열거형은 각 운동의 분류를 나타내는 것 같은데, 단순한 루틴의 이름만 나타내고 있네요? 🤔 왜 열거형으로 만들려고 하셨나요?

2021-12-31 08:27 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +class BodyCondition {
왜 클래스로 지정하셨나요?

2021-12-31 08:27 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +    }
해당 운동 관련 함수들은 `BodyCondition` 의 프로퍼티 값들을 쉽게 가져올 수 있죠? ㅎㅎ 하지만 `BodyCondition`이라는 클래스와 직접적인 상관관계가 있다고 볼 수 있을까요? 🤔

2021-12-31 08:27 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +    var action: () -> Self
왜 `action`은 변수로 선언해주셨을까요?

2021-12-31 08:27 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
>      }
`action` 매개변수에 자기 자신을 불러주고 있네요? 그럼 해당 함수가 호출됐을 때는 어떻게 되는 걸까요?

2021-12-31 08:27 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +var quokka = BodyCondition(uppperBodyStrength: 0, lowerBodyStrength: 0,
왜 변수로 인스턴스를 생성하셨나요?

2021-12-31 08:27 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +    lowerBodyStrength.exercises.forEach { exercise in exercise() }
`forEach`를 사용해보셨네요 ㅎㅎ 그럼 `forEach`와 `for-in`은 어떤 차이가 있을까요?

2021-12-31 08:27 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +}
출력 형식이 요구사항과 맞지 않는 부분이 있네요. 확인 부탁드립니다.

2022-01-02 08:15 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +    var action: () -> Self
요구사항을 잘못이해하여 타입을 다르게 주었어요 ㅜㅜ
Self란 자신의 타입을 편하게 지칭할때 사용하는것으로 알고있습니다만.. 공식문서를 확인해보니 자신의 타입을 참조한다고 나와있네요..!!
사용이유는 `Routine` 의 `[()->Exercise]`에 `action`프로퍼티를 담기위해서 같은 함수타입으로 지정해주어야 한다고 판단했어요!

2022-01-02 08:16 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +
운동들의 종류를 정렬해놓는 용도입니다.

2022-01-02 08:21 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +}
루틴의 이름들이 한정적일거라고 판단했고 인스턴스를 생성할때 루틴의 이름을 선택지로 제공하면 편리할 수 있겠다고 판단했습니다.

2022-01-02 08:23 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +class BodyCondition {
위에 고민한점에도 말씀드린것과 같은 이유에서 어쩔수없이..? 지정하게 됬습니다..!!

2022-01-02 08:28 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +    var action: () -> Self
이부분은 휴먼에러라고 할 수 있습니다..ㅎㅎ var으로할 이유는 없는것같은데 하다보니...그렇게 지정된것같아요

2022-01-02 08:34 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
>      }
action()와 같이 소괄호를 붙여 호출하지않는한 `(Function)`이라는 함수타입의 값이 호출되는걸로 알고있습니다.

2022-01-02 08:37 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +var quokka = BodyCondition(uppperBodyStrength: 0, lowerBodyStrength: 0,
계속변경될값이라고 판단하여 var으로 설정해주었는데요!!
구조체일경우에는 var로 지정해주어야만 함수를 통해 BodyCondition의 값들이 변경될 수 있는데 class일 경우에는 let으로 설정하여도 주소를 참조하기때문에 값들이 변경될 수 있어? var로 설정하지 않고 let으로 지정해도 될것같네요 ㅎㅎ

2022-01-02 08:52 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +}
루틴을 시작하는 이름을 빼먹었네요 ㅎㅎ 수정하겠습니다.

2022-01-02 08:57 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +    lowerBodyStrength.exercises.forEach { exercise in exercise() }
큰 차이로 `forEach`는 클로저 라서 값을 반환할 수 있다는 차이점이있구요
그 외에 `for-in`은 `.count`기능이 있지만 `forEach`는 사용할 수 없는것같습니다.

2022-01-02 09:07 UTC, Quokkaaa commented on CodeStarterCamp_Week4/main.swift
> +    }
아하.....ㅎㅎ 오히려 메서드들이 `Exercise`타입과 상관관계가 있는게 자연스러운것같습니다.

2022-01-02 23:38 UTC, Journey36 commented on CodeStarterCamp_Week4/main.swift
> +    routine.exercises.forEach { $0.action() }
깔끔하네요! 👍

2022-01-02 23:40 UTC, Journey36 commented
@Quokkaaa 
쿼카님, 안녕하세요! 주말 잘 보내셨나요?
추가적으로 리팩토링 해주신 코드를 확인했는데, 이전에 고민했던 부분들도 해결된 것 같고 더 깔끔해진 것 같네요.
이번엔 따로 드릴 말씀은 없네요! 스텝 1 진행하느라 고생하셨고, 머지하겠습니다. 다음 스텝에서 만나요! 🙂

2022-01-02 23:40 UTC, merged