Week4 [STEP1] jeongmin(정민)
yagom-academy/swift-starter-Round4 pull request #30
Opened 2022-05-04 03:26 UTC by jeongmin-l

@jaemuYeo 

안녕하세요 잼킹!
4주차의 첫번째 PR보내드립니다!

# 코드 설명

+ BodyCondition 타입
+ Exercise 타입
+ Routine 타입
+ Person 타입

## BodyCondition
상체근력, 하체근력, 지구력, 피로도의 값을 가지고 있는 타입입니다.
상속을 고려하지 않았고 값의 캡슐화를 위해서 struct를 선택했습니다.

## Exercise
운동의 이름과 행동을 가지고 있는 타입입니다. 
마찬가지로 값의 캡슐화를 위해서 struct를 선택했고 BodyCondition타입을 인자로 받아서 이용하는데
BodyCondition이 Struct타입이라서 Inout변수를 사용했습니다.

## Routine
루틴의 이름과 운동리스트를 가진 타입입니다.
이 타입은 고민을 좀 했던 타입이었는데 결국 이 타입도 값의 캡슐화가 필요한 것 같았고 struct를 선택했습니다.

## Person
이름과 루틴, 몸의 컨디션을 가진 타입입니다.
이 타입은 class로 해주었는데 사람은 할당되면 변하지 않아야 한다고 생각해서 상수로 선언했습니다.
그런데 몸의 컨디션을 바꾸어 주어야 하기때문에 참조 타입인 class를 선택했습니다.

# 궁금한 점 🤔
1. 클래스와 구조체의 선택이 쉽지 않았던 것 같습니다..
사실 Person타입을 제외한 나머지는 캡슐화의 필요성을 생각해서 struct타입을 선택했는데
그 외에 클래스를 사용할 이유를 찾지 못해서 struct를 사용한 것 같습니다 
잼킹께서 보시기에는 struct와 class의 사용이 적절해 보이는지 궁금합니다!

2. 타입의 인스턴스를 초기화 하면서 사용되는 init 도 함수의 인자레이블 네이밍 처럼 평문이나 명령문 처럼 읽히는게 좋은지?
아니면 타입을 선언하는 데에서는 구조(부품, 부품, 부품)의 형태로 작성하는게 좋은지 궁금합니다!

2022-05-04 13:03 UTC, jaemuYeo requested changes
안녕하세요 정민님!! week4까지 빠르게 오셨네요!!👍
일단 저는 클래스와 구조체를 적절하게 잘 사용하셨다고 생각합니다!!
혹시 선택하는 과정에서 마음에 걸리셨던 부분이 있으셨나요??🤔
init네이밍 관련해서는 저는 후자쪽을 더 지향하고 있습니다.
init과정에서 해당 객체의 프로퍼티를 이용한 다른 의미의 값을 초기화할때에는 네이밍이 바뀔 수 있겠죠?
인자 레이블에 와일드카드 패턴을 사용하는 경우도 있습니다!
몇 가지 코멘트에 대해 얘기나눠보고 수정할 사항이 없다면 추후에 머지 진행하겠습니다!

2022-05-04 13:03 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Exercise.swift
> +let 윗몸일으키기: Exercise = Exercise(name: "윗몸일으키기") { condition in
예시에 나온 것 처럼 한글로 네이밍해주셨군요 😭
초반에 얘기했던 일관성 있는 코드를 선호한다고 했던 말 기억나시나요??ㅎㅎ
또 한글로 변수명을 짓게되면 어떤 안좋은 것들이 있을까요?🤔

----

클로저를 잘 사용하셨네요!👍

2022-05-04 13:03 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Exercise.swift
> +    condition.upperBodyStrength += Int.random(in: 10...20)
여기를 비롯한 아래에 랜덤하게 숫자를 뽑는 것들 중 공통되는 범위들이 보이네요😀
이러한 값들을 하나의 객체 또는 Int타입을 extension하여 저장하고 뽑아쓴다면 더 의미있는 숫자가 되지않을까요?
정민님의 생각은 어떠신가요! (필수 수정 내용은 아닙니다!)

2022-05-04 13:03 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Person.swift
> +class Person {
Person 객체는 다음 스텝과 연관된 것인데 벌써 등장했군요!!👍

2022-05-04 13:03 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +    print("현재의 컨디션은 다음과 같습니다.")
하나의 print 함수로 여러줄을 출력하지 않고,
print를 여러번 사용하신 이유가 있으신가요?

2022-05-04 13:03 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Exercise.swift
> +    let action: (inout BodyCondition) -> Void
inout의 사용용도 좋은 것 같습니다!

2022-05-04 15:42 UTC, jeongmin-l commented on CodeStarterCamp_Week4/Exercise.swift
> +let 윗몸일으키기: Exercise = Exercise(name: "윗몸일으키기") { condition in
제 코드를 깃에 공유하고 외국사람과 소통할 때 세계 공용 언어인 영어가 아니면 소통이 불편할 수 있다는 점이 있습니다!
어디선가 영어 + 한글의 형태로 가독성을 높이고 글을 봐버려서 잠시 만용을 부렸던 것 같습니다 ㅎ... 😅 수정하겠습니다!

2022-05-04 16:49 UTC, jeongmin-l commented on CodeStarterCamp_Week4/Exercise.swift
> +    condition.upperBodyStrength += Int.random(in: 10...20)
저도 동감합니다! Int.random() 메서드를 쓰는 것 보다는 값에 이름을 가지고 쓰는 것이 더 의미있는 숫자가 될 것 같아요!

```swift
extension Int {
    mutating func increaseWeights(from start: Int, to end: Int) {
        self = self + Int.random(in: start...end)
    }
    
    mutating func decreaseWeights(from start: Int, to end: Int) {
        self = self - Int.random(in: start...end)
    }
}

let sitUp: Exercise = Exercise(name: "윗몸일으키기") { condition in
    condition.upperBodyStrength.increaseWeights(from: 10, to: 20)
    condition.fatigue.increaseWeights(from: 10, to: 20)
}
```
그래서 최대한 구현을 해보려고 했는데요.. 
일단 extension을 사용해서 메서드로 값을 변경시켜보았는데 의미있는 숫자는 된 것 같으나
객체에 값을 저장하는 방법과 extension에 값을 저장하고 뽑아쓰는 방법이 떠오르지 않았습니다....
잼킹께서 생각하셨던 방법은 무엇이셨을까요 😭

2022-05-04 16:52 UTC, corpiii commented on CodeStarterCamp_Week4/Person.swift
> +class Person {
반복문을 사용하는데 exercise의 배열과 routine, condition을 한 객체에서가 아닌 따로따로 사용하다보니 
코드의 흐름이 부자연스러워 보여서 이 3가지 값들을 묶어줄 Person 객체가 필요해 보였습니다 
그래서 묶어주는 용도로만 먼저 사용해 보았습니다 😅

2022-05-04 16:56 UTC, jeongmin-l commented on CodeStarterCamp_Week4/main.swift
> +    print("현재의 컨디션은 다음과 같습니다.")
앗 안좋은 습관이 또 나와버린 것 같습니다. 여러 줄을 프린트 할때는 """ """ 사용! 
다시 한번 상기시키겠습니다

2022-05-04 16:56 UTC, jeongmin-l commented on CodeStarterCamp_Week4/Exercise.swift
> +    let action: (inout BodyCondition) -> Void
감사합니다! 😁

2022-05-04 17:13 UTC, corpiii commented
클래스와 구조체를 선택할 때 상속과 캡슐화, 객체를 현실세계인 것 처럼 추상화 할 때 사람이 변하면 안된다는 등의 이유 외에도 
좀 더 확실한 이유가 있을 것 같은데 떠오르지 않아서 조금 마음에 걸렸습니다 😢
init네이밍 관련해서도 이해했습니다 후자쪽을 지향하되 경우에 따라 융통성있게 사용하면 되는군요! 😊
main내의 workOut메서드와 showCondition메서드를 Person의 내부로 옮겼습니다 조금 더 자연스러워 보여서요!

2022-05-05 08:43 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Exercise.swift
> +    condition.upperBodyStrength += Int.random(in: 10...20)
제가 생각했던 방법은 정말 단순해요!!
말그대로 값(프로퍼티)를 저장해 사용하는 방법이었습니다.
```swift
enum RandomRange {
    static let tenToTwenty = Int.random(in: 10...20)
    static let twentyToThirty = Int.random(in: 20...30)
}

let 윗몸일으키기: Exercise = Exercise(name: "윗몸일으키기") { condition in
    condition.upperBodyStrength += RandomRange.tenToTwenty
    condition.fatigue += RandomRange.tenToTwenty
}
```
또는
```swift
extension Int {
    static let tenToTwenty = random(in: 10...20)
    static let twentyToThirty = random(in: 20...30)
}
```

하지만 이번에 정민님이 해주신 방법도 좋은 방법인 것 같아요!!

2022-05-05 08:45 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Person.swift
> +class Person {
요구사항을 따라 구현해보는 방법도 좋은 방법이예요!
어떤게 추가될지 모르는 상황에 다음 스텝으로 넘어가면서 리팩토링을 하는 법도
아주 좋은 연습이 될 수 있답니다 😀

2022-05-05 08:48 UTC, jaemuYeo commented
스텝1 고생많으셨습니다!!
머지 진행하겠습니다 👍

2022-05-05 08:48 UTC, merged