Week4 [Step1] 윤세영
yagom-academy/swift-starter-Round4 pull request #34
Opened 2022-05-06 06:41 UTC by ssyoun4092

@oksunwoo 

ㅎㅎ.. 역시나 이번 스텝도 만만치 않았습니다!

> # 질문사항
(**Error.swift 파일과 같이 보시면 좋을 것 같습니다!**)
+ Excercise.swift 파일에 작성한 Excercise 인스턴스를 보시면 action 클로저에 myBodyCondition을 사용해서 작성하였습니다.
    + 아시다시피 이렇게 코드를 작성하면 myBodyCondition에만 유효하기 때문에 추가적인 BodyCondition타입의 인스턴스를 생성한다면 Excercise 인스턴스를 또 다시 만들어야하는 번거로움이 생깁니다.
    + 따라서 Error.swift파일의 Exercise2 구조체처럼 처음부터 BodyCondition 타입을 매개변수로 받는 타입으로 생성하고자 action 프로퍼티를 수정했습니다.
    + 그리고 새로 Exercise2의 인스턴스를 생성해서 기존에 작성했던 Excercise 프로퍼티처럼 똑같이 인스턴스를 생성했는데 에러가 납니다..
        + "Left side of mutating operator isn't mutable"라는 에러가 뜨는데 이를 구글링해보면 loop문에서 주로 발생하는 에러더라구요..
        + 보시다시피 저는 loop문을 작성안했는데도 위와 같은 에러가 왜 뜨는지 잘 몰라서 이렇게 질문올립니다! (검색 키워드라도 알면 좋겠습니다ㅠ)

> # 코드 설명
## BodyCondition.swift
+ 운동상태들은 끊임없이 변하기에 var로 설정하였습니다!

+ 루틴을 진행했을 때 출력되는 프린트문에서 "상체근력", "하체근력" 등의 값이 필요하여 별도로 배열을 생성하였습니다!

+ 운동을 진행할 때 매번 랜덤숫자를 생성하므로 중복해서 사용할 수 있게 함수로 만들었습니다!

## Routine.swift
+ 루틴의 이름과 루틴 순서는 변하지 않기 때문에 let으로 설정하였습니다!

+ startRoutine 함수를 통해 루틴 이름과 루틴에 속해있는 운동 이름을 순차적으로 출력할 수 있습니다
    + calculateBodyConditionStrength 함수를 통해 bodyCondition 점수(?)를 계산합니다
    + 계산이 다 끝나고, printRoutineNames함수를 통해 운동 이름을 순차적으로 출력합니다!
        + 지금 막 생각난건데 '모든 루틴 운동 점수 계산 ->  운동 이름 출력' 보다 '첫 번째 운동 점수 계산, 첫 번째 운동 이름 출력 -> 두 번째 운동 점수 계산, 두 번째 운동 이름 출력...'의 형태로 함수를 작성하는게 더 좋을 것 같네요!

+ printCurrentBodyCondition 함수를 통해 위에서 계산한 컨디션 점수를 출력하고 있습니다!

2022-05-09 06:51 UTC, oksunwoo requested changes
이번 코드 역시 너무 보기 좋았습니다. 단기간에 어떻게 이럴 수 있는지 신기합니다ㅎㅎ
이번에는 질문사항을 직접 달았네요ㅎㅎ 해당 부분 확인해주시면 될 것 같구요
이번에 각 타입마다 class와 struct 선정이유도 말씀해주시면 좋겠습니다!
몇가지만 수정하면 바로 머지가능 할 것 같네요!
고생하셨어요

2022-05-09 06:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/main.swift
exercise 오타가 있는거같죠?ㅎㅎ

2022-05-09 06:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +}
closedRange라는 생소한 것을 사용하셨는데요!
혹시 이게 무엇일까요?

2022-05-09 06:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/Error.swift
> +*/
해당 부분 오류는 bodyCondition이 immutable 하기 때문이라고 나옵니다.
왜 immutable 할까요? 10번째 라인에 upperBodyStrength를 변경하시려 했을때 immutable 오류가 나서 bodyCondition을 혹시 살피셨었나요? var로 선언을 했는데 왜 변경할 수 없지? 라고 생각하셨을것 같은데요! struct는 값타입, class는 참조타입 이라고 말하면 혹시 힌트가 되실까요? bodyCondition을 한번 클래스로 변경해보시고, 값타입과 참조타입. 그리고 struct와 class에서 값타입과 참조타입에 관해서 간단하게 설명부탁드릴게요!

2022-05-09 07:57 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/main.swift
ㅎㅎ.. 수정했습니다!

2022-05-09 08:00 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +}
closedRange<Int>는 닫힌범위의 Int 값에 대한 타입입니다!
1...10 처럼 1부터 10까지의 닫힌범위를 뜻합니다!

A와 B라는 매개변수를 받아
return Int.random(in: A...B)로 작성할까도 했는데, 한번 새로운 타입을 사용해보고 싶어서 사용해보았습니다!

2022-05-09 10:42 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Error.swift
> +*/
값타입은 기본적으로 복사개념이고, 참조타입은 말 그대로 참조하는 타입입니다.
구조체와 열거형의 값타입의 인스턴스를 생성할 경우, 값을 복사하여 전달하고 클래스와 같이 참조타입의 인스턴스를 생성할 경우 메모리의 위치만 전달해줍니다.

값타입의 프로퍼티는 기본적으로 수정이 어렵지만 수정을 해야한다면 mutating 키워드를 사용해서 수정을 해야합니다.

제가 작성한 코드에서, BodyCondition 타입은 값타입인 구조체로 만들었기 때문에 관련 프로퍼티를 수정할 때 "왜 값타입인데 프로퍼티를 수정하려고 하니?"라는 의미로 에러가 발생하였습니다. 따라서 토니가 조언해주신대로 클래스로 타입을 수정하여 이러한 문제를 해결했습니다!

2022-05-09 10:53 UTC, ssyoun4092 commented
> 각 타입마다 class와 struct 선정이유입니다.

1. BodyCondition
+ 본래 struct로 정의한 이유는 따로 상속할 필요가 없어서 였습니다. 그러나 Exercise 프로퍼티의 매개변수 타입을 BodyCondition으로 받을 때 값타입인 struct로 정의하여 문제가 생겼습니다. 따라서 class로 수정하였습니다.

2. Exercise
+ 마찬가지로 상속할 필요가 없어서 구조체로 생성하였습니다.

3. Routine
+ 이것도... 상속할 필요가 없어서 구조체로 생성하였습니다. 또한 class로 생성하면 이니셜라이저를 별도로 정의해줘야하는데, 구조체는 memberwise 이니셜라이저를 사용하기 때문에 개인적으로 구조체 내부의 코드가 좀 더 깔끔해지는 느낌을 받았습니다.

2022-05-09 11:44 UTC, oksunwoo requested changes
이번에도 고생하셨어요! 
자기 코드에 대한 근거가 있으면 됩니다.
앞으로 class vs struct는 계속해서 코드를 새로 짤때마다 많이 고민하시면 좋겠습니다. 문서도 매번 찾아보시구요!

2022-05-09 11:44 UTC, oksunwoo commented on CodeStarterCamp_Week4/Exercise.swift
>  }
앗 세영님 기본 요구사항은 해당 exercise를 활용해보는 것이니, 이 요구사항은 그대로 가져가볼까요~?

2022-05-09 11:44 UTC, oksunwoo commented on CodeStarterCamp_Week4/Exercise.swift
> +    $0.fatigue += $0.createRandomStrength(between: 10...20)
축약형을 사용해주셨네요! 원형말고 축약형으로 사용하신 이유와 $0가 뜻하는 바가 무엇일까요?

2022-05-09 11:44 UTC, oksunwoo commented on CodeStarterCamp_Week4/Routine.swift
> +    var currentBodyCondition: BodyCondition
클래스로 변경이 되면서 값타입 안에 참조타입을 가진 변수가 생겼네요
음 굉장히 먼이야기라서... 루틴도 클래스가 되면 좋을 것 같아요..
Routine은 자식의 reference를 관리해야 할텐데, 정말 value type으로 존재할 수 있을까에 대해 고민을... 해보고 싶으시면.. 검색해보셔도 좋습니다. 해당부분은 스위프트 참조카운팅으로 키워드 검색하시면 되지만, 꼭 이해하지 않으셔도 됩니다...지금은

2022-05-10 00:45 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Exercise.swift
> +    $0.fatigue += $0.createRandomStrength(between: 10...20)
BodyCondition 타입을 매개변수로 받고, 실행구문을 작성할 때 코드의 길이가 길어지는 단점이 있었습니다. 또한, 매개변수 타입이 하나밖에 없었고, 축약형으로 사용해도 가독성에 크게 문제가 없겠다 싶어서 사용했습니다.

$0는 매개변수 타입의 순서를 뜻합니다! 첫번째로 전달받은 매개변수의 이름을 사용하지 않고, $0로 대체하여 사용하고 있습니다. 두번째로 전달받은 매개변수는 $1이 되고, $2, $3...로 이어집니다.

2022-05-10 00:46 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Exercise.swift
>  }
넵 요구사항 그대로 수정했습니다!

2022-05-10 01:13 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Routine.swift
> +    var currentBodyCondition: BodyCondition
값타입 안에 참조타입의 프로퍼티를 복사하면 어떻게 되는지 찾아봤습니다
결과적으로는 값타입 안에 있더라도, 참조타입의 프로퍼티를 복사하면 참조형태로 복사되는 것을 알 수 있었습니다.

값타입 안에 참조타입 프로퍼티를 정하는 것을 선호하지 않는 정확한 이유는 아직까지 이해할 수 없었으나, 그래도 최대한 제가 공부해 본것만 말씀 드리겠습니다!

구조체, 열거형과 같은 값타입의 인스턴스를 생성하면 'stack'이라는 메모리에 올라갑니다. 여기서 인스턴스를 복사하면 같은 stack 메모리에 복사본이 로드가 되구요. 그러나 참조타입은 다릅니다. 참조타입의 인스턴스를 생성하면 heap 영역의 메모리에 로드가 되고, 이 인스턴스를 참조하는 프로퍼티가 stack 메모리에 로드가됩니다. stack 메모리에 로드가 된 객체는 생성한 인스턴스의 메모리 주소만 가지고 있는 것이고, 이를 다른 객체가 복사하게 되면 메모리 주소만 복사하게 됩니다. 따라서 결과적으로는 같은 메모리 주소를 공유하게 되므로 말 그대로 인스턴스를 '참조'하는 것입니다.

이때 reference Count라는 개념이 등장합니다. 참조횟수라고 번역할 수 있는데, "참조타입의 인스턴스가 몇 번 참조되었냐?"를 계산합니다. 굳이 아무도 해당 인스턴스를 참조하고 있지 않은데 heap 영역의 메모리에 로드가 될 필요가 없으니, 참조횟수를 카운팅하여 참조될때마다+1, 값이 nil이 되는 등 참조가 해제될 때 -1로 계산하여 참조횟수가 0이 되면 이 인스턴스는 메모리에서 해제하게 됩니다. 그리고 이때 실행되는 구문이 deinit입니다. 이러한 참조횟수를 자동으로 카운팅 해주는 시스템이 ARC입니다.

다시 본론으롣 돌아오자면, 구조체는 값타입이기 때문에 reference count에 영향을 받지 않습니다.(참조 자체를 안하기 때문)
그러나 구조체 안에 참조타입의 프로퍼티가 있으면 이 프로퍼티'만' 참조횟수를 카운팅을 해야합니다. 나는 분명 구조체를 사용했는데, 참조횟수가 늘어나는 경우가 생기게 되는 것입니다. 어떻게 보면 코드를 작성할 때 고려해야하는 사항이 더 증가한것이고, 심지어 그런 경우가 많아진다면 내가 지금 사용하는 프로퍼티가 값타입인지, 참조타입인지 기억하기도 힘들 뿐더러, 참조횟수 관리는 더욱 어려울 것입니다. 결국 메모리 누수로 이어질 여지가 있다고 생각합니다. 토니 말씀처럼, 차라리 참조타입의 프로퍼티가 필요하다면 클래스 타입으로 정의하고, 구조체 안에서는 값타입의 프로퍼티만 갖는 것이 훨씬 안전하게 코드를 작성할 수 있다고 생각했습니다.

+ 혹시라도 제가 잘못 알고 있는 부분이 있다면 꼭 알려주시면 감사하겠습니다!!

2022-05-10 01:20 UTC, ssyoun4092 commented
요구사항을 그대로 반영한다는 의미를 Exercise 구조체에서 let action () -> Void 프로퍼티를 그대로 사용하라고 이해했습니다.
따라서 매개변수 타입이 사라졌고, BodyCondition도 굳이 클래스타입으로 사용할 이유가 없어서 다시 구조체로 변경하였습니다!

2022-05-10 06:52 UTC, merged