Week4 [STEP2] jeongmin(정민)
yagom-academy/swift-starter-Round4 pull request #35
Opened 2022-05-06 09:15 UTC by jeongmin-l

@jaemuYeo 
안녕하세요 잼킹!
4주차 STEP2 PR 드립니다
정말 만만치 않았던 것 같아요... 머리가 아프네요
어찌어찌 구현은 한 것 같긴한데 버그가 있는지 체크도 했지만 혹시 또 있을까봐 불안불안 하네요 😭
이 코드가 가독성이 더 좋아지고 구조가 더 간결해 지기 위해서는 어디를 리팩토링 해야할까요?

저번 스텝1과 똑같은 부분은 설명을 제외했습니다!
# 코드설명
+ **FitnessCenter타입**
+ **Person타입**
+ **Error타입**
+ **Hangeul.......**

# FitnessCenter
## 프로퍼티
+ targetBodyCondition : 목표 컨디션
+ member : 회원
+ routineList : 루틴목록

## 메서드
+ register : 피트니스 회원등록 메서드
  + enterName : 회원등록 중 이름을 등록하는 메서드
  + setTargetCondition : 목표 컨디션 설정 메서드
<br>

## 메서드 설명
## **register**
`do catch` 문으로 이루어져 있고 두 가지 메서드(`enterName`, `setTargetCondition`)을 실행합니다.
회원등록, 목표 컨디션 설정 시에 발생할 수 있는 에러의 처리를 하고 에러가 발생하면 프로그램을 종료합니다.

### enterName
`readLine()` 메서드 사용시 인식할 수 없는 값이 들어오면 `unReconizedInputError`를 발생시킵니다.
이후 에러가 발생하지 않으면 `Person` 타입의 인스턴스를 생성해서 `member` 변수에 할당합니다.

### setTargetCondition
목표 컨디션을 설정하는 값을 받을 때 먼저 인식되는 값인지 에러 체크를 하고
`Int`로 변환시에 오류가 생기는 값들은 
`ErrorValue.stringToIntConvertErrorValue`라고 지정해둔 값을 반환합니다. 
그 값이 들어가 있는지 판단한 후 들어가 있다면 `stringToIntConvertError` 를 throw 합니다.

split해서 array타입으로 반환을 했기 때문에 값의 count가 적절한지 판단합니다.
3개의 값이라면 정상, 아니라면 적절하지 않은 값이라는 `invalidNumberOfValuesError`를 발생시킵니다.
이후 목표 컨디션에 값들을 설정해줍니다.

+ workOut : 피트니스 운동실행 메서드
  + checkExistMember : 회원이 존재하는지 확인하는 메서드
  + selectRoutine : 루틴을 선택하는 메서드
  + selectRepeat : 반복횟수를 선택하는 메서드
  + checkMemberExhausted : 회원의 탈진여부를 확인하는 메서드
  + checkEnoughForTarget : 회원의 컨디션이 목표에 충분한지 확인하는 메서드

## **workOut**
먼저 옵셔널 타입인 `member`를 많이 사용하기 때문에 guard let으로 언래핑 합니다.
회원이 존재하는지 `checkExistMember`로 판단하고 루틴과 반복횟수를 골라
`member.excise(for:,routine)`을 실행합니다 운동 이후 회원이 지쳤는지 달성했는지 판단 후
달성했다면 컨디션을 출력합니다.
 
위에 설명한 에러 외에 추가된 다른 에러는
회원이 존재하지 않으면 발생하는 `notExistMemberError` 에러, 
회원이 피로도가 높아 탈진하면 발생하는 `exhaustedMemberError` 에러,
목표 컨디션에 도달하지 못하면 발생하는 `notEnoughToTargetError` 에러,
이렇게 3가지 인데 `exhaustedMemberError`는 회원이 도망간 것을 표현하기 위해 nil을 주었고 
목표 컨디션에 도달하지 못하면 발생하는 에러는 프로그램을 종료하지 않고 
현재 컨디션을 보여준 뒤 workOut 메서드를 다시 실행합니다.

### checkExistMember
회원이 존재하지 않으면 `notExistMemberError` 에러를 발생시킵니다.

### selectRoutine
루틴의 번호를 입력받아 -1 한 인덱스 값을 반환합니다. 발생하는 에러는 위의 setTargetCondition 과 비슷하지만
값을 한개만 받기 때문에 값의 갯수 에러가 없습니다 

### selectRepeat
반복횟수를 받아 인식 가능한 값인지 판단하고 정수로 변환해서 반복횟수를 반환합니다.

### checkMemberExhausted
회원의 피로도가 100초과라면 `exhaustedMemberError`에러를 발생시킵니다.

### checkEnoughForTarget
회원의 상체근력, 하체근력, 근지구력이 모두 목표에 도달하지 못하면 `notEnoughToTargetError`에러를 발생시킵니다.

# Error
+ unRecognizedInputError :  인식할 수 없는 값 에러
+ stringToIntConvertError : 문자열에서 정수로 변환 에러
+ invalidNumberOfValuesError : 유효하지 않은 갯수 에러
+ notExistMemberError : 존재하지 않는 회원 에러 
+ exhaustedMemberError : 회원 탈진 에러
+ notEnoughToTargetError : 회원 목표달성 실패 에러

6가지의 에러를 열거 합니다.
ErrorValue의 열거형은 의미없는 값인 -1 에 이름을 붙여 에러 값을 표현합니다.

# Hangeul
readLine() 메서드를 사용할 때 한글이 분리되는 현상 해결이 안되어서 주먹구구식으로 만든 메서드입니다....
원,권 같은 모음,자음,자음,모음을 찾아내지 못하는 버그가 있는데 고치질 못했고 
일단 제 이름과 김철수만 가능하게 구현해봤습니다.

2022-05-08 09:24 UTC, jaemuYeo requested changes
정민님 스텝2도 고생많으셨습니다!!
전체적으로 코드를 많이 고민해서 구현하신게 느껴졌어요!
인터페이스 함수와 이 함수를 구현하기 위한 은닉화된 함수의 나열도
잘 구성되어 있어서 코드를 이해하기도 편했어요 👏👍
그만큼 함수의 기능 분리도 잘 하신 것 같습니다!!
에러는 던지는 함수와 받는 함수의 구분도 좋습니다.
코드의 컨벤션이나 네이밍도 초반보다 훨씬 좋아진 것 같아요~

몇 가지 코멘트를 통해 남겨놓았습니다!
아마 수정을 해야한다면 에러를 처리하는 과정이 될텐데요!
강제 종료가 난무하고 있어서 실행해보면서 값을 잘 못 입력하면 다시 실행해야하는
불편함들이 있었어요!! 조금 더 고민해보시고 에러처리에 대한 부분을 수정해보시면 좋을 것 같아요😀

2022-05-08 09:24 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var member: Person? = nil
기본값으로 nil을 할당해주지 않아도 값이 없다면 nil을 반환 할 것으로 생각되네요 😀

2022-05-08 09:24 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        } catch FitnessCenterContingency.unRecognizedInputError {
에러처리에 대한 부분은 이 곳에서 한번에 코멘트 드리겠습니다!
일단 exit함수로 에러가 발생할때 전부 강제종료로 처리했군요!!
키오스크로 예를 들어볼게요~
만약 손님이 주문을 하다가 적립번호를 잘못 입력해서 강제종료가 되고
재부팅 후 처음부터 다시 주문을 해야한다면 불편하겠죠?
무엇이 잘 못되었는지 사용자에게 알려주고 다시 시도할 수 있게 해준다면 좋을 것 같아요😉

2022-05-08 09:24 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            print("""
여러 줄 프린트 할 때 지금과 같은 형태보다 
```swift
print("""
      --------------
      성공입니다! 현재 \(member.name)님의 컨디션은 다음과 같습니다.
      """)
```
이런 형태가 가독성이 더 좋을 것 같아요 😀

2022-05-08 09:24 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Error.swift
> +enum FitnessCenterContingency: Error {
여러가지 종류의 에러케이스들을 만드셨군요 👍
에러를 받는 곳에 print를 통해 메시지를 전달하지 않고,
이 곳에서 에러와 메시지를 같이 처리하면 어떨까요?
`LocalizedError`를 통해 구현해보면 좋을 것 같아요!!
[참고자료](https://velog.io/@wonhee010/Enum%EA%B3%BC-Error%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC)이 외에 부족한 부분을 더 찾아보시고 시도해보시길 바라요☺️
LocalizedError를 사용한다면 코드의 간결함과 가독성도 한결 좋아질 것 같아요!

2022-05-08 09:24 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var targetBodyCondition: BodyCondition = BodyCondition()
타입을 꼭 명시하지 않아도 해당 변수가 BodyCondition타입 인스턴스인 것을 알 수 있을 것 같아요!

2022-05-08 09:24 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            workOut()
재귀함수를 사용하셨군요 👍

2022-05-08 09:24 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +
불필요한 개행이군요!

2022-05-08 21:42 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var member: Person? = nil
바로 수정하겠습니다!!

2022-05-08 21:51 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            print("""
동의합니다 수정해서 반영하겠습니다 😊

2022-05-09 00:49 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        } catch FitnessCenterContingency.unRecognizedInputError {
이해했습니다!! 다만 루틴을 선택하고 반복횟수를 선택하다가 오류가 났을 때 반복횟수를 다시 입력하는 방향으로 하고 싶은데
루틴을 선택하는 메서드 내부에 반복횟수를 선택하는 메서드를 두어서 하려고 하니 반복횟수 선택 메서드도 do-catch문의 지옥에 빠질 것 같습니다 더 간결한 좋은 방법이 없을까요 😢

2022-05-09 00:49 UTC, jeongmin-l commented on CodeStarterCamp_Week4/Error.swift
> +enum FitnessCenterContingency: Error {
LocalizedError 공부해서 시도해보았습니다!!

2022-05-09 00:50 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            workOut()
감사합니다 😁

2022-05-09 00:50 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var targetBodyCondition: BodyCondition = BodyCondition()
수정하였습니다 ☺️

2022-05-09 00:50 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +
늘 하나씩 나오는 그것... 수정하였습니다! 😅

2022-05-09 15:20 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        } catch FitnessCenterContingency.unRecognizedInputError {
try?와 try!를 사용해보시면 어떨까요? 느낌표는 피해주세요 ㅎㅎ

2022-05-09 16:05 UTC, jaemuYeo requested changes
안녕하세요 정민님 🙂
몇 가지 코멘트와 동작에서 문제가 있는 부분을 적어보았습니다!!
그리고 한 가지 궁금한건 피로도 Max값을 100으로 설정해두셨는데
세트를 반복하다가 100에 도달하면 세트 반복을 끊어야 할텐데
만약 수 많은 세트 수를 입력하면 회원의 피로도가 몇 천 몇 만 까지도 올라가네요 ㅎㅎ
해결해 볼 수 있을까요?

2022-05-09 16:05 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var routineList: [Routine]
이 아이는 let으로 해도 문제 없을 것 같네요 🤔

2022-05-09 16:05 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            member!.exercise(for: setsOfExercise, routine: routineList[indexOfRoutine])
몇 번째 루틴으로 할지 입력할 때에 1또는2가 아닌 다른 값을 입력해도 몇 세트 반복하시겠어요?라는 문구가 출력되고,
그 다음 입력은 크래시가 발생하네요! 
에러의 원인은 `Index out of range`인 것 같아요.

---

여기를 포함한 아래 부분에 옵셔널 강제추출을 사용하였는데 애플에서는 !를 지양하고 있어요.
그 이유에 대해 한번 알아보셔도 좋을 것 같아요😀

2022-05-09 16:05 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Error.swift
> +extension FitnessCenterContingency: LocalizedError {
LocalizedError를 활용하셨군요 👍
제가 생각하기에 조건을 통해서 처리할 수 있는 부분까지 에러로 묶어서 너무 많은 케이스가있는 것은 아닌가
생각도 들어요!
에러 케이스는 유저가 값을 입력하는 과정에서만 발생해도 될 것 같다고 생각합니다.
정민님의 생각은 어떠신가요?

2022-05-10 02:45 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var routineList: [Routine]
let으로 수정했습니다! 😄

2022-05-10 02:48 UTC, jeongmin-l commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            member!.exercise(for: setsOfExercise, routine: routineList[indexOfRoutine])
루틴의 갯수 이하의 값만 받도록 수정했습니다!
지양하는 이유를 공부했는데 강제언래핑을 지양하는 이유는 어디서 충돌이 났는지 구분을 확실하게 하기 위함이군요!
저도 지양해서 쓰도록 하겠습니다

2022-05-10 02:50 UTC, jeongmin-l commented on CodeStarterCamp_Week4/Error.swift
> +extension FitnessCenterContingency: LocalizedError {
요구사항대로 구현해봐야지! 했던 생각에 case로 처리하는게 아니라 조건을 통해서 처리하는 생각을 못했습니다😭

2022-05-10 03:00 UTC, jeongmin-l commented
에러가 나면 에러가 난 위치에서 다시 실행을 하도록 try? try! 를 사용해서 해결해보고 싶었는데 해결이 잘 되지 않았습니다 😭
그래서 최대한 제가 해결해볼 수 있는 방안으로 해결을 해 보았습니다

2022-05-10 09:31 UTC, jaemuYeo commented
안녕하셍요 정민님!!! week4도 고생많으셨습니다👏
제가 발견했던 에러에 대해서는 잘 처리해주신 것 같아요!!
로직에 대한 부분은 다음 프로젝트를 위해 코멘트를 따로 남기지 않았지만 
더 다양한 방시으로 표현하실 수 있으실 거라 믿어요👍

이번 스텝에서 마지막 꿀팁대방출을 하며 머지 진행하겠습니다!
계속 해결하지 못했던 do-catch의 늪에 대해서 입니다.
```swift
func register() {
        if (try? enterName()) != nil {
            var isRetry = true
            while isRetry {
                do {
                    try setTargetCondition()
                    isRetry = false
                } catch let error {
                    print("\(error.localizedDescription)")
                }
            }
        } else {
            if let errorDescription = FitnessCenterContingency.unRecognizedInputError.errorDescription {
                print(errorDescription)
            }
            register()
        }
    }
```

정민님의 코드 일부를 수정해보았는데요. 차이점이 보이시나요?
이전에 LocalizedError를 통해 에러의 Description을 정의하고,
에러를 받는 곳에서 [localizedDescription](https://developer.apple.com/documentation/foundation/nserror/1414418-localizeddescription)을 통해 에러가 발생하는 부분에 대해 정민님이 구현하신 에러문구를 프린트해주고있어요.
이 것이 LocalizedError을 사용한 이유랍니다 😀
조금은 도움이 되셨을지 모르겠습니다!! 
마지막 주차도 화이팅하세요 💪

2022-05-10 09:31 UTC, merged