Week 4 [STEP 1] Oh Sung Ah
yagom-academy/swift-starter-Round4 pull request #36
Opened 2022-05-06 10:00 UTC by delight010

@jaemuYeo 
안녕하세요 잼킹~

클로저에 익숙하지않아서 많이 헤맸어요
사용해본 적이 없는 함수 forEach도 공부해서 적용해보았습니다!
인스턴스 생성 후 직접 사용할 일이 없는 currentCondition은 private로 바꿔보았어요!

2022-05-08 10:19 UTC, jaemuYeo requested changes
성아님 안녕하세요 😀
전체적으로 요구사항에 맞게 잘 구현해주신 것 같아요~
제 몇 가지 생각들을 코멘트를 통해 남겨놓았으니 수정이 필요하다면 수정 후 재PR주시고,
이대로 진행해도 되겠다 생각하시면 머지 진행하도록 하겠습니다!
은닉화도 정말 잘 하셨어요 👍

2022-05-08 10:19 UTC, jaemuYeo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var name: String
BodyCondition타입에 name이라는 프로퍼티가 있는 것이 어색하다 생각이 드네요!!🤔

2022-05-08 10:19 UTC, jaemuYeo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var upperBodyStrength: Int // 상체근력
주석 없이 네이밍 만으로도 충분히 설명이 될 것 같아요! 불필요한 주석이라 생각합니다!

2022-05-08 10:19 UTC, jaemuYeo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        routine.exercises.forEach {
forEach 를 적절하게 잘 상요해주신 것 같아요! 👏👍

2022-05-08 10:19 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Exercise.swift
> +struct Exercise {
이 두 객체는 따로 파일을 분리하지 않은 이유가 있으신가요?

2022-05-08 10:19 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +let 윗몸일으키기: Exercise = Exercise(name: "윗몸일으키기",
예제처럼 한글로 변수명을 사용하셨군요!! 
저는 코드에 한글 사용을 지양하는 편입니다 😀
한글 사용의 안 좋은 점에대해서 알아보셔도 좋을 것 같아요!

2022-05-08 10:19 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +    person.upperBodyStrength += Int.random(in: 10...20)
아래를 포함해서 범위 중 중복되는 것들도 몇 가지 보이는군요!
범위의 값을 구조체에 static 상수로 보관한다던가
Int의 Extension을 통해 구현하여 사용해보면 어떨까요??
필수 사항은 아닙니다! 참고만 해주세요!😀

2022-05-08 10:19 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +kimYuna.exercise(routine: hellRoutine)
kimYuna, SongGain 상수를 먼저 작성 후 호출부를 뒤에 함께 작성하는 것이 더 가독성이 좋을 것 같아요🙂

2022-05-08 15:09 UTC, delight010 commented on CodeStarterCamp_Week4/Exercise.swift
> +struct Exercise {
class Routine안에 Exercise가 포함되어있어서 연관되어있는 타입들이기때문에.
따로 분리는 하지않았습니다~

2022-05-08 15:14 UTC, delight010 commented
@jaemuYeo 
예제에 Exercise 변수명이 한글로 되어있어서 그대로 해봤는 데. 한글로 명명해도 실행이 잘되서 신기했어요. 왠만하면 영어, 숫자, _ 로 구성하는걸 권장하는 건 알고있습니다!
BodyCondition의 name 프로퍼티는 출력할 때 이름이 필요해서 넣게되었습니다.

2022-05-09 09:20 UTC, jaemuYeo commented
스텝1 고생하셨습니다!! 머지 진행할게요! 
마지막 주도 화이팅입니다 💪
스텝2의 회원이름을 출력하는 부분에서 readLine() 함수에 한글을 입력하면 자소분리가 되는 이슈가 있는데
예시) 회원이름 잼킹 입력 -> ㅈㅐㅁㅋㅣㅇ님의 피로도가 140입니다. 회원님이 도망갔습니다.
그 부분은 한글대신 영어로 입력하셔도 됩니다!

2022-05-09 09:20 UTC, merged