Week4 [step1] duck
yagom-academy/swift-starter-Round4 pull request #37
Opened 2022-05-07 05:15 UTC by Hong-seungju

@llghdud921 
안녕하세요 제리~~
Week4 [step1] 입니다.
즐거운 가정의달 보내세요~~

2022-05-08 16:39 UTC, llghdud921 requested changes
안녕하세요!! duck
duck도 즐거운 가정의달 보내시길 바래요ㅎㅎ

클로저에 대한 이해도 높으시고 코드 구성도 굉장히 잘하셔서 간단한 코멘트 드렸습니다! 
확인 부탁드릴게요~~

2022-05-08 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/Exercise.swift
> +    person.fatigue -= Int.random(in: 5...10)
피로도가 마이너스가 될수도 있는 로직이에요!!! 수정해볼까요!!

2022-05-08 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/Exercise.swift
> +let yoga: Exercise = Exercise(name: "요가") {
추가동작 굿굿

2022-05-08 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/Routine.swift
> +        print("hellRoutine을 시작합니다.")
이부분은 routineName을 출력하는 것 같아요!! 개선해볼까요?

2022-05-08 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/main.swift
> +var aa = Routine(routineName: "hellroutine", exercises: exercise)
루틴이름이 aa라니......ㅠㅠㅠ 네이밍 별표 백개입니당

2022-05-08 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        print("피로도: \(fatigue)")
여러개의 print문을 사용하는 것을 하나의 print로 처리할 수도 있습니다!
[Multiline String Literals](https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html#ID286)를 참고해보세요 :)

2022-05-09 01:46 UTC, Hong-seungju commented on CodeStarterCamp_Week4/Exercise.swift
> +    person.fatigue -= Int.random(in: 5...10)
넵 수정하겠습니다!

2022-05-09 01:47 UTC, Hong-seungju commented on CodeStarterCamp_Week4/Routine.swift
> +        print("hellRoutine을 시작합니다.")
startRoutine의 네이밍을 개선하면 되는 건가요...??

2022-05-09 01:48 UTC, Hong-seungju commented on CodeStarterCamp_Week4/main.swift
> +var aa = Routine(routineName: "hellroutine", exercises: exercise)
아.. 테스트를 빨리 해본다는게 깜빡하고 다시 네이밍을 변경을 안했네요...
수정하겠습니다.

2022-05-09 01:48 UTC, Hong-seungju commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        print("피로도: \(fatigue)")
넵 수정하겠습니다.

2022-05-09 10:09 UTC, Hong-seungju commented
@llghdud921  안녕하세요 제리 Week4 [step1] 수정본 입니다.

2022-05-09 15:14 UTC, llghdud921 commented on CodeStarterCamp_Week4/Routine.swift
> +        print("hellRoutine을 시작합니다.")
```suggestion
        print("\(routineName)을 시작합니다.")
```
이러한 로직으로 구성될수도 있다는 말이었어요!! 이부분은 크게 중요하지 않으니 넘어갑시당~

2022-05-09 15:14 UTC, llghdud921 commented
이번 코드 구성을 굉장히 잘해주셔서 더 수정될 부분은 없어보이네요!!! 머지하고 다음 스텝으로 넘어갑시다~~

2022-05-09 15:14 UTC, merged