Week4 [Step 2] dooly
yagom-academy/swift-starter-Round4 pull request #38
Opened 2022-05-07 17:14 UTC by yuvinrho

@leeari95 

# Step2

## 사용자 입력 받는 함수 정의
1. inputToString : 사용자 입력을 받아 String으로 반환합니다.(피트니스 센터 회원 이름 입력하기 위함) 빈문자열, 공백포함, 문자가 아닌경우 InvaildInputValue 에러를 던집니다.
2. inputToInt : 사용자 입력을 Int로 반환합니다.(운동 목표치 설정, 루틴 리스트에 있는 루틴선택) 에러가 발생하면 InvaildInputValue를 던집니다.

## Person 구조체
1. exercise 메소드. 매개변수로 세트 수, 루틴종류, 피로도 한계가 들어갑니다.
2. 루틴 종류에 따른 운동을 세트 수 반큼 반복합니다. 운동을 한 번 할때 마다 내 몸의 피로도와 피로도 한계를 비교하고, 피로도가 한계 피로도를 넘으면 runAway()메소드를 실행하여 도망갑니다.
3. runAway() 메소드 : 메소드가 실행되면 FitnessCenterError.Overfatigue 에러를 던집니다.

## FitnessCenter 구조체
- runFitnessCenter 메소드 : 피트니스 센터 회원 가입 메소드, 바디컨디션 목표설정 메소드, 루틴리스트에 있는 루틴 선택 메소드, 세트횟수를 입력는 메소드, 루틴을 시작하는 메소드,  운동이 끝나면 회원 바디컨디션 결과를 출력하는 메소드를 실행합니다.
- 각 메소드에 대해 에러가 발생할 경우 에러를 처리합니다.

### 에러 핸들링 부분 왜이렇게 어려운지ㅠㅠ 고치고 지우고 난리가 아니네요ㅠㅠ 사용자 입력받는데 이상한 값이 들어오지 않도록 나름대로 에러처리 해보았고 다른 메소드 들도 에러처리해보았는데 맞게 한걸까요?..또 수정한 것도 많아서 커밋이 어느순간 30개가 되어버렸는데 이렇게 많아도 괜찮은 걸까요??..

2022-05-08 05:07 UTC, leeari95 requested changes
둘리 안녕하세요! 🤗
이번 스텝도 정말 잘 구현해주셨네요.
커밋 이력과 적어주신 설명 덕에 코드를 이해하는데 너무 수월했어요.

커밋 이력이 많아져서 걱정이신 것 같은데, 전혀 걱정하지 않으셔도 됩니다!

에러처리를 꼼꼼히 해주시기 위해 노력하신 모습이 정말 멋져요!! 👍🏻
타입 구현도 잘해주셨고, 요구사항대로 잘 동작하고 있는 듯 보여요.

자세한건 몇가지 코멘트들을 남겨보았어요. 확인해주시고 수정이 완료된다면 재리뷰 요청 주세요!
이번 스텝도 고생 많으셨습니다 😊

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +    }
이 guard문은 같은 에러를 던지고 있네요.
묶어볼 수 있을 것 같아요.

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +    return input
문자인지 확인하는 과정같은데, 숫자가 들어가면 안될까요?
이러한 조건을 설정해주신 이유가 궁금합니다 🤔

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +    }
이 guard문도 합쳐보면 좋을 것 같아요!

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +    }
ㅋㅋㅋ 트라이 런어웨이... 코드가 너무 재밌네요 ㅋㅋㅋ😂
읽다가 빵터졌어요 ㅋㅋㅋㅋ

바로 에러를 던져주지 않고 이렇게 별도의 함수로 빼주신 이유가 무엇인가요? 😊

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +            print("입력값 오류.")
입력을 잘못했다면 다시 처음 메뉴로 돌아가야 하는게 맞지 않을까요?
입력을 잘못하니까 그대로 프로그램이 종료되버리네요!

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +        }
피트니스 멤버가 없는 경우는 어떤 경우인가요?

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +            print("센터에 회원이 없습니다.")
센터에 회원이 없는 경우에도 프로그램이 종료되겠네요!

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +            self.runFitnessCenter()
재귀함수를 사용해보셨네요!?
while문과 재귀함수는 어떤 차이가 있을까요?

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +            }
이 부분은 Routine 타입에 이미 메소드로 기능을 구현하시지 않으셨나요?
따로 분리가 필요해보여요!

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +        }
오.. 루틴을 출력하는 부분을 enumerated 메소드를 활용해서 구현해보셨네요.
새로운 루틴을 추가해도 걱정 없겠어요. 최고!! 👍🏻

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +        }
루틴이 존재하지 않다는 오류가 적절하지 않을까요?
잘못된 입력은 이미 inputToInt 메소드 내부에서 던져주고 여기까지 못오지 않을까... 하는 생각이 들어요 🤔

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +        }
여기서 멤버를 옵셔널 바인딩 처리 해주는 이유가 무엇인가요?

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +yagomFitnessCenter.runFitnessCenter()
실행 코드도 함수로 묶어보는 것은 어떠세요?
위에 처럼 주석처리 안해도 될 것 같아요 🤗

2022-05-08 05:07 UTC, leeari95 commented on CodeStarterCamp_Week4/main.swift
> +}
나중에 시간적 여유가 되신다면 [LocalizedError](https://developer.apple.com/documentation/foundation/localizederror)에 대해서도 알아보시면 좋을 것 같아요 🤗

2022-05-08 06:02 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    }
아하~~ 왜 저는 묶을 생각을 못했는지ㅋㅋㅋㅋ 알려주셔서 감사합니다!!

2022-05-08 06:07 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    return input
멤버 이름을 입력받기 위해서만 사용하기 때문에 숫자는 못들어가게 제한을 걸어두었습니다~

2022-05-08 06:50 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    }
감사합니다~~ 수정하였습니다!

2022-05-08 13:48 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +    }
ㅋㅋㅋㅋ사람이 도망가는 행위를 하는 것이기 때문에 도망치는 메소드를 만들어서 에러를 던지게 하고 싶었습니다ㅎㅎ

2022-05-09 16:15 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +            print("입력값 오류.")
어떻게 이걸 해결할까 정말 많이 고민했습니다ㅠㅠ이거에 대한 제 결론은 runFitnessCenter() 메소드에서 do-catch를 하니 프로그램이 종료되니깐 사용자 입력이 필요한 각 함수에서 while로 무한 반복을 하여  do-catch 를 하게 하였고, 에러가 발생하지 않으면 do 맨끝에 break키워드로 탈출하게 하였는데 다른 좋은 방법이 있으면 힌트 부탁드립니다ㅠㅠ

2022-05-09 16:18 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +            print("센터에 회원이 없습니다.")
수정하였습니다~~

2022-05-09 16:19 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +            }
Routine타입에 구현해놓은 메소드를 사용하게 수정하였습니다~~

2022-05-09 16:27 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +        }
문제 요구조건에 루틴을 진행할 회원이 없는 경우 에러처리하라고는 되어있어서 추가해놓기는 했는데 사실.... 멤버가 없는 경우에 에러처리는 어떤 흐름에 추가를 해야되는지 잘 모르겠습니다ㅠㅠ 처음 프로그램 시작하면 member인스턴스가 생기고, 멤버가 한계피로도를 넘으면 도망가면서 프로그램이 종료되어서 딱히 멤버가 없는 경우가 있을까라는 생각이 듭니다. 혹시 어디에 에러처리를 추가했으면 좋겠다 하는 의견있으시면 소곤소곤 힌트주시면 감사드리겠습니다ㅎㅎ

2022-05-09 16:34 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +            self.runFitnessCenter()
while은 조건이 false일때까지 반복하고 몇번을 반복하는지 모를때 사용하고 재귀는 함수에서 내 자신을 다시 호출할때 사용하는 것이라고 알고있고 차이는 while은 빠르고 재귀는 느리다? 사용자가 보기 직관적이다?? 이정도로만 알고있습니다ㅠ 재귀를 사용한 이유는 루틴 후 목표치에 도달하지 못했을 때 다시 함수 처음으로 돌아가서 함수를 반복하려고 했는데 이때당시 while로 어떻게 처리해야 해야하고 에러 핸들링은 어디함수에서 해야할지 머리가 뜨근해지고 아이디어가 막상 떠오르지 않아서 재귀로 처리했습니다ㅠㅠ 지금은  각 함수에 while로 옳바른 사용자 입력이 들어올 때 까지 모두 수정해놓았습니다~

2022-05-09 16:34 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +        }
감사합니다ㅎㅎ

2022-05-09 16:37 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +        }
InvaildRoutine이라는 에러를 추가하여 루틴이 존재하지 않을경우를 추가하였습니다~~

2022-05-09 16:41 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +        }
xcode에서 노랑색 에러가 발생해서...보기 싫어서.. 옵셔널바인딩으로 에러를 없애주었습니다ㅠㅠ 그런데 여기까지 와서 멤버가 중간에 사라지거나 하는 경우로 멤버 옵셔널을 확인할 필요는 따로 없을것 같아서 !로 수정하였습니다~

2022-05-09 16:42 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +yagomFitnessCenter.runFitnessCenter()
알려주셔서 감사합니다ㅎㅎ runStep2() 함수를 생성하여 묶어주었습니다~~

2022-05-09 16:43 UTC, yuvinrho commented on CodeStarterCamp_Week4/main.swift
> +}
감사합니다~~ LocalizedError에 대해서 알아보겠습니다~~

2022-05-10 00:40 UTC, leeari95 approved these changes
둘리~ 수정사항 잘 확인했습니다!😁

제가 질문드리는 부분이나 드리는 의견은 모두 틀려서 드리는 것 보다는
잘 알고계신지, 혹은 궁금해서 여쭤보는 것이 대부분이랍니다.

또 자신만의 논리가 있고, 납득이 된다면 수정하지 않아도 된다고 봅니다!
항상 자신만의 논리를 가지고 코드를 작성하셨으면 좋겠네요!

그리고 수정해주신 부분중에 do-catch문을 여러번 사용해주셨는데,
do-catch는 언제써야하는지 다시 고민해보셨으면 좋겠습니다.
던져주기만하고 최종적으로 사용하는 곳에서 한꺼번에 에러처리를 해볼 수도 있을 것 같아요. (제 생각ㅎ)
다시한번 do-try-catch문을 복기해보셨으면 좋겠어요!! 💪🏻

큰 문제없고, 정상적으로 작동하는 것 확인했고, 머지해드리겠습니다!
고생하셨습니다~ 😊

2022-05-10 00:41 UTC, merged