Week4 [Step 1] som
yagom-academy/swift-starter-Round4 pull request #40
Opened 2022-05-08 05:13 UTC by jsa0224

@Jager-yoo 

벌써 일요일이네요...🥲 다음 주면 캠프가 끝나다니 아쉬워요😩

- 고민했던 부분
다른 주차의 과제보다는 고민을 덜 했던 것 같아요. 
클로저 문법이 바로 이해되기도 했고, 코드의 간결성으로 프로그래밍하는 동안 재밌었던 거 같아요😆
고민이라 함은... 저는 운동에 진심이어서 어떤 운동을 넣을까 고민했던 거 같아요 ㅎㅎ

- 부족했던 부분
헬스 루틴으로 할 운동을 배열에 넣어서 호출하도록 만들었는데요.
보통은 `윗몸 일으키기 3세트` 라고 하지 `윗몸일으키기, 윗몸일으키기, 윗몸일으키기` 이렇게 말하지는 않잖아요.
배열에 그대로 넣고 그대로 호출되니까 호출문이 간결하지 않은 느낌이에요.
제가 부족했다고 느낀 부분을 다음 스텝에서 해결하도록 과제를 주셔서 일단 고민을 멈추고 PR을 보내봅니다!

2022-05-08 07:32 UTC, Jager-yoo requested changes

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    func checkYourCondition() {
이니셜라이저와 메서드 사이에 `공백 엔터` 하나 들어가면 좋겠네요!

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    }
BodyCondition 타입 구현 정말 깔끔하게 잘 해주셨어요! 👏🏻 

하나 팁을 드리자면, 조금 심플한 버전의 이니셜라이저도 만들 수 있을 것 같아요.

만약 모든 사람들의 BodyCondition 이 `항상 0 부터 시작`한다면...
매번 이니셜라이징 할 때 숫자 0 을 넣어주기 불편할 수 있잖아요? 실수할 수도 있구요. 😄

```swift
// 이니셜라이저(생성자)를 하나 더 만드는데, 파라미터로 시작 숫자만 받아서, 내부에서 전부 프로퍼티에 집어 넣는 형태
init(startingPoint: Int) {
    self.upperBodyStrength = startingPoint
    self.lowerBodyStrength = startingPoint
    self.muscularEndurance = startingPoint
    self.fatigue = startingPoint
}
```

이런 식으로, 이니셜라이저를 사용하기 편하게, 추가로 만드는 방법도 있어요. 😄 
그러면 인스턴스를 생성할 때, 하나의 숫자로 전부 동일하게 시작할지, 혹은 몸의 상태를 제각각 숫자를 넣어서 시작할 지, `선택권`이 생기게 되죠!

<img width="954" alt="image" src="https://user-images.githubusercontent.com/71127966/167285846-c3433574-ccb8-47b9-b41d-d67b8aa6617a.png">

만약 `0`으로 시작하는 거라면, 새로 만든 이니셜라이저를 사용하면 코드 양이 절반이 됩니다! 👍🏻 

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/71127966/167285904-c207c60e-8eb7-4f2c-ad7f-620c95ddf8d9.png">

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Exercise.swift
> +}
여기 `액션` 프로퍼티는 왜 `var`로 선언하신 걸까요?
왜냐면 `let`으로 바꿔도 잘 작동하더라구요. 😄 

액션에서 해주는 운동들을, 런타임(프로그램이 돌아가는 도중)에 변경하는 게 아니라면
`상수(let)`로 생성해주는 게 더 자연스러워 보입니다!

그리고 13번째 줄은 굳이 비워둘 필요 없을 것 같아요!

```swift
struct Exercise {
        let name: String
        let action: () -> Void
}
```

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Exercise.swift
> +})
메서드의 마지막 파라미터가 클로저라면, `후행 클로저(trailing closure)` 문법을 적용할 수 있습니다.

## [공식 문서 - Trailing Closures](https://docs.swift.org/swift-book/LanguageGuide/Closures.html#ID102) 부분을 확인해보세요! 😄 

![image](https://user-images.githubusercontent.com/71127966/166621058-6ddcfde1-83d0-46eb-be95-51d1118c4ac7.png)

- 아래 코드 처럼, 좀 더 깔끔한 코드로 수정해볼 수 있겠습니다. 👍🏻 

```swift
// 상체운동
let sitUp = Exercise(name: "윗몸일으키기") {
    person.upperBodyStrength += Int.random(in: 10...20)
    person.fatigue += Int.random(in: 10...20)
}

let deadLift = Exercise(name: "데드리프트") {
    person.upperBodyStrength += Int.random(in: 10...20)
    person.lowerBodyStrength += Int.random(in: 5...10)
}

let plank = Exercise(name: "플랭크") {
    person.upperBodyStrength += Int.random(in: 10...20)
}

let barbellRow = Exercise(name: "바벨로우") {
    person.upperBodyStrength += Int.random(in: 10...20)
}

let cablePullover = Exercise(name: "케이블 풀오버") {
    person.upperBodyStrength += Int.random(in: 10...20)
}

// 하체운동
let squat = Exercise(name: "스쿼트") {
    person.lowerBodyStrength += Int.random(in: 20...30)
    person.fatigue += Int.random(in: 10...20)
}

let lunge = Exercise(name: "런지") {
    person.lowerBodyStrength += Int.random(in: 20...30)
    person.muscularEndurance += Int.random(in: 10...15)
}

let legExtension = Exercise(name: "레그 익스텐션") {
    person.lowerBodyStrength += Int.random(in: 20...30)
}

// 유산소운동
let longRun = Exercise(name: "오래달리기") {
    person.muscularEndurance += Int.random(in: 20...30)
    person.upperBodyStrength += Int.random(in: 5...10)
    person.lowerBodyStrength += Int.random(in: 5...10)
    person.fatigue += Int.random(in: 20...30)
}

// 동적휴식
let activeRest = Exercise(name: "동적휴식") {
    person.fatigue -= Int.random(in: 5...10)
}
```

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Routine.swift
> +    var exercises: Array<Exercise>
Routine 구조체의 exercises 프로퍼티도 var → `let`으로 변경해도 문제없네요! 😄 
`배열`이 들어가니까, 단수형인 exercise 가 아니라 복수형인 exercises 사용하신 점도 정말 좋습니다!

콜론(:) 뒤에 타입을 명시해주실 때는 Array<Exercise> 라고 해주셨는데
`[Exercise]` 라는 표현을 쓰지 않는 이유가 있으실까요~?
저는 좀 더 간편해서 많이 쓰거든요! ㅎㅎ

```suggestion
    let routineName: String
    let exercises: [Exercise]
```

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Routine.swift
> +    }
개인적으로, `print문`을 만들 때, `이모지`를 넣어서 이렇게 시각적으로 구분해주는 스킬을 좋아해요!

왜냐면 나중에 UI 있는 앱을 만드시다보면..
별의 별 메시지들이 콘솔 로그에 잔뜩 뜨거든요? (의도하지 않아도 막 뭔가 뜨더라구요...)

그러면 내가 일부로 넣어둔 print문하고 구별이 잘 안 돼요 😢 
그래서 저는 print문을 넣으면, 꼭 앞에 💚 🔴 → 이런 눈에 잘 띄는 이모지를 하나씩 꽂아놔요. ㅎㅎ

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Routine.swift
> +    }
22번째 줄 - print문 아래 공백도 삭제해도 괜찮아 보입니다!

2022-05-08 07:32 UTC, Jager-yoo commented on CodeStarterCamp_Week4/main.swift
> +var hellRoutine = Routine(routineName: "지옥의 헬스루틴", exercises: exercise)
- 여기선 person 인스턴스는 반드시 `var`여야 하죠~?
구조체로 만들었으니까요. ㅎㅎㅎ
대신에 새로 만든 짧은 이니셜라이저를 한 번 적용해보세요! 👍🏻 

- exercise 를 선언할 때, 타입 명시를 `[Exercise]` 로 바꿔봤습니다.
근데 여전히 Array<Exercise> 가 좋다면, 그걸 사용하셔도 괜찮아요. 😄 

- hellRoutine 인스턴스는 var → `let` 으로 선언해도 전혀 문제가 없네요!
항상 let 을 기본으로 생각하시되, 에러가 뜨면 그때 var 로 바꾸는 걸 추천드립니다!
`변경`될 필요가 없는 객체들을 var 로 선언해두면, 다른 개발자가 볼 때 오해할 수도 있으니까요.
확실하게 `"얘는 변경되지 않는 애다!"` 느낌을 주기 위해 let 으로 선언해두면, 코드 읽기가 더 편해요. 🌊

```suggestion
var person = BodyCondition(startingPoint: 0) // 새로 만든 짧은 이니셜라이저 적용해봄

let exercise: [Exercise] = [sitUp, sitUp, sitUp, activeRest, deadLift, deadLift, deadLift, activeRest, plank, plank, plank, activeRest, barbellRow, barbellRow, barbellRow, activeRest, cablePullover, cablePullover, cablePullover, activeRest, longRun]

let hellRoutine = Routine(routineName: "지옥의 헬스루틴", exercises: exercise) // let 으로 바꾸기
```

2022-05-09 08:41 UTC, jsa0224 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    }
이런 방법은 생각도 못 했어요! 좋은 팁 알려주셔서 감사합니다👍

2022-05-09 08:47 UTC, jsa0224 commented on CodeStarterCamp_Week4/Exercise.swift
> +})
`후행 클로저`, 저도 사용할까 말까 좀 고민한 부분인데요.
클로저를 공부할 때, 너무 많이 축약하면 처음 코드를 보는 상대방이 헷갈려할 수도 있다고 하더라고요. 저도 `action 프로퍼티`가 없으니까 뭔가 허전하기도 했고요 ㅎㅎ
어디까지 축약해도 되는 건지 헷갈려지기 시작하지만😵‍💫 수정했습니다!

2022-05-09 08:51 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Exercise.swift
> +})
후행 클로저 안 쓴 커밋을 해봤으니까, 적용한 커밋도 해봤다고 생각하시죠! 😄

2022-05-09 08:53 UTC, jsa0224 commented on CodeStarterCamp_Week4/Routine.swift
> +    var exercises: Array<Exercise>
배열 선언에 익숙하지 않아서 계속 `Array<>`형태를 사용하는 거 같습니다🥲
객체 파트를 공부하면서 `변수`, `상수`에 대한 개념도 모호해지는 거 같아요😵‍💫
복습 차원으로 `배열`과 `변수`, `상수` 부분 다시 보도록 할게요!

2022-05-09 08:57 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Routine.swift
> +    var exercises: Array<Exercise>
이 이미지 한 번 참고해보세요!
출처는 [이 블로그](https://velog.io/@ryan-son/Swift-%EA%B5%AC%EC%A1%B0%EC%B2%B4%EC%99%80-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0%EC%9D%98-%EC%83%81%EC%88%98%EC%99%80-%EB%B3%80%EC%88%98-%EC%84%A0%EC%96%B8%EC%97%90-%EB%94%B0%EB%A5%B8-%EA%B0%92-%EB%B3%80%EA%B2%BD-%EA%B0%80%EB%8A%A5-%EC%97%AC%EB%B6%80%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B3%A0%EC%B0%B0) 입니다! 😄 

![image](https://user-images.githubusercontent.com/71127966/167376036-9ecbb73b-ae23-40d5-aafb-79b93feb0c70.png)

![image](https://user-images.githubusercontent.com/71127966/167376051-535cb356-5563-46e1-bc4e-83578fa8f44d.png)

2022-05-09 09:18 UTC, jsa0224 commented
@Jager-yoo 

좋은 월요일입니다😞
원래 어제 수정까지 하려고 했는데 갑자기 열이 올라서 못 했네요ㅠㅜ
지금은 괜찮습니다 ㅎㅎ (코로나는 아닌 거 같아요)

불필요한 공백들 삭제하고, 이니셜라이저도 하나로 통합해서 수정했습니다!

2022-05-09 16:48 UTC, Jager-yoo commented
변경 내용 확인했습니다! 😄 
수고하셨어요 솜~!
머지합니다!

2022-05-09 16:48 UTC, Jager-yoo approved these changes

2022-05-09 16:48 UTC, merged