Mission4: Step2: 야곰 피트니스, 지옥의 헬스 트레이닝
yagom-academy/swift-starter-Round4 pull request #43
Opened 2022-05-08 22:17 UTC by wolframhwang

@llghdud921 

안녕하세요 제리

간만에 PR 올리네요.
그동안 이래저래 바쁜일이 많았습니다.

## Error

- 에러 사항에 대해서 Enum을 통해 정리하려고 많이 노력했습니다.
- 근데, NamingError 를 제외한 BodyConditionError / RoutineSelectError / CountOfSetSelectError 는, 전부 Integer관련 에러라서 겹치는 부분이 상당히 많은데, 이 부분을 프로토콜이나 상속으로 해결하고 싶다고 생각은 했는데 쉽진 않더군요..

## Extension

- Extension을 사용해서 Int의 음수 값을 얻어낼수 있게 코드를 구현했습니다.
- Extension에서는 저장 프로퍼티는 선언할수 없고, 함수나, 연산 프로퍼티에 대한 선언만 되더라구요
- 생각보다 유용했습니다.

## ExerciseSet

- ExerciseSet은.. 네이밍이 사실 그닥 마음에 들진 않지만, 운동 할 때 필요한 enumerate Set이라서 이 네이밍이 가장 적합하다고 판단했습니다.

## 에러처리 어떻게...?

- 저는, Result를 사용했습니다.
- do - catch 문을 사용하는 방법도 있겠으나, 사용할 경우 에러 처리마다.. 분기점이 많아져서 처리하는데 좀 .. 화나더라구요
- 대체로 에러처리는 GuestRegister에서 입력 값을 받을 경우에 일어납니다.
- 그리고 에러 발생 시, 재귀로 처리하는걸 선호하지 않는 편이라, while로 처리해두었습니다.

## Step1 대비 구조 변경

- Exercise의 action 프로퍼티는 Person을 파라미터로 받게 변경하였습니다.
- exercise자체가, "운동하는" 사람의 bodycondition을 조절해 주는 역할을 해야하는데, 이런 부분에 있어서는, person에게 Message를 보내서, condition을 조절하는 방식이 더 적합하다고 판단하여 변경했습니다.

2022-05-09 16:39 UTC, llghdud921 requested changes
안녕하세요~!
벌써 마지막주가 되었네요ㅠㅠ 하지만 코드 정말 잘 작성해주고 계시고 저도 최대한 피드백 빨리 드리려고 노력할테니 끝까지 열심히 달려보아요~~!!!

그리고 코드 잘 작성하시는 것은 말할 것도 없고 PR에 구현 내용과 그에 대한 생각을 적어주셔서 감사드립니다! 그럼 간단하게 코멘트 남겨드렸으니 확인 부탁드리고 궁금한 점은 DM주세요~!!

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    func isGetGoal(goal: BodyCondition) -> Bool {
`목표에 도달하였는가?`라는 메서드의 기능을 나타내고 있는 것 같아요
상태 유무를 판단하는 메서드명은 동사가 들어가므로 `isReachedGoal` 과 같은 네이밍이 더 나을 것 같아요!

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/ExerciseSet/ResrOrTraining.swift
> +enum RestOrTraining {
흠.. 저도 고민을 해보았는데요
`RestOrTraining` 보다는 `ExerciseState`와 같은 운동 상태를 나타내는 것이 더 명확하지 않을까 싶네용..

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/Extension/Int_Extension.swift
> +    var isNagative: Bool {
getter setter를 잘 활용하시는 것 같아요!! 👍 💯

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/Extension/Int_Extension.swift
> +extension Int {
파일 분리 완벽.. 👍

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        self.goalBodyCondition = guestRegister.assignGoalBodyCondition()
self키워드를 이용하셔서 로직을 작성해주셨는데요!
저는 코드 구성상 깨끗해보이고 싶고 self가 꼭 필요할때와 없어도 괜찮은 코드를 구분하기 위해 꼭 필요할때만 self 키워드를 넣는 편입니다!

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/GuestRegister.swift
> +    func assignPersonalInfo() -> Person {
약어는 지양합시다!!

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/GuestRegister.swift
> +    func inputName() -> Result<String, NamingError> {
Result를 굉장히 잘 다루시네요!! 👍

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/GuestRegister.swift
> +            }
Error case 마다 print를 해주고 있는데요! 
localizedError 프로토콜을 공부해보시고 활용해보시면 해당 로직이 간결해질것 같아요!

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/GuestRegister.swift
> +        }
저의 개인적인 의견인데요!
nilCondition, nilName 등 동일한 에러인데 다른 Error 타입으로 정의해두었어요. 저였으면 InputError하나로 nilValue, emptyValue, negativeValue들을 정의했을 것 같아요!

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/GuestRegister.swift
> +            return .failure(.nilName)
`readline`메서드에서 nil을 반환하는 경우는 어떤 경우일까요?

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/GuestRegister.swift
> +        return Person(name: guestName)
`guestRegister`에서 `Person`객체를 생성하여 회원정보를 만드는 로직이 너무 좋은 것 같습니다... 크.....

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        }
여기에서 get을 쓴 이유가 있을까요? 그냥 `return fatigue`를 해주는 것과 무슨 차이가 있었던 것인가요? 
(진짜 궁금해서 여쭤봅니다..)

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    mutating func growthBody(bodyPart: BodyPart,
근력을 늘이는 메서드의 기능을 명확하게 나타내지 못하는 것 같아요! 개선해볼까요?

2022-05-09 16:39 UTC, llghdud921 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    private var goalBodyCondition: BodyCondition
이것도 제 개인적인 생각인데요
요구사항에는 `fitnessGuest`만 optional로 정의하라고 나와있지만 goalBodyCondition도 optional로 정의해도 될것같아요!
제 생각에는 guest가 없으면 목표운동량도 없게되니까 둘다 optional로 가져가도 될것같다는 생각입니다ㅎㅎ
한번 고려해보세용ㅎㅎ

2022-05-10 03:26 UTC, wolframhwang commented on CodeStarterCamp_Week4/GuestRegister.swift
> +    func assignPersonalInfo() -> Person {
엄.. 어떤 부분에서 약어가....?

2022-05-10 03:26 UTC, wolframhwang commented on CodeStarterCamp_Week4/GuestRegister.swift
> +            }
찾아봤는데 좋은 방법이라고 생각이 듭니다.

2022-05-10 03:31 UTC, llghdud921 commented on CodeStarterCamp_Week4/GuestRegister.swift
> +    func assignPersonalInfo() -> Person {
Info용

2022-05-10 04:20 UTC, wolframhwang commented on CodeStarterCamp_Week4/GuestRegister.swift
> +    func assignPersonalInfo() -> Person {
ㄴㅇㄱ 헛;; 진짜 아무렇지 않게 명사 인줄 알고 썼네여;; 감사합니다

2022-05-10 04:21 UTC, wolframhwang commented on CodeStarterCamp_Week4/GuestRegister.swift
> +        }
네 그런거같아요.. 항상배워갑니다.

2022-05-10 04:23 UTC, wolframhwang commented on CodeStarterCamp_Week4/GuestRegister.swift
> +            return .failure(.nilName)
empty 일 경우에는 empty 로 처리됩니다.
nil로 들어가는 경우가 저도 궁금해서 찾아봤는데요

찾아보니 [이런]([https://appleceo.github.io/2019/06/25/readLine/]) 경우에 nil이 들어가는군요.

2022-05-10 04:24 UTC, wolframhwang commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        }
private로 fatigue를 선언 해놔서 직접 가져오질 못하다보니, 연산프로퍼티로 처리 하려고 했습니다

개인정보니까요..?

2022-05-10 04:26 UTC, wolframhwang commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    mutating func growthBody(bodyPart: BodyPart,
말씀하신게 기능을 개선하자 라는 말씀이신지, growthBody 라는 것이 근육 늘이는 메소드라는 네이밍을 개선하자는 것인지 제가 이해를 잘못한거같아서... 답변 대신 질문을 드립니다.

2022-05-10 04:26 UTC, wolframhwang commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    private var goalBodyCondition: BodyCondition
저도 사실.. Optional이 조금 더 어울린다고 생각은합니다.
반영해볼게요

2022-05-10 09:45 UTC, wolframhwang commented
@llghdud921 
안녕하세요 제리
말씀하셨던 부분들에 대해서 수정사항을 반영해서 패치를 다시 쌓았습니다.


- 목표 도달했는지 확인하는 부분에 대해서 리네이밍을 진행했습니다.
    - isGetGoal -> isReachedGoal
- RestOrTraining Enumeration -> ExerciseState 리네이밍
- 불필요한 self 키워드 제거
- 근육 성장에 관련된 네이밍 변경 growthBody -> growthMuscles
- LocalizedError 프로토콜 추가한 전체적인 리팩토링 반영

2022-05-11 15:48 UTC, wolframhwang commented on CodeStarterCamp_Week4/BodyCondition.swift
> +        }
수정사항 반영했습니다.

2022-05-11 16:23 UTC, llghdud921 requested changes
안녕하세요!
우선 리뷰가 늦어진점 죄송합니다ㅠ week5 리뷰는 해당 코드가 머지되고 진행할게요~
몇가지 답변을 남겨두었습니다~ 확인부탁드릴게용

2022-05-11 16:23 UTC, llghdud921 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    private var goalBodyCondition: BodyCondition
엇 이부분 반영이 안되어있네요...?

2022-05-11 16:23 UTC, llghdud921 commented on CodeStarterCamp_Week4/InputError/NamingError.swift
> +enum StringInputError: Error, LocalizedError {
파일명은 namingError.swift인데 StringInputError가 작성되어있네용
그리고 StringInputError.swift에 StringInputError가 또 정의되어있는데... 저만 그런가요? 같은 타입 중복되면 에러생기지 않나 싶어요

2022-05-11 16:23 UTC, llghdud921 commented on CodeStarterCamp_Week4/InputError/IntegerInputError.swift
> +    var errorDescription: String {
잘 사용해주셨는데요!
아마 프로토콜을 제대로 활용하셨다면 `String?` (string 옵셔널) 타입의 errorDescription이 정의가 되어있어야해요!
![스크린샷 2022-05-12 오전 1 10 00](https://user-images.githubusercontent.com/40068674/167896953-cd3de7b8-99be-452d-97cd-ff6e09c7371c.png)

그래서 실제로 사용하는 error를 처리하는 부분에서는 `print(error.localizedDescription)` 으로 작성해주시면 된답니다~

2022-05-11 16:23 UTC, llghdud921 commented on CodeStarterCamp_Week4/Person.swift
> +        }
이부분 아까도 말씀드렸지만 그냥 연산프로퍼티로도 사용할 수 있습니다!
하지만 틀린것은 아니에요!! 이유가 있다면 get only 연산프로퍼티로도 만들수 있을 것 같아요~
추가적으로 get set은 언제, 왜 사용되는 건지, set only는 사용할수 있는지 등 다양한 의문도 가져보셨으면 합니다!

2022-05-11 16:37 UTC, wolframhwang commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    private var goalBodyCondition: BodyCondition
빠져있엇네요 반영했습니다.

2022-05-11 16:38 UTC, wolframhwang commented on CodeStarterCamp_Week4/InputError/NamingError.swift
> +enum StringInputError: Error, LocalizedError {
흠.. 이건 엑스코드 문제같은데요
제 디렉터리엔 제거 했고, 지난번에 제거한 패치 같이 올렸는데 이상하네요
그냥 웹에서 삭제했습니다.

2022-05-11 16:38 UTC, wolframhwang commented on CodeStarterCamp_Week4/InputError/IntegerInputError.swift
> +    var errorDescription: String {
넵

2022-05-11 16:39 UTC, wolframhwang commented
@llghdud921 제리

리뷰 주신 부분에 대한 사항들 반영했습니다 리뷰 다시 부탁드릴게요!

2022-05-11 16:43 UTC, llghdud921 commented on CodeStarterCamp_Week4/InputError/IntegerInputError.swift
> +    var errorDescription: String {
수정된것을 보았는데 localizedDescription을 사용해보셨을까요...?
그냥 옵셔널 수정이 아닌 실행하는 코드도 수정되어야한다고 생각해요

2022-05-11 16:45 UTC, llghdud921 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    private var goalBodyCondition: BodyCondition
이것도 단순한 옵셔널의 수정이 아닙니다ㅠ
옵셔널로 정의됨으로써 실행하는 코드가 어떻게 수정될 수 있는지 생각을 해보셨으면 합니다

2022-05-11 17:21 UTC, merged