Week4 [Step2] Onestar
yagom-academy/swift-starter-Round4 pull request #46
Opened 2022-05-09 16:32 UTC by oneStar92

@oksunwoo 
***
# Step 2: 야곰 피트니스, 지옥의 헬스 트레이닝
* Todo
- [x] Person 타입을 생성합니다.
  * Person 타입은 다음과 같은 프로퍼티를 갖습니다.
    * 이름
    * bodyCondition
  * Person 타입은 다음과 같은 메서드를 갖습니다.
    * exercise(for set: Int, routine: Routine)
- [x] FitnessCenter 타입을 생성합니다.
  * FitnessCenter 타입은 다음과 같은 프로퍼티를 갖습니다.
    * 목표 바디 컨디션
    * 회원(Optional로 설정합니다.)
    * 최소 2개 이상의 루틴 목록 (Collection타입)
  * FitnessCenter 타입은 다음과 같은 메서드를 갖습니다.
    * 실행예시와 같은 피트니스 프로그램을 시작하는 메서드
- [x] 프로그램 실행시 다양한 예외 상황에 대한 에러 처리를 진행합니다.
  * 루틴 진행 도중 회원의 피로도가 100이 넘은 경우
  * 루틴이 끝났을 때 목표치에 미도달한 경우
  * 각종 입력 상황에서 예상치 못한 입력값이 들어온 경우.
  * 루틴을 진행할 회원이 없는 경우
  * 기타 예외 사항으로 판단되는 경우
***
 현재 Step1의 action을 수정하여서 PR하였습니다. 코드의 흐름은 올바른 값이 입력되기 전까지 계속 입력을 받는 형태로 구현하였습니다.

2022-05-10 08:32 UTC, oksunwoo requested changes
원스타 이번에도 너무 고생하셨어요!
제가 이번에 드리고 싶은 말씀은 전반적으로 코드의 가독성이 많이 떨어집니다....
갑자기 왜 이렇게 되었을까요ㅠㅠ 제생각에는 이렇게 300줄까지 쓰여질 코드가 아닌데...
어떻게 리뷰를 드리지 하다가 우선 원스타의 의견을 듣고싶었구요, 하나씩 고쳐가면 좋을 것 같아요!

현재는 FitnessCenter가 하는 역할이 굉장히 많습니다. 사실 피트니스센터가 하는 게 맞긴한데...
한번 역할 분리를 조금 해보면 어떨까 싶어요.
음.. 어떻게 나눌까 고민을 해보았는데요. 피트니스 센터와 콘솔부분을 좀 분리하면 어떨까요? 피트니스 센터와 그 안에 있는 태블릿? 프로그램?의 개념인거죠. 원스타도 "프로그램이 강제종료됩니다" 라는 문구를 써주셨듯이 피트니스센터가 강제종료되진 않을거잖아요? 그러니까 프로그램 타입과 같이 view(콘솔)를 구성하는 타입을 조금 나누어보았으면 좋겠어요. 그리고 이 프로그램을 피트니스센터가 갖고 있는 느낌으로 역할 분리를 해보면 어떨까요?

조금은 어려울 수도 있지만, 각자의 역할이 명확해지면 자동으로 가독성도 올라가고, 재사용성 또한 좋아지는 깔끔한 코드를 완성할 수 있을거에요!

2022-05-10 08:32 UTC, oksunwoo commented on CodeStarterCamp_Week4/Person.swift
> +    var bodyCondition: BodyCondition
음..언젠가는 원스타도 마주할 부분 같아서 말씀드립니다.
bodyCondition은 reference 타입입니다. 반면 Person은 value 타입이죠. Person은 자식의 reference를 관리해야 할텐데, 정말 value type으로 존재할 수 있을까에 대해 고민을...한번 정도 해보시는 것은 좋은 경험이라고 생각됩니다. 이 부분은 검색 키워드로 스위프트 참조 카운팅을 남겨놓겠습니다

2022-05-10 08:32 UTC, oksunwoo commented on CodeStarterCamp_Week4/main.swift
> +
에러타입을 별개로 파일을 분리해보는 것은 어떨까요?

2022-05-10 08:32 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
golas는 오타겠죠??ㅎㅎ
그리고 메서드명에서 굳이 property는 없어도 좋을 것 같아요

2022-05-11 09:05 UTC, oneStar92 commented on CodeStarterCamp_Week4/Person.swift
> +    var bodyCondition: BodyCondition
너무 어려운 내용이라서 잘 이해가 안되네요 ㅠㅠ 메모 해놓고 공부해보겠습니다.

2022-05-11 09:05 UTC, oneStar92 commented on CodeStarterCamp_Week4/main.swift
> +
넵!!

2022-05-11 09:05 UTC, oneStar92 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
해당 함수는 삭제했습니다 ㅠㅠ

2022-05-11 09:12 UTC, oneStar92 commented
* Error 파일 분할.
* FitnessCenterKiosk 타입을 통한 역할 분담.
***
역할을 나눈다고 나눴는데... 아직도 코드의 가독성이 그렇게 좋아보이진 않습니다... 우선은 Push하여서 리뷰를 받고싶어서 Push하였습니다.
***
# 질문사항
1. 지금과 같은 경우엔 Commit의 단위를 어떻게 나눠야 할지 잘모르겠습니다. 처음 코드를 작성하는 과정에도 하나의 함수를 해당 함수를 구현하기 위해서 여러개의 함수가 만들어지는데 보통 이런경우엔 어떤 기준을 commit의 기준으로 잡아야하나요.. 하나의 메서드, 함수를 기준으로 해야하는지 아니면 하나의 기능구현을 기준으로 해야하는지 잘 모르겠습니다.
***

2022-05-12 09:50 UTC, oksunwoo reviewed
우선 정말 고생하셨습니다!
역할분리가 정말 쉽지않았을텐데 말이죠

키오스크 타입과 fitness센터 타입을 잘 분리해주셨어요!
물론 아직 완벽하게 각 메서드가 분리가 되어있지않지만요
하지만 저는 이게 시작이라고 생각합니다.
1기능 1함수라는 말 들어보셨나요? 한개의 메서드에는 하나의 기능만 작성되도록 하라는 말입니다.
이렇게 작성을 하게되면 재사용성도 증가할 뿐더러, 수정할때에도 변경이 조금 더 쉬워질 수 있겠죠
지금까지는 아주 좋았는데, 이번스탭에서는 코드가 많이 복잡해지고 읽기가 힘든 코드가 되었죠.
이게 메서드에 여러 기능이 들어가있고, 각자 분리가 쉽지않기에 한 메서드에 다 담았기 때문입니다. 이부분은 앞으로 신경쓰시면서 코드 작성하시면 점차 감이 오실 거에요. 원스타의 검색능력과 코드를 짜내려 생각하는 부분은 정말... 대단하다고 생각이 들거든요!

---
### 질문에 대한 답변
커밋단위에 대한 고민으로 들리는데요!
사실 이 부분은 위에서 제가 말씀드린 부분과 어느정도 통하는 부분이라고 생각이 드는데, 1기능 1메서드면 커밋이 깔끔해지겠죠ㅎㅎ  아마 원스타가 생각하신 기능은 크게크게 잡으신것같은데, 저는 checkEnglish같은 것도 하나의 기능이라고 생각하기 때문에, 원스타입장에서는 메서드별로 커밋단위를 쪼개시면 될 것 같습니다!! 아그리고 이건 저도 누구한테 들었는데, 커밋에 뭐라고 적어야할 지 고민이 되면 잘못짠 메서드다 라는 말을 들은적이 있는데요ㅎㅎ 만약 정말 한가지기능만 메서드에 탑재한다면 고민할필요가 없다는 뜻이더라구요 저는 사실 몇번 겪어봐서..ㅎㅎ

무튼 원스타 이번스탭도 너무너무너무 고생하셨습니다!

2022-05-12 09:50 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    let fitnessCenterKiosk = FitnessCenterKiosk()
제가 말씀드린대로 kiosk 타입을 주셨군요!
아주 좋습니다.
fitnessCenter가 kiosk를 소유하고 있는 형태에요! 현실에서도 그렇긴하죠!
이제 여기서 조금만 더 수정을 해볼까요?
init해줄때 kiosk를 받아오는 거에요! 이렇게 해주는 이유는 객체간 결합도를 낮추기 위함입니다!
지금은 어느 특정 키오스크가 지정되어 있지만, 나중에 만약 kiosk를 바꾸고 싶을수도 있잖아요!
자동차로 예를 들자면 바퀴는 자동차에 속해있지만, 자동차가 바퀴를 소유하고있다면 바퀴교체는 매우힘들어지겠죠?
그래서 바퀴라는 것만 들어올수있게 해놓고, 자동차에 네모난바퀴를 끼우든, 세모바퀴를 끼우던 동작이 가능하도록 변경하는 느낌인거죠!

2022-05-12 09:50 UTC, oksunwoo commented on CodeStarterCamp_Week4/Error.swift
> +}
실제 이 function의 동작하는 곳은 어디일까요~?
지금은 에러있는 곳에 넣어두셨지만, 실제 파일이 동작하는 곳에 이 메서드를 넣는 것이 좋을 것 같아요

2022-05-12 09:50 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +                }
if let으로 바인딩을 해주고 계신데, 이부분은 괄호가 너무 많아서 가독성이 조금 떨어져보이네요ㅎㅎ
guard let 으로 바꾼다면 아주 조금은 상황이 나아질 것 같은데요?

그리고 메서드명은 repeat 으로 루틴을 반복하는 곳인데, check후 결과가 성공인지 실패인지까지 판별하고있어요!
이 부분도 잘게 나누어볼수있을 것 같죠?

2022-05-12 09:50 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +                    kioskStep += 1
저는 사실 이부분을 보면서 감탄했어요
정말 창의적인 방법이라고 생각했거든요! 진짜 생각많이 하셨을 거같아요ㅎㅎ 더불어 알고리즘 문제도 잘푸실것 같네요

그와 별개로 switch문을 보면 어떻게든 step별로 다 돌아가고 있는모습이죠? 사실 switch문의 쓰임새에서 조금 벗어나는 느낌입니다. switch문은 선택지가 여러개있는 경우 중에서 한가지 케이스를 선택해야 합니다. 사실 이 부분은 if else가 조금 더 잘어울리는 것 같아요!

또한 step별로 메서드를 구분할 수 있을 것 같아요!

2022-05-12 09:50 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    let fitnessCenterKiosk = FitnessCenterKiosk()
덧붙여서 검색해보고 싶으시면 의존성 주입 이라는 키워드로 한번 해보세요!

2022-05-12 09:50 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +                        return .success(true)
result타입을 사용하셨네요!
result를 쓰신 이유가 있으신가요?
무엇이 좋던가요?
error처리와의 차이점도 꼭 알고계셔야합니다ㅎㅎ

2022-05-12 09:50 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenterKiosk.swift
> +    func receiveEnglishName() -> String {
여기에 빈 공백은 무엇인가요~

2022-05-13 07:50 UTC, oneStar92 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    let fitnessCenterKiosk = FitnessCenterKiosk()
이런 부분도 신경써야 하는군요!! 매번 새로운 내용을 배우네요.

2022-05-13 12:18 UTC, oneStar92 commented on CodeStarterCamp_Week4/FitnessCenterKiosk.swift
> +    func receiveEnglishName() -> String {
앗.. 수정했습니당

2022-05-13 12:23 UTC, oneStar92 commented on CodeStarterCamp_Week4/Error.swift
> +}
넵 알겠습니다.

2022-05-13 12:27 UTC, oneStar92 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +                        return .success(true)
해당 코드를 작성 당시에 실패할 수 있는 작업들에 대한 결과를 알려주기 위해서 result타입을 사용하였습니다.
저는 Result사용이 더 명시적이고 간결해서 사용하는데 더 편리하였습니다.
넵!!! 차이점도 꼭 숙지하도록 하겠습니당.

2022-05-13 12:29 UTC, oneStar92 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +                }
수정했습니다!

2022-05-13 12:32 UTC, oneStar92 commented
***
이렇게 토니의 리뷰가 끝이나네요.
그 동안 좋은 리뷰 해주셔서 감사했습니다.
토니 덕분에 많은 것들을 배우게됐습니다.
비록 이 PR이 마지막 PR이지만 나중에 꼭 현업에서 만나보고 싶네요!!
그동안 감사했습니다!!
***
* 기능 분리를 최대한으로 해봤습니다.
* 리뷰에 남겨주신 내용을 반영했습니다.

2022-05-17 00:40 UTC, merged