Week 4 [STEP 2] Oh Sung Ah
yagom-academy/swift-starter-Round4 pull request #47
Opened 2022-05-10 10:12 UTC by delight010

@jaemuYeo 

오류처리를 어디서 부터 해야되는 지, 함수가 처리하는 영역은 어느정도로 잡아야될 지 많이 고민을 했어요.
쓰다보니 코드가 길어졌는 데. 스스로도 괜찮은 코드인지 돌이켜보게 됩니다
특히, 
```Swift
func achieveGoalBodyCondition() -> Bool {
        let currentBodyCondition = self.member?.bodyCondition
        if currentBodyCondition?.upperBodyStrength ?? 0 < goalBodyCondition?.upperBodyStrength ?? 0 {
            return false
        } else if currentBodyCondition?.lowerBodyStrength ?? 0 < goalBodyCondition?.lowerBodyStrength ?? 0 {
            return false
        } else if currentBodyCondition?.muscularEndurance ?? 0 < goalBodyCondition?.muscularEndurance ?? 0 {
            return false
        } else {
            return true
        }
    }
```

이부분 같은 경우는. BodyCondition의 인스턴스들이 옵셔널 값이라서. 옵셔널을 풀고 비교하기 위해 ?? 연산자를 썼는 데요.

```Swift
func achieveGoalBodyCondition() -> Bool {
        let currentBodyCondition = self.member?.bodyCondition
        if (currentBodyCondition?.upperBodyStrength)! < (goalBodyCondition?.upperBodyStrength)! {
            return false
        } else if (currentBodyCondition?.lowerBodyStrength)! < (goalBodyCondition?.lowerBodyStrength)! {
            return false
        } else if (currentBodyCondition?.muscularEndurance)! < (goalBodyCondition?.muscularEndurance)! {
            return false
        } else {
            return true
        }
    }
```
이렇게 강제로 옵셔널을 추출하는 쪽이 가독성면에서 좀 더 좋지않을까..생각이 들어요.
가급적 강제옵셔널 추출은 지양하는 게 좋다고하지만..
더 좋은 방법이 없는 지 고민이 됩니다.

2022-05-11 09:46 UTC, jaemuYeo requested changes
## 실행 문제점

1. 회원의 이름을 입력할 때 값을 입력하지 않아도 재 입력되지않고, 
넘어갑니다. 특히, 넘어가는 위치가 목표치를 입력하는 곳이 아닌 루틴을 선택하는 부분으로 넘어갑니다.

2. 운동목표치를 입력할때 값을 입력하지 않아도 `값의 갯수가 적거나 큽니다.`라는 에러가 발생합니다.

3. 회원의 피로도가 100이 넘어 도망을 갔는데 목표치에 도달하지 못했습니다 -> 루틴 선택으로 넘어가 버려요!!
그리고 넘어간 것을 다시 실행하면 무한으로 반복이 됩니다!

4. 아무런 입력값없이 실행 후 세번 엔터치면 성공입니다! 라는 문구가 나타나고 앱이 종료됩니다.

현재 앱을 실행해보면 위와 같은 현상들이 발생합니다.
일단은 프로젝트 요구사항 처럼 프린트 안되는 부분도 보이네요! . 내용별로 점선을 통해 구분짓는 부분이요 😫
그리고 에러가 발생하면 그냥 넘어가지 않고 다시 입력할 수 있도록 유저에게 편의를 제공해주었으면 좋겠어요 !!

## PR내용에 대한 제 생각

애플에서는 옵셔널 강제추출에 대해 매우 지양하고 있는데요!
옵셔널 강제추출 시 nil값일 경우 어떤 현상이 일어나는지와
지양하고 있는 그 이유에 대해서 한 번 알아보시면 좋을 것 같습니다~
성아님의 코드를 최대한 헤치지 않는 선에서 저라면 어떻게 했을지 작성해보았어요😀

```swift
func achieveGoalBodyCondition() -> Bool {
        guard let member = self.member, let goalBodyContition = self.goalBodyCondition else { return true }
        let currentBodyCondition = member.bodyCondition
        
        if currentBodyCondition.upperBodyStrength < goalBodyContition.upperBodyStrength {
            return false
        } else if currentBodyCondition.lowerBodyStrength < goalBodyContition.lowerBodyStrength {
            return false
        } else if currentBodyCondition.muscularEndurance < goalBodyContition.muscularEndurance {
            return false
        } else {
            return true
        }
    }
```

## readLine() 함수 사용
위의 내용과 같은 내용일 수 있지만 이 곳을 구현하신 부분에서도 옵셔널 강제추출을 사용하셨군요!
옵셔널 바인딩을 활용해 다시 구현해보시면 좋을 것 같아요 🙏

## 에러처리에 대한 부분
에러 케이스들을  간단하게 잘 네이밍하셨군요!
하지만 너무 간결해서 어디에 사용될 에러케이스들인지 잘 파악이 안되는 것 같아요!
LocalizedError와 localizedDescription을 알아보시고 적용해보셔도 좋을 것 같습니다!

———

위의 내용들을 토대로 정상적으로 작동하는 코드로 변경해보고 추후에도 문제가 있으면
문제가 될법한 부분을 찾아서 코드에 코멘트를 남겨놓겠습니다!!
궁금하신 내용 있으시면 언제든 디엠주셔요😀

2022-05-11 09:46 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Error.swift
> +enum InputError: Error {
에러케이스를 잘 정의하셨군요 👍

2022-05-11 09:46 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    convenience init(routine: [Routine] ) {
convenience init을 통해 값을 초기화하셨군요!!👏

2022-05-11 09:46 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        let inputName: String = readLine()!
이 곳을 포함해 아래의 readLine함수를 옵셔널 바인딩 하신 후 구현해보세요!😀

2022-05-11 09:46 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    func inputRoutineSet() throws -> Void {
이 메서드의 위치는 어디가 좋을까요?? 🤔
executeRoutine 메서드에서 사용되었지만 그 위에 작성되었군요!

2022-05-11 09:46 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        let bodyCondition: BodyCondition = .init(upperBodyStrength: goalBodyConditionArray[0], lowerBodyStrength: goalBodyConditionArray[1], muscularEndurance: goalBodyConditionArray[2], fatigue: 0)
몇 일 전 도우미들 사이에서 이슈가 있었던 부분이군요!
사실 이 부분은 개인차의 컨벤션일 수 있겠지만 보통은

```swift
let bodyCondition = BodyCondition(인스턴스 초기화)
```
형식으로 작성한답니다 😀

2022-05-12 11:18 UTC, delight010 commented
@jaemuYeo 

말씀해주신 거 확인하고, 수정을 많이 했습니다!

- inputText()
입력값이 있는 지 확인하고 String으로 반환
- inputInt()
Int로 형변환할 수 있는 값인지 확인하고, 형변환실패 시 재입력

- inputGoalBodyCondition()
한번에 입력받고 .map으로 [Int]로 바꾸고싶었지만
시간이 좀 많이 걸릴 것 같아서 더 쉬운 방법으로 바꿨어요.
출력할 목표설정 부분을 Array로 정하고, int값을 받아와 append하도록 바꿨습니다.

- inputRoutineSet()
입력한 숫자가 입력할 수 있는 범위에 있는 지 판별하기 위해 routineNumberRange를 쓰고, 
while문을 통해 routineNumberRange의 범위내에서만 입력할 수 있도록 하였습니다.

- executeRoutine()
피로도가 100이 넘지않았을 때만 
achieveGoalBodyCondition을 호출하도록 하였습니다.

- achieveGoalBodyCondition
말씀해주신대로 바꾸니 훨씬 보기 편하네요!!
상수도 쉼표를 통해 연속적으로 만들 수 있다는 걸 배웠습니다!!!

- func exercise(for set: Int, routine: Routine)
while문 안에서 피로도가 100이 안넘었을 때만 다음 세트를 진행하도록 하였습니다.

- extension InputError: LocalizedError
원래는 do~catch문으로 오류처리를 하고 싶었는 데요.
error 문구 출력하고, 함수를 다시 재귀하기엔 좋은 방법이 아닌 것 같아.
error를 출력할 수 있도록 extension하였습니다.

2022-05-13 08:10 UTC, jaemuYeo reviewed
성아님 마지막까지 정말 정말 고생많으셨습니다!! 👏
마지막 인사를 하기 전 코멘트먼저 남겨보자면
프로그램을 실행하는데 있어서의 문제점들을 잘 보완해주셨어요 👍
PR로 보내주신 코드의 설명 덕분에 이해도 훨씬 빨랐습니다~
옵셔널을 강제추출하지 않고 바인딩해서 처리해주는 것 또한 완벽합니다!
그리고 `localizedDescription`의 사용도 적절하게 해주신 것 같아요~
성아님 말씀처럼 이번 프로젝트 어려운 부분이 많았지만 잘 마무리해주셨습니다 😀
week4까지 마무리하신 것도 너무너무 대단하십니다👏👍
5주 동안 너무너무 고생 많으셨고, 앞으로도 개발길 꽃길만 걷기를 바라요🌸🎉
저도 많이 부족했지만 성아님과 5주 동안 함께 진행하게 되서 많이 배우고 즐거웠습니다!!
항상 응원할게요~~☺️

2022-05-13 08:10 UTC, jaemuYeo commented on CodeStarterCamp_Week4/Error.swift
> +extension InputError: LocalizedError {
LocalizedError 정의를 잘 해주셨어요! 👏
이제 에러케이스가 더 명확해진 것 같아요!!

2022-05-13 08:10 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
>      func exercise() {
exercise메서드가 훨씬 간결해졌군요 👍

2022-05-13 08:10 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    func inputText() -> String {
아래의 inputInt 메서드를 포함해 재사용가능하게 기능을 나누신 부분은
너무너무 잘 하신것 같습니다!! 멋져요 👍
다만 은닉화(private)를 한다고 생각하고, 작성한 위치를 조금 변경해 보면 좋을 것같습니다!!
개인의 컨벤션 차이이지만 저는 인터페이스 함수를 가장 위에 두고 도구들을 아래에 작성하는 편입니다😀

2022-05-13 08:10 UTC, jaemuYeo commented on CodeStarterCamp_Week4/FitnessCenter.swift
>      func achieveGoalBodyCondition() -> Bool {
Bool타입을 반환하는 함수의 네이밍은 어떻게 하면 잘 표현될까요??🤔

2022-05-13 08:10 UTC, merged