Week4 [Step2]윤세영
yagom-academy/swift-starter-Round4 pull request #53
Opened 2022-05-12 06:10 UTC by ssyoun4092

@oksunwoo 
오늘이 마지막 PR이 될 것 같네요...ㅠ 무지 아쉽습니다ㅠ 덕분에 많은걸 배워가요ㅎㅎ 진심으로 감사드립니다!

> ## 코드설명
너무 많은 것을 생각해서 그런지.. 코드가 깔끔하진 못하네요ㅠ 어떻게 최대한 중복을 없애려고 하고, 정리하려고 했습니다만 부족한게 많을 것 같아요! 부족한 부분 알려주시면 감사하겠습니다!

### Exercise.swift
+ 주요 변경점이라고 한다면, action 프로퍼티에서 매개변수 타입을 BodyCondition을 받도록 하지만, Inout 키워드를 통해 함수실행할 때 값이 변경할 수 있도록 하였습니다.
+ Step1 리뷰 때 BodyCondition의 타입을 클래스로 바꿔서 해결하라고 말씀해주셨는데, inout을 통해 한번 해결해보았습니다.

### Person.swift
+ 구조체로 정의한 이유는 따로 상속받거나 상속하지 않아서 구조체로 정의하였습니다.

### Error.swift
+ 에러를 열거형으로 정리하고, 그 에러가 발생하였는지 확인하는 함수도 같이 넣었습니다.
    + 처음에는 FitnessCenter 안에 함수를 넣었는데, 너무 길어지고, 가독성도 떨어져서 Error파일에 같이 넣었습니다.
+ commonError: 사용자가 입력한 input에서 기본적인 에러를 검출합니다.
    + 강제종료, 특수문자 여부 확인, 숫자가 포함되어있는지 확인, 숫자만 포함되어있는지 확인합니다.
+ InputChooseRoutinError: 몇 번쨰 루틴을 선택할건지에 대한 입력을 받을 때 사용자가 선택지 외의 숫자를 입력할 때 에러를 발생시킵니다.
+ WhileExercisingError: 운동을 진행할 때, 피로도가 초과되었는지, 목표치를 달성하였는지에 대한 에러를 발생시킵니다.

+ checkInputHasCommonError 함수를 통해 모든 commonError를 확인하고자 했습니다. 입력 받을때마다 확인해야해서 하나의 함수로 만들고 재사용하고자 했습니다.

### FitnessCenter.swift
+ 구조체를 사용한 이유는 상속받거나 하지 않아서 입니다!
+ 옵셔널 바인딩을 할 때 guard let, if let 중에 고민을 많이 했는데, 사용 기준은" 옵셔널 바인딩을 하지 않으면 해당 함수를 실행할 이유가 없는가?"입니다.
    + 대표적으로 사용자의 입력을 받아야만 Step2 프로젝트가 의미가 있는 것이기 때문에 guard let으로 readLine()을 옵셔널바인딩 하였습니다.
+ 148번줄에 유일하게 강제추출을 하였습니다.
    + 그 이유는 해당 코드줄을 실행하기 전에 이미 몇차례 input이 숫자임을 확인하였기 때문에, 절대로 nil값이 될 수 없다고 생각했습니다.

> ## 고민했던 점
+ 사용자의 입력에서 에러가 발생하였을 때, 새로 입력을 받을 수 있도록 하는 로직을 생각해내는 굉장히 어려웠습니다.
    + 처음에는 catch문 안에서 해당 함수를 처음부터 새로 실행하도록 코드를 작성하였습니다.
        + 보기에는 별 문제가 없어 보이지만, 알고보니 catch문을 빠져나와서 코드를 실행하는게 아니라, catch문 안에서 다시 함수가 실행되는 거더라구요..
        + 만약 사용자가 계속 입력을 실패하면 catch문에서 함수가 실행되고 그 함수 안의 catch문에서 또 함수... 이렇게 소용돌이처럼 빠져나올 수가 없었습니다.
    + 따라서 제가 생각해낸 최선의 방법이 inputHasProblem이라는 함수안에 변수를 따로 만들어서, try문을 통과하면 false, 에러가 있으면 true로 바꿉니다. 그리고 do-catch문 밖에서 if문을 통해 inputHasProblem의 값을 체크하고, true라면 즉, 에러가 있었다면 처음부터 새로 해당 함수를 실행하도록 하였습니다.
        + 뭔가 최선의 방법은 아닌데..ㅠ 다른 방법이 있는지 알고 싶습니다!

+ 어떻게 하면 제3자가 제 코드를 읽기 쉬울까를 고민 많이 했습니다.. 
+ 함수내부가 너무 긴거 같기도하고..ㅠ 함수 네이밍은 잘 지은거 같은데 또 한편으로는 너무 긴게 아닌가도 싶네요

2022-05-14 10:51 UTC, oksunwoo requested changes
우선 정말 고생하셨습니다.
코드도 깔끔했구요.
한번 피트니스센터 타입과 뷰를 보여주는 타입을 나누어보는 것은 어떨까요?
예를 들어, 태블릿이나 키오스크가 있다고한다면 실제로 목표치를 입력해볼 수 있다고 생각해보는 것은 어떨까요? 지금은 피트니스 센터가 하는 역할이 굉장히 많은 것 같기도 해서 나누어보는 것 추천드릴게요!
우선은 태블릿을 피트니스센터가 소유하는 방식으로 적용해봐도 좋을 것 같습니다.

---
### 질문에 대한답변

flag를 이용하는 방식으로 해결을 해주셨는데요! 세영님께서 질문하신 사항이 무엇인지 잘 이해를 하지못했습니다ㅠ true false 변수를 지우고 나서 실행을 해보았는데, catch문을 하나만 통과했습니다. 질문다시한번 말씀해주시면 피드백 드리겠습니다.

2022-05-14 10:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        }
오 재귀를 사용하셨네요!
재귀의 장,단점에 대해 알고계신가요? 반복문과는 무슨차이가 있을까요?
왜 여기서는 재귀를 사용하였을까요?

2022-05-14 10:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
>      }
doExercise인데 너무 많은 역할을 하는 것 같지않나요?
운동을 하는것부터 컨디션을 알려주고, 운동을 성공했는지 실패했는지 판별까지 해주고 있는 메서드 같아요~
조금 더 잘게 나누어볼수있지는 않을까요?

2022-05-14 10:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/Error.swift
> +}
여기있는 메서드는 에러타입이라고 보긴 어려울 것 같아요!
세영님께서는 지금 파일분리를 person타입, fitnessCenter타입 등등 타입별로 파일분리를 해주셨는데,
해당 함수가 과연 에러 타입일까요?
이 메서드가 동작되는 곳은 정확히 어디인가요?

예를 들어, 헬스장 타입과 태블릿 타입이 있다고 가정했을때 숫자가 제대로 들어왔는지 확인하는 곳이 어디인지 생각해보면 조금더 명확해질 수 있을까요?

2022-05-14 10:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/Error.swift
> +    let range = target.rangeOfCharacter(from: letters)
와 검색능력에 우선 칭찬을👏
그러면 평소와 마찬가지로 순서대로
CharacterSet, punctuationCharacters,rangeOfCharacter, decimalDigits 은 무엇이던가요^^?

2022-05-14 10:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/Error.swift
> +}
지적은 아니고 그냥 다른 팁도 드리자면
forEach에 대해서 아시나요?
for문과는 무엇이 다른지 한번 찾아보시고, 왜 쓰이는지도 한번 생각해보시면 좋을 것 같아요!
위와 같이 character 타입이 쓰이게 되면, isNumber를 이용해서 코드를 조금 더 편리하게 짤 수도 있을 것 같거든요ㅎㅎ

2022-05-14 10:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/Error.swift
> +        whose.bodyCondition.muscleEndurance < targetMuscleEndurance {
whose보다는 그냥 사람을 뜻하는 단어가 들어가도 괜찮을것 같아요ㅎㅎ

2022-05-14 10:51 UTC, oksunwoo commented on CodeStarterCamp_Week4/Error.swift
> +        throw WhileExercisingError.overFatigue
일반적으로는 한줄에 .이 두개이상 들어가면 가독성을 헤친다고 합니다
현재는 그리 나쁘진않은데 어떻게 개선해볼 수 있을까요?

2022-05-14 16:36 UTC, oksunwoo reviewed
<img width="277" alt="스크린샷 2022-05-13 오후 2 22 03" src="https://user-images.githubusercontent.com/55880539/168440618-e5896451-500d-454f-a84f-772cc329517a.png">
<img width="240" alt="스크린샷 2022-05-13 오후 2 22 08" src="https://user-images.githubusercontent.com/55880539/168440619-ac05c86b-a23d-4026-9a5a-2a1f545c03b9.png">

제가 코멘트를 빠뜨린게 있는데요
이렇게 테스트를 해보면 무엇이 잘못된지 바로 아시겠나요?
입력이 잘못된경우에도 끝까지 다른 스펙을 요구하고 있죠. 그리고 세번 잘못입력한 경우는 문구가 세번이 뜨는 군요. 사용자가 실제로 사용한다 했을때 사용자경험면에서 좋지 않아보여요. 오히려 한번 잘못된경우 바로 잡아주는 것이 좋을 것 같네요 어떻게 생각하세요 세영님은?

2022-05-16 03:21 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        }
재귀함수의 장점
+ 변수사용이 줄어듭니다.
+ for문이나, while문에 비해 코드가 간결해진다는 장점이 있습니다.

재귀함수의 단점
+ 지속적으로 함수를 호출하게되면 불필요하게 과도한 메모리 스택이 쌓이는 단점이 있습니다

재귀를 사용한 이유
+ 솔직하게 반복문으로 되돌아가는 방법을 처음에는 생각이 안나서, 단순하게 처음으로 돌아가는 식으로 구현하였습니다.
+ 재귀함수의 장단점을 알게되고, 이 방법을 사용해도 큰 문제는 없겠다는 생각을 했습니다.
    + 메모리에 스택이 과하게 쌓일정도로 함수가 재귀되진 않는다고 생각합니다. 에러메세지를 사용자한테 알려주고 있기 때문입니다!

2022-05-16 03:21 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/FitnessCenter.swift
>      }
넵 함수를 나누어서 구현하였습니다!

2022-05-16 03:22 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Error.swift
> +}
위 함수를 사용하는 타입 안에 메소드로 들어가있는게 좋을 듯해서 수정했습니다!

2022-05-16 03:24 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Error.swift
> +        throw WhileExercisingError.overFatigue
함수 도입부에 member.bodyCondition을 변수로 선언하고,
그 변수를 통해 fatigue로 접근하며 개선하였습니다!

2022-05-16 03:24 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Error.swift
> +        whose.bodyCondition.muscleEndurance < targetMuscleEndurance {
넵ㅎㅎ

2022-05-16 03:42 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Error.swift
> +}
forEach란걸 처음 봤네요..ㅎㅎ 조금 알아보긴 했는데, 정확히 어떤 경우에 사용해야하는지는 아직 감이 안오네요ㅠ

그래도 클로저형태라서, 매개변수를 받고 받은 매개변수로 무언가 활용할 수 있다는 점에서 for문과 다른 것 같습니다!!
토니의 힌트 덕분에 forEach와 isNumber를 통해 코드를 수정했긴 했는데, 보다 더 간결한 코드가 있을 것 같아요..

2022-05-16 04:01 UTC, ssyoun4092 commented on CodeStarterCamp_Week4/Error.swift
> +    let range = target.rangeOfCharacter(from: letters)
앗.. 감사합니다! 검색하는 것도 재밌더라구요!

+ CharacterSet
    + '검색 작업을 활용하기 위한 유니코드의 집합체'라고 공식문서에 적혀있습니다!
    + 예를 들어 특수문자만 모여있는 집합을 이용해 무언가를 하고 싶을때, 직접 하나하나 입력하기보단 애플이 제공하는 CharacterSet을 이용하면 훨씬 수월하게 사용할 수 있습니다!
    + 주의할점은 유니코드 형태로 포함되어있다는 점입니다! 따라서 실제 포함되어있는걸 확인하려면 변환해야합니다

+ punctuationCharacterSet
    + 특수문자들이 유니코드형태로 포함된 집합체입니다

+ rangeOfCharacter
    + 해당 String타입의 문자가 입력받은 CharacterSet타입의 집합체에 있는 문자와 비교하여 포함하고 있다면 포함되어 있는 모든 문자를 반환하고, 없다면 Nil값으로 반환합니다

+ decimalDigits
    + 모든 십진수를 포함하는 CharacterSet입니다!

2022-05-17 00:41 UTC, closed without merging