Week4 [Step2] som
yagom-academy/swift-starter-Round4 pull request #54
Opened 2022-05-12 08:16 UTC by jsa0224

안녕하세요, @Jager-yoo

오늘이 마지막 코멘트 시간이라고 공지를 받아서 평소보다 더 열심히 과제를 수행했는데요!
그래도 너무 오래 걸렸네요..🥲
Step1이 쉽다고 느껴서 그런지 Step2는 지옥의 난이도였어요...
~야곰피트니스 사용자를 지옥 보내기 전에 제가 먼저 갈 거 같아요...~

## 부족한 부분
1. 입력한 근육량을 달성해도 실패 처리 (루틴 선택 무한 루프)
제 예상에는 아마 이 코드에 문제가 있어서 그런 거 같아요. 어떻게 고치면 좋을지 모르겠어요...ㅠㅜ
```Swift
func accomplishCondotion() -> Bool {
        let currentBodyCondition = member?.bodyCondition
        guard currentBodyCondition?.upperBodyStrength ?? 0 < targetBodyCondition.upperBodyStrength  else { return false }
        guard currentBodyCondition?.lowerBodyStrength ?? 0 < targetBodyCondition.lowerBodyStrength  else { return false }
        guard currentBodyCondition?.muscularEndurance ?? 0 < targetBodyCondition.muscularEndurance else { return false }
        return true
    }
```

2. member.name이 옵셔널 상태로 출력
제가 맞게 표현한 말인지 모르겠지만.. 
예를 들어 피트니스 맴버가 저라면, `Optional("som")` 이렇게 출력이 되더라고요.
`옵셔널 바인딩`을 안 하고 출력되서 그런 걸까요? 
```Swift
print("--------------")
print("목표에 도달하지 못 했습니다. 현재 \(member?.name)님의 컨디션은 다음과 같습니다.")
member?.bodyCondition.checkYourCondition()
print("--------------")
tryRoutine()
```

## 오래 걸린 부분 (하소연이라 안 보셔도 돼요...)
1. convenience init
이건 제가 TIL에서도 하소연을 쓴 부분인데요...
야곰 피트니스 인스턴스를 만들 때, `이름`과 `루틴리스트` 외의 프로퍼티는 필요가 없다고 판단되서 보조 이니셜라이저의 존재를 알고 사용하려고 마음 먹었죠! 그래서 처음에는 필요한 프로퍼티만 초기화하면 되겠구나 싶었어요.
```Swift
convenience init(name: String, listOfRoutine: [Routine]) {
        self.init(name: name, listOfRoutine: listOfRoutine)
    }
```
그랬더니 오류가 떴어요 ㅇ0ㅇ! 다시 원문을 찬찬히 읽어보니 객체의 모든 프로퍼티를 언급해야 한다더라고요. 
```Swift
convenience init(name: String, listOfRoutine: [Routine]) {
        self.init(name: name, targetBodyCondition: BodyCondition, listOfRoutine: listOfRoutine)
```
이렇게 하면 될 줄 알았는데 계속 오류가 나는 거예요... 증말 억울했어요!
이 짧은 코드에 4시간이나 소모했다구요...
물론 `member` 프로퍼티를 언급 안 한 것도 문제지만 `BodyCondition`의 프로퍼티도 모두 언급해야하더라고요...

```Swift
convenience init(name: String, listOfRoutine: [Routine]) {
        self.init(name: name, targetBodyCondition: BodyCondition(upperBodyStrength: 0, lowerBodyStrength: 0, muscularEndurance: 0, fatigue: 0), listOfRoutine: listOfRoutine)
    }
```

그래서 이렇게 바꾸니 오류가 안 나서 룰루랄라 다른 코드를 작성하고 있었는데, 같이 스터디 하시는 분이 애초에 `BodyCondition`에 0이라고 값을 지정하면 초기화할 필요가 없어서 저렇게 코드가 길어지지 않는다고 하셔서 한 번 사용해봤습니다! 

```Swift
class BodyCondition {
    var upperBodyStrength = 0
    var lowerBodyStrength = 0
    var muscularEndurance = 0
    var fatigue = 0
}
```
```Swift
convenience init(name: String, listOfRoutine: [Routine]) {
        self.init(name: name, targetBodyCondition: BodyCondition(), member: Person(name: "", bodyCondition: BodyCondition()), listOfRoutine: listOfRoutine)
    }
```

근데 좋은 방법인지는 잘 모르겠어요😞 초기화를 하지 않고 저렇게 값을 넣어도 되는 걸까요...

2. 디엠으로 말씀드렸던 '근육량 값이 안 들어가요' 사건
Step 1의 코드 때문이었어요.
Step 1에서는 `Person`이라는 객체가 따로 없었기 때문에 변수 `person`의 `근육량`만 변화되게끔 코드를 만들었는데, Step 2에서 그대로 작동되니 값이 들어갈리가 없었죠.
```Swift
var person = BodyCondition(startingpoint: 0)

let sitUp = Exercise(name: "윗몸일으키기") { 
    person.upperBodyStrength += Int.random(in: 10...20)
    person.fatigue += Int.random(in: 10...20)
}
```

그래서 person에 BodyCondition을 넣어줬어요.

```Swift
struct Exercise {
        let name: String
        let action: (BodyCondition) -> Void
}

// 상체운동
let sitUp = Exercise(name: "윗몸일으키기") { (person: BodyCondition) in
    person.upperBodyStrength += Int.random(in: 10...20)
    person.fatigue += Int.random(in: 10...20)
}
```
여기에는 6시간을 투자했답니다! 저 코드 말고 다른 부분이 문제라 생각해서 삽질을 오래... 했어요 ㅎㅎ

## LastDay
물론 코드캠프는 금요일까지지만, 코멘트는 오늘까지가 기한이라고 들었어요ㅠㅠ
5주가 이렇게 쏜살같이 지나간 건 처음인 거 같아요 ㅎㅎ!
그동안 더 성장할 수 있게 도와주신 예거! 감사해요 ㅎㅎ!!

2022-05-12 18:11 UTC, Jager-yoo commented
솜~! 5주 동안 수고하셨습니다. 💐 
이번 과제 어렵더라구요~! 😅 저도 어디를 어떻게 고칠지 많이 고민해봤답니다!

질문 주신 부분에 대한 해결 & 대답은 코드 리뷰 단계에서 다 달아볼게요!

2022-05-12 19:15 UTC, Jager-yoo requested changes

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var fatigue = 0
PR 에 적어주신 내용이 이거군요.
그냥 타입의 모든 프로퍼티에 기본값(default value)을 집어넣어두면, 애초에 값을 할당해줄 필요가 없으니까
`이니셜라이저` 또한 의무적으로 구현하지 않아도 됩니다.

저는 개인적으로, 그럼에도 이니셜라이저를 만드는 게, 좀 더 명확하게 `개발자의 의도`를 담을 수 있다고 생각합니다.

```swift
var upperBodyStrength: Int
var lowerBodyStrength: Int
var muscularEndurance: Int
var fatigue: Int

init() {
    upperBodyStrength = 0
    lowerBodyStrength = 0
    muscularEndurance = 0
    fatigue = 0
}
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var fatigue = 0
그리고, 자신의 프로퍼티를 호출할 때 `self` 를 반드시 붙일 필요는 없습니다.

1. 저는 `self`를 반드시 붙이라고 Xcode 에서 경고를 내거나
2. 프로퍼티와 파라미터의 이름이 동일해서, 헷갈림을 유발할 수 있는 경우

이렇게 2가지가 아니라면, 웬만하면 self 를 생략하는 편입니다.
왜냐면, 글자가 줄어들기 때문에 `가독성이 향상`된다고 생각해서 입니다. 😄

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +            exercise.action(self)
여기 신기하더라구요!
action 은 클로저를 타입으로 갖는 상수인데
파라미터가 `(BodyCondition)` 이니까, `self` 를 집어 넣어서, 스스로의 프로퍼티 값을 변경시킬 수 있게 만드는...
너무 좋은 논리였습니다. 감탄했어요 ㅋㅋㅋ 👏🏻👏🏻👏🏻

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Exercise.swift
>  }
Exercise 구조체 선언할 때, 프로퍼티들 앞에 띄어쓰기가 너무 과하게 많이 들어가있습니다.
이런 거 일일히 체크하기 어렵다면, 전체를 드래그 하신 다음에 `컨트롤 + i` 키를 사용하면, 자동으로 indentation 이 맞춰집니다!

```swift
struct Exercise {
    let name: String
    let action: (BodyCondition) -> Void
}
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Exercise.swift
>  }
솜이 action 프로퍼티의 타입을 `(BodyCondition) → Void` 로 이미 정의하셨죠?
지금부터 이어질 운동들은.. 전부 Exercise 타입의 인스턴스 들이잖아요?

따라서, person 이라는 임시변수는 `당연히` BodyCondition 타입일 거에요.
그러니까, person 뒤에서 콜론(:) 찍고, 다시 타입 명시를 해줄 필요가 없습니다. 😄 

이런 거 할때, 이 상수/변수가 무슨 타입이지? 🤔 궁금하시다면...
`옵션` 키를 누른 상태에서, 상수/변수를 좌클릭 해보세요...! 그러면 `타입`을 빠르게 알 수 있어요. 🔍 

```suggestion
let sitUp = Exercise(name: "윗몸일으키기") { person in
    person.upperBodyStrength += Int.random(in: 10...20)
    person.fatigue += Int.random(in: 10...20)
}
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Exercise.swift
>  }
다른 운동들도 전부 이 방식으로 고쳐보세요!

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +}
에러 타입까지 만드시느라.. 정말 공부할 것도 많고
심지어 `do-try-catch` 까지 적용하느라 정~말 힘드셨을 것 같아요. 🥶 

저는 Swift 입문할 때.. do-try-catch 가 너무 싫었거든요.
그래서 `에러 타입` 까지는 만들더라도, 에러 처리 해주기 귀찮아서 `try?` 하곤 했었어요. ㅎㅎㅎ

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +}
하고 싶은 말은
이런 `에러 타입`도 .. 코드량이 적더라도, 엄밀하게는 `별도의 파일로 분리` 시키는 게 깔끔합니다!

여기는 `FitnessCenter` 타입이니까, 다른 타입이 섞여있으면 좀 중구난방해보이거든요.

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
`편의 생성자(convenience init)`는 꼭 사용하실 필요는 없어요!

제 생각에, 이번 프로젝트에서 솜이 어려움을 겪으신 건, 억지로 이 `편의 생성자`를 구현하려다 보니까
로직이 계속 복잡해지고.. 머리속도 복잡해지신 게 아닐까.. 😅 조심스럽게 생각이 드네요..ㅎㅎㅎ

일단, 저희는 `본질`에 집중하기 위해서
이 편의 생성자는 아예 통째로 삭제할게요! 그게 마음이 편하실 거에요! 👍🏻

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var listOfRoutine: [Routine]
## ⭐ 중요한 부분입니다! ⭐ 

이번 문제 해결에 가장 중요한 부분이 여기에요.
`targetBodyCondition` 이라는 프로퍼티의 `타입`을 BodyCondition 으로 세팅한 게, 가장 걸림돌이었어요.

결국 비교해야 하는 건, 3개의 숫자 뿐이에요. 상체근력 / 하체근력 / 근지구력이요.
그래서 여기는 간단하게 `[Int]` 타입으로 입력받는 게 낫다고 생각하구요.
일단 default value 를 [0, 0, 0] 으로 넣어주는 식으로 해서, 이니셜라이저에서 신경 안 쓰도록 해볼게요!

+ 그리고 targetBodyCondition → `bodyGoal` 로 이름을 간략하게 바꿔봤어요. 🤔 
우리가 어떤 체형의 목표를 얘기할 때 "바디 골" 이라는 단어를 쓴다는 거에 착안해서.. 심플하게 줄여봤어요. ㅎㅎ

```suggestion
    let name: String
    var bodyGoal: [Int] = [0, 0, 0]
    var member: Person?
    var listOfRoutine: [Routine]
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
프로퍼티 4개 중에서, 2개는 기본값을 설정해놨기 때문에,
`이니셜라이저`에서는 2개의 프로퍼티(name, listOfRoutine)만 할당해주면 됩니다. 😄 

```suggestion
    init(name: String, listOfRoutine: [Routine]) {
        self.name = name
        self.listOfRoutine = listOfRoutine
    }
```

근데 왜 하필 member 랑 bodyGoal 만 기본값을 줬을까요?
그 이유는.. 이 2개 프로퍼티는 파라미터로 값을 전달 받는 게 아니라, 타입 내부에서 `readLine()` 메서드를 통해, 유저한테 값을 입력받아야 하기 때문이에요..!

추가 코멘트를 읽다 보면, 이해가 좀 되실 겁니다!

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        }
- member 프로퍼티는, 아직 존재하지 않는 옵셔널 상태잖아요?
그러니까, 옵셔널 값에 접근해서 name 을 건드리는 것 보다는
그냥 통째로 `Person 인스턴스를 생성해서 할당`하는 게 좋아보여요. 👍🏻 
(코드를 보면서 이해해보세요!)

- 그리구 전반적으로, `들여쓰기`가 좀 과하게 된 코드들이 종종 보입니다!
이 메서드도 들여쓰기가 스페이스바 8번이나 되어 있어요! (보통 4번임)

```suggestion
    func exerciseRoutine() {
        do {
            let memberName = try writeName() // 유저의 이름을 상수로 받아낸 뒤에
            member = Person(name: memberName, bodyCondition: BodyCondition()) // 이니셜라이저에서 사용
            bodyGoal = try inputBodyGoal() // 이건 아래서 다룰게요.
        } catch InputError.empty {
            print("입력되지 않았습니다. 다시 입력해주세요.")
        } catch InputError.invaildValue {
            print("없는 번호입니다. 다시 입력해주세요.")
        } catch InputError.outOfValue {
            print("값의 갯수가 적거나 큽니다.")
        } catch {
            print("알 수 없는 오류입니다. 다시 시도해주세요.")
        }
        tryRoutine()
    } // 줄 잘 정렬하기
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
readLine() 메서드가 활성화 됐을 때, 아무 입력도 하지 않고 바로 `엔터` 누르면 어떻게 될까요?
그러면 `nil` 이 입력되는 게 아니라, `빈 문자열("")`이 들어가게 됩니다.

솜이 작성하신 코드는 nil 입력을 막을 수는 있어도, 빈 문자열("")을 걸러주진 못하고 있어요!
이걸 해결하려면, 간단하게 `guard문`을 하나 더 추가하면 됩니다. 😄 

```suggestion
    func writeName() throws -> String {
        print("안녕하세요. \(name)피트니스 센터입니다. 회원님의 이름은 무엇인가요?")
        
        // inputName 이 nil 인지 아닌지 먼저 검증
        guard let inputName = readLine() else {
            throw InputError.empty
        }
        
        // 여기까지 왔다는 건, nil 은 아니라는 소리인데, 그러면 빈 문자열("")인지 검증
        guard inputName.isEmpty == false else {
            throw InputError.empty
        }
        
        // 여기까지 왔다는 건, nil 도 아니고, 빈 문자열("")도 아니란 소리임
        return inputName
    }
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
이 메서드는 고친 게 좀 많아서.. 주석 참고해주세요! 😅 

```swift
func inputBodyGoal() throws -> [Int] {
    print("운동 목표치를 순서대로 알려주세요. [상체근력:  하체근력:  근지구력: ]")
    print("목표치간 띄어쓰기는 필수입니다. ex) 100 100 100")
    
    // guard문 2개를, 이렇게 하나로 합칠 수도 있음 (else절이 똑같다는 조건 하에)
    guard let inputBodyGoal = readLine(), inputBodyGoal.isEmpty == false else {
        throw InputError.empty
    }
    
    // 여기서 String -> [Int] 로 변환하는데, compactMap 은 따로 공부해보세요!
    let inputBodyGoalArray = inputBodyGoal.split(separator: " ").compactMap { Int($0) }
    
    guard inputBodyGoalArray.count == 3 else {
        throw InputError.outOfValue
    }
    
    return inputBodyGoalArray
}
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        if accomplishCondotion() {
피로도가 100 을 넘어도, `무한루프` 돈다고 하셨죠?
이 부분에 `guard문` 하나 추가해서 해결할 수 있습니다! 👍🏻 

```suggestion
        routineNumber = 1
        
        // 피로도 100이면 프로그램이 자연스럽게 종료되도록 하기
        guard member?.bodyCondition.fatigue ?? 0 < 100 else {
            print("[알림] 운동을 할 회원이 없으므로, 프로그램이 종료됩니다.")
            return
        }
        
        if accomplishCondition() {
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +            print("목표에 도달하지 못 했습니다. 현재 \(member?.name)님의 컨디션은 다음과 같습니다.")
출력문에 `Optional("이름")` 이렇게 나오는 문제는
출력할 때 옵셔널이 벗겨진 상태가 아니라는 점 때문입니다. 😄 

해결 방법은 간단합니다. 옵셔널 바인딩을 하거나, `nil 병합 연산자(??)`를 사용하면 됩니다.
여기서는 간단하게 nil 병합 연산자 쓰는 게 좋겠네요!

이렇게 하면, 제대로 나오실 겁니다. ㅎㅎㅎ

```suggestion
            print("--------------")
            print("목표에 도달하지 못 했습니다. 현재 '\(member?.name ?? "이름 없음")'님의 컨디션은 다음과 같습니다.")
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
## ⭐ 이 부분도 중요합니다! ⭐ 

- 일단 메서드 제목에 오타있어서, 수정했구요. 😄 (Condotion → Condition)

- `bodyGoal` 프로퍼티는 이제 BodyCondition 타입이 아니라, 그냥 숫자의 배열인 `[Int]` 타입입니다.
그래서 [index] 방식으로 접근해서, 값을 비교해주면 끝입니다. 😄 


```swift
func accomplishCondition() -> Bool {
    let currentBodyCondition = member?.bodyCondition
    
    guard currentBodyCondition?.upperBodyStrength ?? 0 < bodyGoal[0] else { return false }
    guard currentBodyCondition?.lowerBodyStrength ?? 0 < bodyGoal[1] else { return false }
    guard currentBodyCondition?.muscularEndurance ?? 0 < bodyGoal[2] else { return false }
    return true
}

// 참고로, 3번의 guard 문은 아래와 같이 통합시킬 수 있습니다. 콤마(,) 사용해서 묶어주고, else절은 하나로 통일!
func accomplishCondition() -> Bool {
    let currentBodyCondition = member?.bodyCondition
    
    guard currentBodyCondition?.upperBodyStrength ?? 0 < bodyGoal[0],
          currentBodyCondition?.lowerBodyStrength ?? 0 < bodyGoal[1],
          currentBodyCondition?.muscularEndurance ?? 0 < bodyGoal[2] else {
        return false
    }
    
    return true
}
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Person.swift
> +    }
Person 타입은 `구조체`입니다.
그래서 `멤버와이즈 이니셜라이저` 기능이 포함되어 있습니다.

즉, `이니셜라이저`를 반드시 구현하지 않아도, 스위프트가 알아서 만들어줍니다.
특히, 여기서 구현하신 이니셜라이저는 좀 뻔하죠?
name, bodyCondition 정직하게 파라미터로 받아서, 정직하게 프로퍼티에 할당해주잖아요?

정확하게 `멤버와이즈 이니셜라이저`가 하는 일입니다.
그러니까 이니셜라이저 부분을 아예 ❌ **삭제** ❌ 해주셔도 무방합니다! 😄

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Person.swift
> +    }
- 여기 메서드 논리가 좀 복잡해서, 고쳐봤어요. 👷🏻 
`currentNumber` 라는 임시 변수와 while 조합이 필요 없고, 단순한 `for문` 하나로 다 처리할 수 있어요! ㅎㅎ

- 그리구 `피로도(fatigue)`가 100 을 넘는 경우는, `예외 처리` 같은 거잖아요?
그니까 if문 보다는 guard문이 더 어울립니다. ㅎㅎ

아래 코드를 참고 부탁드립니다!

```swift
func doExercise(for set: Int, routine: Routine) {
    for round in 1...set {
        guard bodyCondition.fatigue < 100 else {
            print("\(name)님의 피로도가 \(bodyCondition.fatigue)입니다. 회원님이 도망갔습니다.")
            break
        }
        
        print("--------------")
        print("\(routine.routineName)을 \(round)set시작합니다.")
        bodyCondition.exercise(routine: routine)
    }
}
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Routine.swift
>          }
```suggestion
    init(routineName: String, exercises: [Exercise]) {
        self.routineName = routineName
        self.exercises = exercises
    } // 이거 혼자 이상하게 들여쓰기 쑥 들어가있네요! ㅋㅋㅋ
```

2022-05-12 19:15 UTC, Jager-yoo commented on CodeStarterCamp_Week4/main.swift
> +yagomFitnessCenter.exerciseRoutine()
FitnessCenter 타입은 `클래스`로 구현했죠~?
클래스의 var 프로퍼티는, 타입의 인스턴스가 let 이어도 변경할 수 있어요. 😄 (많이 어려워 하셨던 부분!)

그니까 `yagomFitnessCenter`는 `상수(let)`로 저장해줘도, 전혀 문제 없이 작동합니다!

```suggestion
let yagomFitnessCenter = FitnessCenter(name: "야곰", listOfRoutine: [hellRoutine, normalRoutine])
yagomFitnessCenter.exerciseRoutine()
```

2022-05-14 07:10 UTC, Jager-yoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var fatigue = 0
우리에게 익숙한 [Airbnb](https://www.airbnb.co.kr/) 있죠?
에어비앤비에서 만든 `Swift Style Guide` 문서가 있는데요. ㅎㅎㅎ

이 문서에도 제가 드린 의견과 비슷한 내용이 있어요. [링크](https://github.com/airbnb/swift#omit-self)도 첨부할게요. 😄 
> Don't use `self` unless it's necessary for disambiguation or required by the language.

간단하게 번역하자면... `"모호하거나 Xcode 에서 반드시 요구하는 게 아니라면, 'self' 를 사용하지 마세요."`
라고 읽을 수 있겠네요.

"모호하다" 라는 건, 제가 위 코멘트에서 얘기한 2번 처럼, 프로퍼티와 파라미터의 이름이 동일해서 헷갈리는 경우가 대표적인 예시 같구요.
self 를 반드시 붙여야 하는 경우는, `비동기적(혹은 escaping) 클로저` 내부에서 명시적으로 self 를 사용해야 하는 경우인데요...

이건 iOS 개발을 더 공부하시다가 보면, 어느 순간, "Xcode 가 왜 여기서 self 를 붙이라고 요구하지?" → 생각하는 시점이 오실 겁니다. 🤣 
그때 가서, 이 코멘트를 다시 기억해주시면 좋겠습니다!

<img width="836" alt="image" src="https://user-images.githubusercontent.com/71127966/168414609-31115f82-e62b-4e7a-98e5-00659ca01608.png">

2022-05-14 08:33 UTC, jsa0224 commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var fatigue = 0
이니셜라이저할 때 self를 생략해도 된다니... 충격적이에요😮😮
Xcode에서 경고하지 않는 이상은 생략해도 되겠네요!

2022-05-14 08:42 UTC, Jager-yoo commented on CodeStarterCamp_Week4/BodyCondition.swift
> +    var fatigue = 0
넵!
근데 프로퍼티와 파라미터로 받은 이름이 `동일`한 경우엔 `self` 를 명시해주는 게 좋다는 점만 기억하시면 되겠습니다~! 😄 
(꼭 동일하지 않더라도, 봤을 때, 다른 개발자가 헷갈릴 것 같으면 self 명시해주면 센스있겠죠~!)

```diff
- upperBodyStrength = upperBodyStrength
+ self.upperBodyStrength = upperBodyStrength
```

2022-05-14 08:48 UTC, jsa0224 commented on CodeStarterCamp_Week4/Exercise.swift
>  }
저도 왜 들여쓰기가 되는 지 모르겠어요... 플레이그라운드에서 복붙한 코드라 그런 걸까요🧐

2022-05-14 08:51 UTC, Jager-yoo commented on CodeStarterCamp_Week4/Exercise.swift
>  }
예시 코드를 복붙해오기 전부터, 이미 들여쓰기가 과하게 되어있었을 수도 있구요.. 😄 
개발하다 보면, 이런 들여쓰기 놓치는 경우가 원래 꽤나 있기 때문에... 아주 사소한 실수니까, 넘 걱정하지마세요!

어차피 더 배우시다 보면, 이런 코드 style 오류를 잡아주는 [SwiftLint](https://github.com/realm/SwiftLint) 라는 도구를 사용하게 되실 겁니다.
그거 쓰면, 들여쓰기가 좀 이상하거나 문법적으로 어색한 부분을 다 잡아줘요. ㅎㅎ

2022-05-14 08:56 UTC, jsa0224 commented on CodeStarterCamp_Week4/Exercise.swift
>  }
<img width="482" alt="스크린샷 2022-05-14 오후 5 50 08" src="https://user-images.githubusercontent.com/94514250/168418620-d0ab0886-c14e-4f9c-aa3c-bb68367da32c.png">

진짜 신기하네요!ㅎㅎ 나중에 복잡한 코드 만들 때 도움이 될 거 같아요👍
이미 person이 BodyCondition타입이라 따로 선언할 필요는 없었군요... 수정했습니다!

2022-05-14 08:59 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +}
아하! 다른 파일로 분리해두는 게 좋군요! 수정했습니다!

2022-05-14 09:31 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
이번 미션 리뷰 받으면서 도움되는 내용을 많이 배워가는 거 같아요!
저 메서드가 제대로 안 돌아가는 이유가 저거였군요...😂

2022-05-14 09:36 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
맞아요... 저는 야곰 피트니스 센터 인스턴스 생성할 때, 이름과 루틴 배열만 가지고 오고 싶었을 뿐인데...🥲
머리가 많이 아팠어요ㅎㅎ...

2022-05-14 09:36 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var listOfRoutine: [Routine]
바디골...! 간결해져서 좋네요~! 네이밍은 아직도 넘나 어렵네요...ㅠㅠ

2022-05-14 09:39 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    var listOfRoutine: [Routine]
사용자가 입력한 값이 배열로 들어오니까 프로퍼티도 배열 타입으로 하는 게 좋겠군요!!

2022-05-14 09:49 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
이렇게 되면 제가 하던 고민들도 싹 해결이네요!
피트니스 센터 이름과 루틴은 인스턴스 생성할 때 파라미터에 값이 넣을 수 있도록, 해당 프로퍼티들만 이니셜라이저하고
readLine()에서 입력받을 프로퍼티들은 그럴 필요가 없게 되네요...!!

저도 이렇게 유연한 사고를 가지고 싶어요...😞
막상 프로그래밍할 때 너무 돌아가는 방법만 채택해서 사용하는 거 같아요🙄

2022-05-14 11:20 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        }
- 들여쓰기는 아마 위에서도 말했지만 플레이그라운드에서 코드를 복붙해서 가져오면서 생긴 오류(?) 같아요... 
한 번 찾아봐야겠네요...ㅠㅠ

- 이니셜라이저를 이런 식으로도 사용할 수 있군요! 무조건 init() 메서드 안에서만 사용해야하는 줄 알았어요 ㅇ0ㅇ!!

2022-05-14 17:02 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
저도 솜의 코드를 읽으면서 1시간 이상 고민해서 찾은 방법입니다.. ㅋㅋㅋ
절대 훅훅 떠오르지 않아요..!! 자신감 가지세요 😄

2022-05-15 05:10 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
앗 이것도 문제였어요! 제가 까먹었나봐요... PR에 못 적었군요🥺

2022-05-15 05:29 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
`compactMap`은 각 요소를 조건을 지정하여 호출할 때, `nil` 이 아닌 배열을 반환해주는 `고차함수`군요 !!
가드문을 안 써도 되서 좋네요!ㅎㅎ

2022-05-15 05:55 UTC, jsa0224 commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +        if accomplishCondotion() {
ㅇ0ㅇ!! 이런 방법이 있었군요...!

2022-05-15 06:36 UTC, Jager-yoo commented on CodeStarterCamp_Week4/FitnessCenter.swift
> +    }
맞습니다! 어떤 처리를 했을 때, `nil` 이 나오는 원소들은 자동으로 걸러주는 고차함수에요.

저희는 문자열을 숫자로 바꾸는 `Int($0)` 처리를 하잖아요?
이때 숫자가 아닌 불순물이 섞여있다면, nil 이 나오게 될텐데, 그런 애들을 거른 뒤에 count 가 3인 것만 확인하면 될 것입니다! 😄

2022-05-15 07:57 UTC, jsa0224 commented
@Jager-yoo 

이젠 정말 마지막이네요...🥺
그래도 스승의 날에 보내게 되네요 ㅎㅎ! 예거는 제겐 정말 좋은 스승님이셨습니다🙇‍♀️

사실 어제 끝내려고 했는데 오래 걸리게 되었네요.
앞서 목표치를 달성해도 계속 세트를 선택하라는 메서드가 출력되서 무한루프가 도는 문제를 해결하느라 오래 걸렸어요ㅠㅠ
예거의 말씀대로 피로도가 100이 달성되면 운동이 끝나도 목표치 달성 여부는 알 수 없게 되는 거잖아요!

이 문제를 해결하느라... 오래 걸렸는데, 단순한 비교연산자 문제였어요 ㅎㅎ

```Swift
func accomplishCondition() -> Bool {
        let currentBodyCondition = member?.bodyCondition
        
        guard currentBodyCondition?.upperBodyStrength ?? 0 >= bodyGoal[0],
              currentBodyCondition?.lowerBodyStrength ?? 0 >= bodyGoal[1],
              currentBodyCondition?.muscularEndurance ?? 0 >= bodyGoal[2] else {
            return false
        }
        return true
    }
```

원래는 `<` 이거였잖아요... 그래서 무한루프가 도는 거더라고요.  
원래 제가 만든 메서드는 현재 인바디가 목표 인바디보다 적으면 성공이라는 요상한 메서드가 되어버렸더라고요!
그래서 이 부분을 해결하느라 조금 늦어버렸습니다ㅠㅜ

2022-05-15 10:04 UTC, Jager-yoo approved these changes

2022-05-15 10:09 UTC, Jager-yoo commented
헉 그렇네요! `비교 연산자`의 방향을 잘못 넣었군요.. 저도 저걸 놓쳤네요. 😅 

수정사항들 확인했습니다! 기간이 조금 지났음에도, 힘을 내서 리팩토링해주셔서 감사하구요!
뿌듯하게 머지와 함께, 마무리하도록 하겠습니다. 🎉 

지난 5주 동안 정말 수고 많으셨습니다!
저도 리뷰하면서, 다시 기초를 되돌아볼 수 있었어요. 모르는 개념도 추가로 공부했구요 ㅎㅎㅎ (ex. main, Top-level 코드)

(혹시) 커리어 스타터 캠프 하시게 된다면, 캠프에서 선/후배로 다시 만나길 기대하겠습니다! 👍🏻

2022-05-15 10:10 UTC, merged