Week4 [Step 01] OneE
yagom-academy/swift-starter-Round4 pull request #56
Opened 2022-05-12 16:48 UTC by One-E12

@jaemuYeo  

와! 드디어 진짜 마지막 PR이네요 8ㅅ8

가능할까 했는데 그래도 이렇게 PR이라도 보내는게 어딘가 싶습니다.😢 그동안 저와 함께 해주셔서 감사해요 

 👍잼👍 킹👍 최👍 고👍 

---- 

일단 작성하면서 계속 막혔던 부분은 제가 자꾸 타입.프로퍼티 이렇게 작성하려고 해서 계속 오류와의 전쟁이었어요.
아무래도 초기화 하는게 익숙하지 않아서 그런게 아닐까 싶습니다.🤔 Class / Struct의 초기화를 잘 못하는게 가장 큰 문제인 것 같아요.
위에서 Init()으로 작성하고 나면 인스턴스?를 만들어주는 걸 잘 안하고..., 그냥 타입으로 냅다 불러왖줘!!! 하는 느낌이었달까요.

이름들도 아직 익숙하지 않고, 비슷하다 느껴져서 그런 것 같아요. ( 맞아요 핑계입니다. 휴...)

사실 처음에
```swift
let sitUp: Exercise = Exercise(name: "윗몸일으키기", action: {
    bodyCondition.upperBodyStrength += Int.random(in: 10...20)
    bodyCondition.fatigue += Int.random(in: 10...20)
})
```
여기서 
`bodyCondition.upperBodyStrength` 를 `BodyCondition.UpperBodyStrength`로 계속 했는데 왜 안되는거지 하고 한 30분 고민했답니다. 🤔 구체화도 안 해주고 말이에요🤔 

---- 

그리고 두 번째 막힌 부분은 잼킹에게 DM으로 질문했던...! Array 속에 action 꺼내오기였어요.
이름을 뽑아 오는 건 로또 때 생각나서 로또 코드 보고오니까 감이 잡혔는데 클로저를 어떻게 꺼내오는거지? 하고 한동안 막혀있었습니다.
잼킹이 ⭐️지네 마스터⭐️ 가 되러 가신 사이 고민해보다가 
`클로저가 생기고 함수가 생긴다.` 가 생각나서 바로 그냥 `()` 붙이니까 해결되서 저 소리질렀어요. ㅋㅋㅋㅋㅋㅋ 
그래서~ 이렇게 두 가지의 고민들 끝에 ***일단은*** 완성했답니다. 

---- 

아마 수정해야할 게 있겠지만...😢 그래도 뿌듯하네요!!!!!!!!!!!!!!!!!!!

맘 편히 잼킹의 마지막 리뷰 기다리겠습니다 🥳

2022-05-12 16:53 UTC, One-E12 commented
줄바꿈 수정해서 다시 푸쉬했습니다~_!_!_

2022-05-13 08:36 UTC, jaemuYeo requested changes
👍원👍이👍최👍고👍
어디가시려구요 ^_^ 마무리는 하고 가셔야죠 ㅎㅎ
스텝1까지는 머지될때까지 해보자구요~ 꼭 오늘 제출안하셔도 됩니다!!
코드에 코멘트 확인해주시고 추가로
파일별로 객체를 구분하고 main에서 코드를 실행해볼까요?

2022-05-13 08:36 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +    init(upperBodyStrength: Int = 0, lowerBodyStrength: Int = 0, muscleEndurance: Int = 0, fatigue: Int = 0) {
이러한 경우 init에 기본값을 주기보다는 위의 변수에다가 0을 할당해주는게 좋을 것 같다는 생각해요😀
그러면 굳이 init 함수를 작성하지 않아도 된답니다!
BodyCondition 객체를 클래스로 정의하신 이유도 궁금하네요!
만약 원이와 잼킹이 서로 다른 운동 후 BodyCondition을 체크하는데 같은 값을 참조하고 있다면
어떻게 될까요?? 각자의 기초체력도 목표도 다를텐데말이죠 🤔

2022-05-13 08:36 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +    func nowCondition(myRoutine: Routine) {
메서드의 네이밍이 적절하지 않은 거같아요!
이 전의 함수네이밍은 어떻게 작성했었죠?? 매개변수도 간단히 routine 정도로만 해줘도 좋을 것 같습니다😀

2022-05-13 08:36 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +    func doExercise() {
exercise 정도로 네이밍 해줘도 좋을 것 같네요!

2022-05-13 08:36 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +let sitUp: Exercise = Exercise(name: "윗몸일으키기", action: {
클로저를 잘 활용하셨네요! 👏
현재 타입 명시를 해주셨는데 바로 뒤에 Exercise가 또 읽히네요!
swift에는 타입 추론이라는 기능도 있으니 이렇게 인스턴스를 생성하는 경우에는 타입 명시를 하지 않으셔도 됩니다!

2022-05-19 09:51 UTC, One-E12 commented
잼킹 일단 제가 생각했던대로 구현이 되긴 했는데, 이게 맞는 방향인지 잘 모르겠어요.

----- 

### 궁금한 점 

제가 생각하기에는 지금처럼 이렇게 설정을 했을 때, 
```swift
    func tellCondition(afterRoutine: Routine) {
        afterRoutine.doExercise(by: self)
        print("""
            -----------------------
            현재의 컨디션은 다음과 같습니다.
            상체근력: \(bodyCondition.upperBodyStrength)
            하체근력: \(bodyCondition.lowerBodyStrength)
            근지구력: \(bodyCondition.muscleEndurance)
            피로도: \(bodyCondition.fatigue)
            """)
    }
```
원이, 잼킹 이렇게 소수가 아닌 다수라면 계속 `bodyCondition = oneECondition` 을 
인원 수 대로 계속해서 생성해줘야 할 거라는 생각이 들었어요. 
그건 굉장한 낭비가 아닐까 하는 생각에, (코드도 엄청 길어질 것 같구요.) 
최대한 `self.upperBodyStrength` 를 사용해서 doExercis를 한 상태를 받아온 후에, 
각각의 인스턴스를 구성해주는 형식으로 구현해보려고 했는데,
아직 구현 방식을 어떻게 해줘야하는지 답이 오지 않더라구요.😢 

-----

 여러가지로 시도해본 방법 중에, 
```swift 
func doExercise(by who: BodyCondition) {
        tellMyExerciseRoutine()
        for didExercise in exercise {
            let exercised = didExercise.action
            exercised()
        }
    }
```
 여기서 exercised() 이렇게 한 후에 이 exercised()의 결과를 BodyCondition의 인스턴스에 넣어주려고 했는데,
exercise의 action이 () -> Void 형식이라 들어갈 수 없더라구요.🤔 
함수의 결과를 이용해서 다른 인스턴스에 추가해주는 방식등을 이용해서  풀어내는 건 스위프트에서 불가능 한 걸까요?🤔 

---

생각하는대로 챱챱 적어내면 좋을텐데 😭 많이 어렵네요 😢😢😢😢

2022-05-20 10:48 UTC, jaemuYeo requested changes
생각나는대로 챱챱 적어낸다면 천재일거예요 원이 🙂
너무 속상해하지마요!! 
week4의 난이도가 어렵기도 하구요!! 특히 클로저는 정말 외계어 같죠? ㅎㅎ
차근차근 다시 한번 해봐요!! 구현을 하고나서 얻는 성취감은 힘들었던 만큼의 것과 비례할겁니다!!
코드에 코멘트 남겨놓을게요~

2022-05-20 10:48 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +            상체근력: \(bodyCondition.upperBodyStrength)
해당 객체의 프로퍼티를 통해 출력하고 있는데 외부에 BodyCondition인스턴스를 만들어서
사용하신 이유가 있으신가요??
`self.upperBodyStrength`와 같이 해도 될 것 같아요!

2022-05-20 10:48 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +    init(upperBodyStrength: Int, lowerBodyStrength: Int, muscleEndurance: Int, fatigue: Int) {
인스턴스를 통해 0으로 초기화 하지않고 이 곳에서 init을 생략하고
위에 프로퍼티에다가 0을 넣어주는건 어떤가요?

2022-05-20 10:48 UTC, jaemuYeo commented on CodeStarterCamp_Week4/main.swift
> +    var action: () -> Void
() -> Vodi에서 ()는 함수의 매개변수에 해당하죠!
저 안에 BodyCondition타입을 넣어주면 원이가 시도하려는 것을 해결할 수 있을 것 같아요!
수정하게 되면 외부에서 운동들의 클로저들을 전부 수정해야할 텐데
클로저에 대해 한번 더 공부해보시고 구현해보시다가 막히면 너무 오래 고민하지 말고 바로 헬프주세요!!

2022-07-03 07:10 UTC, closed without merging