Week4 [STEP 2] JM.Y
yagom-academy/swift-starter-Round4 pull request #6
Opened 2022-01-02 15:31 UTC by JungmoYu

@Neph3779 안녕하세요 네프님!

Step2를 꾸역꾸역 완성해서 PR드립니다.
갑작스럽게 복잡해진(아마 제가 잘 몰라서 복잡하게 느끼는거겠죠?) Step2를 제출합니다!

나름대로 여러가지 고민해봤는데, 자세한 사항은 코멘트로 남기겠습니다.

감사합니다!

2022-01-02 15:49 UTC, JungmoYu reviewed
안녕하세요!

위와 같이 제가 고민했던 사항들을 코멘트에 남겨보았습니다.
막상 코멘트를 달려하니 막 많아보이진 않지만..생각보다 엄청 고민의 시간을 가지게 되더라구요 ㅠㅠ

우선, `에러 throw를 여기 저기서 하는 점`과 `FitnessCenter타입의 메써드가 너~무 여러개`인 것은 아닌가 하는 생각이 드는데...

네프님 피드백 부탁드립니다!

감사합니다!

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/DefineExercise.swift
>      }
myBodyCondition -> publicBodyCondition으로 이름을 변경한 것에 맞춰서 상수 선언부에서도 이름을 바꿔주었습니다.

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/main.swift
> +var publicBodyCondition: BodyCondition = BodyCondition()
회의실에서 질문드리고 받은 답변을 근거로 해서 위와 같이 `myBodyCondition -> publicBodyCondition`이라는 이름으로 이름을 좀 변경해줬습니다.

제가 이해한 것으로는, `BodyCondition타입의 publicBodyCondition`이 이 프로젝트 모든곳에서 쓰이는 공통 인스턴스라고 생각했기 때문입니다!

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/Error/Error.swift
> +}
Error를 정의해보았습니다.

이전에 말씀해 주신 대로 다른 Error타입이 무엇이 있는지는 아직 알아보지 못했습니다 ㅜㅜ

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/BodyCondition.swift
> +class BodyCondition {
`struct -> class`로 바꾼 이유는,
`BodyCondition`의 인스턴스인 `publicBodyCondition`이 여기 저기서 많이 쓰이는데, 공통된 상태를 유지하려면 값 타입이 아닌 참조 타입을 이용해야한다고 생각해서입니다!

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/BodyCondition.swift
> +    }
추후 필요한 출력함수 정의

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +    }
`main.swift`에서 이 매서드(`startTraining()`)을 호출 한 이후 연쇄적으로 메써드들이 호출되는데,
루틴을 돌고 난 후 원하는 컨디션에 도달하지 못 했을 때 루틴을 선택하는 `askForSelectRoutine()`부터 재시작하는 것이 맞다고 판단하여 메써드를 이렇게 찢었습니다.

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/Person.swift
> +    var bodyCondition: BodyCondition = publicBodyCondition
`publicBodyCondition` 인스턴스를 공통 바디컨디션으로 사용하고자 위와같이 사용하였습니다.
이 과정에서 만약 `BodyCondition` type이 struct라면, 제가 원하는 동작이 이루어지지 않고, 완전히 새로운 `BodyCondition`이 생기는 것(값 타입이라 메모리공간에 새롭게 생성)이기 때문에 `BodyCondition` 타입을 class로 바꾼 것입니다!

2022-01-02 15:49 UTC, JungmoYu commented on CodeStarterCamp_Week4/main.swift
> +} catch {}
`No Member` 에러를 보기위해 위와 같이 두 case로 찢어보았습니다.

2022-01-02 23:29 UTC, Neph3779 commented on CodeStarterCamp_Week4/Error/Error.swift
> +}
LocalizedError를 키워드로 검색해볼까요?

2022-01-02 23:45 UTC, Neph3779 requested changes
안녕하세요 정모님!
정말 고민을 많이 하셔서 코드를 짜신게 보이네요!
<img width="1114" alt="스크린샷 2022-01-03 오전 8 35 46" src="https://user-images.githubusercontent.com/67148595/147892440-8e84db27-7bcc-4798-94ec-eced59f961fc.png">
출력 부분이 다음과 같이 나오는 것 해결해주시면 더 좋을 것 같아요 ㅎㅎ
피드백 남겨드린 것들 확인해주시고 수정사항 반영해주시면 될 것 같습니다~
그럼 화이팅!!

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +            print("--------------")
이 부분은 에러에 대한 처리 부분이겠죠? throw를 받는 쪽에서 처리해주는건 어떨까요?

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +            print("--------------")
여기서는 에러를 throw만 하고 그 에러를 받아 처리하는 부분은 따로 있었으면 좋겠어요

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +        guard let routineIndexInt = Int(routineIndexString) else { return }
```suggestion
        guard let routineIndexString = readLine(),
              let routineIndex = Int(routineIndexString) else { return }
```

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +        guard let routineIndexInt = Int(routineIndexString) else { return }
왜 이렇게 수정하는 것이 현재 상황에선 더 좋을지? 고민해보시면 좋을 것 같아요

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +    }
깔끔하고 좋네요!
다만 throw를 받아서 처리해주는 메서드가 또다시 throw를 하는건 조금 아쉽네요 ㅠㅠ
차라리 member가 nil인지 체크해주는 throw 메서드를 만들어서
do 문에서 돌려본 뒤 catch에서 처리해주는건 어떨까요?

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/Person.swift
> +    var bodyCondition: BodyCondition = publicBodyCondition
좋습니다! 싱글톤 패턴에 대해서도 한 번 공부해보시면 도움이 될거에요 !

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/Person.swift
> +    var bodyCondition: BodyCondition = publicBodyCondition
struct 사용으로 인해 어떤 의도하지 않은 동작이 발생할 수 있는지
자세하게 시나리오 하나 정도만 생각해볼까요?

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/main.swift
> +do{
```suggestion
do {
```

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/main.swift
> +do{
```suggestion
do {
```

2022-01-02 23:45 UTC, Neph3779 commented on CodeStarterCamp_Week4/main.swift
> +do{
가끔 이런 컨벤션들이 안지켜진 부분들이 있던데
swift lint로 나중에 해결할테지만.. 그래도 습관을 들여놓으시는것도 좋을 것 같아요!

2022-01-03 15:56 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +        guard let routineIndexInt = Int(routineIndexString) else { return }
이 부분 같은 경우는, 분기를 줄이고자함이 맞을까요?
처음 생각에는 혹시 메모리의 관점에서 자원을 덜 낭비하는건가 싶기도 했지만, 다시 보니 결국 guard가 전역으로 변수를 지정함으로서 `routineIndexString / routineIndexInt`모두 메서드의 끝 까지 살아있을 것 같아서 자원을 더 쓰는 코드일 것 같지는 않고..

그래서 혹시 이전의 코드가 분기의 가능성을 줄임으로서 뭔가 개선사항이 있것 일까요?

2022-01-03 16:29 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +    }
말씀대로 처리해 보았습니다. CR수정에서 질문드리겠습니다!

2022-01-03 16:30 UTC, JungmoYu commented on CodeStarterCamp_Week4/main.swift
> +do{
네 알겠습니다! 아직 linter를 사용해보지 않았지만, 그 이전에 최대한 습관들이도록 더 신경쓰도록 하겠습니다!

2022-01-03 16:32 UTC, JungmoYu commented
@Neph3779  안녕하세요 네프님!

피드백주신 사항들에 대해서 수정사항 반영했으며, 추가질문 코멘트로 남기겠습니다!

죄송하지만, 아래 사진과 같이 어떤 것에는 제가 reply를 할 수 있고, 어떤 것은 그렇지 않은데 어떤 차이인지 혹시 알고 계신가요!?

![image](https://user-images.githubusercontent.com/86354361/147955314-b2e05201-c415-41c8-b8c3-16b82d7f06ad.png)

2022-01-03 16:38 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +
질문 드린것과 같이, 이 부분은 혹시 제가 생각 한대로
메모리 자원의 측면이 아니라, 분기를 줄이는 측면으로 접근해서 이렇게 작성하는 코드가 더 좋겠다고 생각해도 되는 부분일까요?

2022-01-03 16:38 UTC, JungmoYu commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +            try checkMemberNil()
이런식으로 수정 해보긴 했는데, 말씀해주신 대로 `checkMemberNil`이라는 메서드를 생성해서 do안에서 돌린다고 하더라도, 결국 `notNilMember`라는 상수를 사용하기 위해서는 `optional binding`과정이 필요한 것으로 예시에 나오기에 이렇게 `return으로 early exit`하는 부분을 만들었습니다.

2022-01-03 16:43 UTC, JungmoYu commented
### struct 사용으로 인해 어떤 의도하지 않은 동작이 발생할 수 있는지 자세하게 시나리오 하나 정도만 생각해볼까요?

이 부분은 예를들어서 제가 `myBodyCondition`이라는 `BodyCondition type의 인스턴스`를 생성한다 하더라도, 후에 다른 곳에서 어떠한 메서드가 

```Swift=
func someFunction(bodyCondition: BodyCondition) {
    bodyCondition.upperBodyCondition += 10
}

someFunction(myBodyCondition)
```

위와 같은 코드를 작성했을 경우, 제가 원한 작업은 `myBodyCondition의 upperBodyCondition을 10증가시키는 것` 이지만, 실제로 BodyCondition이 struct라면, 애초에 위의 코드는 `var bodyConditionInThisMethod = bodyCondition `이런식으로 값을 복사하는 과정이 필요하며, 이렇게 만든다 하더라도 결국 `myBodyCondition.upperBodyCondition의 값은 변화가 없을 것` 이라는게 저의 생각입니다!

2022-01-03 22:50 UTC, Neph3779 commented on CodeStarterCamp_Week4/Types/FitnessCenter.swift
> +
지금은 읽기 좋은 코드가 최우선이라 메모리 자원도 분기처리의 감소도 목적이 아닌 컨벤션을 따르기 위해서 제안드린 코드입니다

2022-01-03 22:52 UTC, Neph3779 commented
안녕하세요 정모님! struct 사용시 발생할 수 있는 문제점도 잘 알아보셨군요!
comment가 달리는것과 안달리는건 저도 왜 그런지를 잘 모르겠습니다 ㅠㅠ... 깃헙 사용법을 조금 더 알아봐야할 것 같아요!
이번 스텝은 여기서 머지하겠습니다! 다음 미션에서 봬요~!

2022-01-03 22:52 UTC, merged