week4 [STEP 1] kokkile
yagom-academy/swift-starter-Round4 pull request #80
Opened 2022-11-07 10:41 UTC by kokkilE

안녕하세요. @wongbingg 
4주차 STEP 1 PR 보냅니다. 항상 감사합니다!

## 고민했던 점

### 변수의 타입
근력이나 피로도 등 변수가 음수값을 갖지 않게끔 구현하고자 했습니다.
UInt 타입으로 정의해보았지만, 마찬가지로 0 이하의 값으로 연산할 때 `(ex) 5 - 10 = -5` 자동으로 0으로 보정되진 않고 오버플로우가 발생하더라구요. 어차피 조건식을 통해 음수값을 검사해야 한다면 굳이 UInt 타입으로 정의할 필요가 없다고 생각해서 Int 타입으로 정의하였습니다.

## 해결이 되지 않은 점

## 조언을 얻고싶은 부분

2022-11-07 23:24 UTC, wongbingg commented
안녕하세요 kokkilE 님 Week4 STEP1 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] BodyCondition 타입에 요구된 프로퍼티가 선언되었는지
- [x] 출력값의 형식이 실행예시와 일치하는지
### ✅ 고민했던 점

변수의 타입까지 고민 하셨군요 👍 맞습니다 overflow가 나기 전에 자체적으로 조건문을 통해 보정을 해주어야 하죠😂 전체적인 코드도 잘 작성 해주셨습니다

2022-11-07 23:40 UTC, wongbingg requested changes

2022-11-07 23:40 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +    }
`Property Observer` 를 잘 활용해 주셨네요 👏

2022-11-07 23:40 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +    }
기본값 부여를 통해 파라미터 값을 받지 않아도 생성이 되도록 구현 하셨네요 👏
적절한 것 같습니다

2022-11-07 23:40 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +}
뭔가 들여쓰기가 한번 더 되어있는 것 같네요 ..? 🧐
의도한 컨벤션이 아니라면 다른 곳과 들여쓰기 정도를 일치시켜 줄까요 ?

2022-11-07 23:40 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +})
클로저를 잘 활용 해주셨네요 👏

- `Int.random(in: 10...20)` 이런식으로 딱 떨어지는 수로 표현해도 좋을 것 같아요 ☺️ 개개인마다 스타일이 다르니 참고만 해주세요

2022-11-07 23:40 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +    }
같은 코드가 각 프로퍼티에서 반복해서 사용되고 있어요 🧐 메서드 분리를 한번 시도 해볼까요 ?

2022-11-08 04:55 UTC, kokkilE commented on CodeStarterCamp_Week4/main.swift
> +    }
변경값의 부호를 확인하고 값을 보정해주는 `correctChangedValue` 메서드와 변경사항을 출력하는 `monitorChanges` 메서드로 분리해보았습니다!

2022-11-08 04:55 UTC, kokkilE commented on CodeStarterCamp_Week4/main.swift
> +}
반영하였습니다.

2022-11-08 04:57 UTC, kokkilE commented on CodeStarterCamp_Week4/main.swift
> +})
반영하였습니다. 한결 보기 편한 것 같아요!

2022-11-08 06:35 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +    }
메서드 분리를 잘 해주셨군요 👍

함수 내에서 varName이란 파라미터는 사용되고 있지 않는 것 같아요 🧐

2022-11-08 06:36 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +    }
메서드 분리와 세부사항까지 처리 해주셨군요 👍👍

2022-11-08 06:37 UTC, wongbingg commented on CodeStarterCamp_Week4/main.swift
> +    }
코드가 한결 깔끔해졌네요 👏👏

2022-11-08 06:39 UTC, wongbingg commented
수정사항 잘 반영 되었네요 ~! 이번 스텝 머지하도록 하겠습니다 👍
다음 스텝도 화이팅입니다 !! 💪

2022-11-08 06:39 UTC, merged