Week 4 [STEP 2] 500beckwon
yagom-academy/swift-starter-Round4 pull request #87
Opened 2022-11-09 13:24 UTC by 500beckwon

@llingo 

STEP 2 를 완료하여 PR을 보내드립니다

 ## 고민했던 점
 ### 가독성 좋게 만들기
 - Routine class를 제작하면서 Error 처리를 하는 과정에서 한 함수에 이것저것 다 넣다 보니 코드가 읽기 힘들어보였습니다 때문에 몇 줄을 더 쓰더라도 좀 읽기 편하게 나눌 수 있는 부분은 다 나누어서 func startActivityRoutine 내부를 정리했습니다.
 - Int지만 0 이하의 값은 에러로 간주하여 숫자외의 값 입력, 숫자지만 0 이하, 피로도 제한 3가지로 에러를 나누어 만들었습니다.

 ---

 ## 해결이 되지 않은 점
 ### ~번째 출력
- enum으로 "N 번째" 출력을 위한 값을 만들었지만 근본적인 해결은 아닌 것 같습니다. 다만 switch로 해도 결과가 같아 추가작업은 하지 않고 제출하게 되었습니다.

 ---

 ## 조언을 얻고 싶은 부분
 ### try?
 -  try? 구문을 사용하면 catch를 따로 선언하지 않아도  이 경우에는 해당 선언자체가 옵셔널로 선언되어 에러를 감지할 수 없다는 뜻인가요?

 ```

2022-11-10 08:59 UTC, llingo requested changes
안녕하세요 @500beckwon 님
벌써 이번 주차의 마지막 PR이네요 🎉

이번 STEP의 중점사항은 다음과 같습니다.
- [x] 사용자와 상호작용하는 완성된 프로그램을 만들어봅니다.
- [x] 원하는 방식으로 에러를 처리합니다.

에러 타입을 직접 구현하여 적절하게 상황에 따른 에러 처리를 진행해주셨습니다! 코멘트 남겨드린 것처럼 LocalizedError도 한번 참고해보시면 좋을 것 같습니다.
코멘트 남겨주신 부분에 대한 수정하신 후 디스코드 DM으로 남겨주시면 빠르게 확인 후 Merge 해드리겠습니다!

---

**Q1. try? 구문을 사용하면 catch를 따로 선언하지 않아도 이 경우에는 해당 선언자체가 옵셔널로 선언되어 에러를 감지할 수 없다는 뜻인가요?**
A. 루틴을 실행하는 부분에서 `try?`을 사용하셨는데요! 에러가 발생했을때 nil 처리한 후 계속 진행하기 때문에 catch문에서 에러를 잡아낼 수 없게 되어 코멘트에 남겨드린 스크린샷처럼 루틴이 종료되지 않고 계속 이어지게 됩니다.

2022-11-10 08:59 UTC, seu0313 commented on CodeStarterCamp_Week4/ActivityError.swift
> +        }
Error를 잘 구현해주셨습니다 👍 추후에 [LocalizedError](https://developer.apple.com/documentation/foundation/localizederror)에 대해 알아보시는 것도 추천합니다

2022-11-10 08:59 UTC, seu0313 commented on CodeStarterCamp_Week4/Routine.swift
> +        }
피로도에 대한 에러 처리를 해주셨군요 👍

2022-11-10 08:59 UTC, llingo commented on CodeStarterCamp_Week4/main.swift
> +            bodyCondition.fatigue += exercise.fatigue
고차함수 map을 사용하셨군요 👍

2022-11-10 08:59 UTC, llingo commented on CodeStarterCamp_Week4/KoreanNumber.swift
> +    case one = 1
요구사항의 출력 예시 때문에 구현하셨군요 😮

2022-11-10 08:59 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +            throw ActivityError.unknown
unknown은 "알 수 없음"의 의미인 것 같아요. 에러가 발생했을때 어떤 에러가 발생했는 지 알기 어려울 것 같습니다!

2022-11-10 08:59 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +                try? startActivity(condition: condition)
`try`를 사용하는 것이 좋을 것 같아요! `try?`를 사용하게되면 에러가 발생했을때 nil 처리하여 catch문으로 빠지지 않기 때문에 아래 스크린샷과 같이 루틴을 종료하지 않고 계속 진행하게 됩니다.

![스크린샷 2022-11-10 오후 5 48 20](https://user-images.githubusercontent.com/94151993/201043841-cb506f60-6080-4812-bd4b-825fd240a905.png)

2022-11-10 10:29 UTC, 500beckwon commented on CodeStarterCamp_Week4/Routine.swift
> +            throw ActivityError.unknown
wrongInput으로 바꾸었습니다

2022-11-10 10:30 UTC, 500beckwon commented on CodeStarterCamp_Week4/Routine.swift
> +                try? startActivity(condition: condition)
? 을 제거하였습니다

2022-11-10 10:40 UTC, 500beckwon commented on CodeStarterCamp_Week4/ActivityError.swift
> +        }
errorMessage를 삭제하고 LocalizedError를 사용하였습니다

2022-11-10 15:31 UTC, llingo commented on CodeStarterCamp_Week4/ActivityError.swift
> +        }
LocalizedError가 적용이 안되어있는 것 같아요! 확인 부탁드립니다 👀

2022-11-11 05:04 UTC, llingo approved these changes
@500beckwon 님!

이번 주차 미션동안 수고하셨습니다! 다음 주차도 화이팅입니다 🎉

2022-11-11 05:04 UTC, merged

2022-11-16 12:45 UTC, ElonPark commented on CodeStarterCamp_Week4/ActivityError.swift
> +        }
swift custorm error description으로 검색해보시는걸 추천 드릴께요

2022-11-16 12:46 UTC, ElonPark commented on CodeStarterCamp_Week4/KoreanNumber.swift
> +    case one = 1
첫번째 케이스만 1로 지정하면 나머지는 생략해도 순서대로 지정돼요