Week4 [Step2] 송중
yagom-academy/swift-starter-Round4 pull request #96
Opened 2022-11-15 05:57 UTC by kimseongj

@llingo 
안녕하세요 링고 Week4 step입니다!
## 조언이 필요한점
### 깃허브 브랜치 관련..
(kimsj-Step2)브랜치를 새로 만들어서 yagom-academy/swift-starter-week4의 ss_6_kimsj 브랜치로 PR을 보내려고 하는데 
![image](https://user-images.githubusercontent.com/88870642/201837185-4ccf2c01-344c-430d-949e-21da3279b24c.png)
이러한 오류가 떴습니다..! 어떻게 해결하면 좋을까요? 
브랜치를 다시 kimsj로 바꿔서 제출을 했습니다 ㅠ

2022-11-15 10:26 UTC, llingo requested changes
안녕하세요 @kimseongj 님
벌써 이번 주차의 마지막 PR이네요 🎉

이번 STEP의 중점사항은 다음과 같습니다.
- [x] 사용자와 상호작용하는 완성된 프로그램을 만들어봅니다.
- [x] 원하는 방식으로 에러를 처리합니다.

강제 옵셔널 추출은 가급적 사용을 지양하는 것이 좋아보입니다 👀
남겨드린 코멘트 확인하시고 수정 부탁드립니다 :) 수정 후 DM이나 멘션 남겨주시면 바로 확인하겠습니다!

---

**Q1. 이러한 오류가 떴습니다..! 어떻게 해결하면 좋을까요?**
A. `kimsj-Step2` 브랜치가 `kimsj`의 마지막 커밋 후에 생성된 브랜치가 맞을까죠? 이전에 생성된 브랜치라면 `kimsj`의 변경사항이 반영되어 있지 않기 때문에 충돌나는 것으로 보이네요. 에러가 발생한 환경에 대한 정보가 부족해서 확실하지는 않지만 위의 내용이 맞을까요? 🤔

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/input.swift
> +import Foundation
input.swift 파일은 무엇을 위한 파일일까요? 🤔

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +        print("default error catch")
Error 타입을 구현하셔서 에러 처리를 해주셨군요! 좋습니다 👍

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +}
파일 분리를 잘해주셨습니다! 에러 타입도 분리할 수 있을 것 같아요 👍

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/main.swift
> +//}
사용하지 않는 코드는 제거하는 것이 좋아보입니다 :)

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +    func pro(bodyCondition: BodyCondition) {
함수명이 `pro` 인가요?

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +        let inputString = readLine()!
readLine에 nil 값이 들어가는 경우, 값을 강제 추출할 때 프로그램이 강제 종료될 것 같아요. 
적절한 옵셔널 처리를 하면 좋을 것 같아요 :)

`control + i` 를 통해 코드 블록의 줄을 정리할 수 있습니다.

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +    guard inputString.allSatisfy({$0.isNumber}) else {
`allSatisfy` 메서드는 어떤 기능을 하는 메서드 인가요? 

```swift
guard inputString.allSatisfy({ $0.isNumber }) else { ... 
```
이 좋아보입니다 :)

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +    let inputNumber = Int(inputString)!
바로 위의 에러 처리를 통해 프로그램이 종료되지는 않지만 강제 추출 사용을 가급적 지양해야 한다고 생각됩니다!

2022-11-15 10:26 UTC, llingo commented on CodeStarterCamp_Week4/Routine.swift
> +    for number in 0..<inputNumber{
```swift
for number in 0..<inputNumber {
                             ⬆️
```
한칸을 띄우면 더 좋을 것 같아요 :)

2022-11-15 10:45 UTC, kimseongj commented on CodeStarterCamp_Week4/Routine.swift
> +    func pro(bodyCondition: BodyCondition) {
네.. ㅎㅎ 상급자를 표현하고 싶어서 pro라고 함수명을 정한거 같군요!

2022-11-15 10:47 UTC, kimseongj commented on CodeStarterCamp_Week4/Routine.swift
> +        let inputString = readLine()!
이 부분은 readLine을 찾와봤는데, readLine을 하고 아무것도 작성이 되지 않으면 nil값이 들어가지 않고 ""형태로 값이 들어가기 때문에 강제추출을 하였습니다!

2022-11-15 10:48 UTC, kimseongj commented on CodeStarterCamp_Week4/Routine.swift
> +    guard inputString.allSatisfy({$0.isNumber}) else {
allSatisfy는 문자열 혹은 배열에서 원소 하나가 만족하는지 안하는지 알려주는 반환값이 bool인 함수입니다!

2022-11-15 10:48 UTC, kimseongj commented on CodeStarterCamp_Week4/Routine.swift
> +    let inputNumber = Int(inputString)!
수정하겠습니다!

2022-11-15 10:49 UTC, kimseongj commented on CodeStarterCamp_Week4/Routine.swift
> +    for number in 0..<inputNumber{
헉 이런 부분을 자꾸 놓치는군요 감사합니다!

2022-11-15 10:55 UTC, kimseongj commented on CodeStarterCamp_Week4/Routine.swift
> +        let inputString = readLine()!
추가적으로  ctrl+d 를 누르면 아무것도 안눌른것으로 되어 nil값이 된다고 합니다.
일반적으로 사용자들은 입력값을 안넣을 때 "Enter"만 입력할거라 생각되어 강제 추출을 하였지만 수정하겠습니다!

2022-11-15 10:57 UTC, kimseongj commented on CodeStarterCamp_Week4/input.swift
> +import Foundation
A. kimsj-Step2 브랜치가 kimsj의 마지막 커밋 후에 생성된 브랜치가 맞을까죠? 이전에 생성된 브랜치라면 kimsj의 변경사항이 반영되어 있지 않기 때문에 충돌나는 것으로 보이네요. 에러가 발생한 환경에 대한 정보가 부족해서 확실하지는 않지만 위의 내용이 맞을까요? 🤔 -> 이 부분이 맞는거 같아요..! Week5를 진행할 때 해보겠습니다!

2022-11-16 04:28 UTC, seu0313 commented on CodeStarterCamp_Week4/Error.swift
> +}
@kimseongj
이 부분도 같이 Error.swift 파일로 이동한 이유가 있을까요?
파일 이름이 Error.swift보다는 RoutineError.swift 가 더 좋을 것 같아요!

2022-11-16 04:28 UTC, seu0313 commented on CodeStarterCamp_Week4/Routine.swift
> +    func pro(bodyCondition: BodyCondition) {
더 구체적인 네이밍이면 좋을 것 같아요! :)

2022-11-16 08:36 UTC, llingo approved these changes
@kimseongj 님

이번 스탭 수고하셨습니다. 다음 스탭도 화이팅입니다 🎉

2022-11-16 08:36 UTC, merged